### ISSUE TITLE
Calculate data limits when sending credit

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1009]
Right now we send frames that update flow control if we get a corresponding `_BLOCKED` frame or when we cross certain thresholds.  At that point, a new frame is pushed into the `FlowMgr` for later sending.

The limits on the frame is set at the time that we decide that sending a frame is necessary.  That's not great, because more credit might be available by the time it comes to send the frame.  Better to calculate available space at the time the frame is sent.

This likely means changing the way that `FlowMgr` works, but it means holding less state.  The state that is held then is what type of frame is needed, what the contents are.

**Comment by ddragana** [comment]
This has been fixed.
