### ISSUE TITLE
Keep-alive API

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1038]
In at least HTTP it would make sense to have an API for keeping the connection alive.  Mostly, this is for when we have requests outstanding and haven't received a response.  We want to make sure that responses don't hit a closed NAT binding.

As multiple actors might be independently using this API, it probably makes sense to use a reference-counted hold.  `std::rc::Rc<()>` might be able to do the job, for instance.  The transport can hold a weak reference that - if it resolves - indicates that a keep-alive is necessary.  Then we can send a packet (containing PING) if the connection is idle for N seconds (where N is something like half our idle timeout).  We might be able to use our idle timeout start time, except that we probably need to retain a value that tracks if we have sent the ping; otherwise we'll send too often - sending the ping won't necessarily refresh the idle timeout start time.

Our HTTP code should use this API.

**Comment by ddragana** [comment]
Fixed by #1160
