### ISSUE TITLE
Failure to load dynamic library when running neqo-server

### ISSUE THREAD

**Issue by yaseco** [mozilla/neqo#1045]
from` /neqo/target/debug` I'm running the following command:

`./neqo-server [::]:12345
`
I'm getting the following error:

thread 'main' panicked at 'NSS_Initialize failed: NssError { name: "PR_LOAD_LIBRARY_ERROR", code: -5977, desc: "Failure to load dynamic library" }', /root/neqo/neqo-crypto/src/lib.rs:134:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How to fix that?

**Comment by martinthomson** [comment]
You need to point to the NSS binaries using LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH if you are on a mac).  It's a limitation of our build setup that we can't write rpath into binaries.  I don't know where to find that, but you might be able to do something like this:

```sh
export LD_LIBRARY_PATH="$(dirname "$(find . -name libssl3.so -print)")"
```

or for a mac 

```sh
export DYLD_LIBRARY_PATH="$(dirname "$(find . -name libssl3.dylib -print)")"
```

I haven't tested either.

`cargo run` probably doesn't suffer from this problem unless you use an external NSS.

**Comment by marcblanchet** [comment]
ran into same problem. response of @martinthomson works. Suggest to add it to the readme explicitly.

**Comment by valenting** [comment]
I think `cargo run --bin neqo-server -- [::]:12345 --db ./test-fixture/db` and `cargo run --bin neqo-client [URL]` should work instead.

**Comment by marcblanchet** [comment]
> I think `cargo run --bin neqo-server -- [::]:12345 --db ./test-fixture/db` and `cargo run --bin neqo-client [URL]` should work instead.

fine. would be useful to update the README.
