### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1052]
~1.8% of HTTP3 connection is closed with the INTERNAL_ERROR code. We should look into this.

**Comment by martinthomson** [comment]
Is this down to us encountering an internal error, or receiving CONNECTION_CLOSE?

**Comment by ddragana** [comment]
I think it is us (I need to investigate a bit).  This error is more common when necko gets ConnectionClosing event not ConnectionClosed event.

Looking at [this](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2020-12-01&include_spill=0&keys=closed!closing!__none__!__none__&max_channel_version=beta%252F84&measure=HTTP3_CONNECTTION_CLOSE_CODE&min_channel_version=null&processType=*&product=Firefox&sanitize=0&sort_by_value=0&sort_keys=submissions&start_date=2020-11-16&table=0&trim=0&use_submission_date=0).

**Comment by ddragana** [comment]
I was thinking about adding a "comment" to each place we set this error and collect telemetry on this comments. Comments can be just a enumeration.

**Comment by ddragana** [comment]
PR #1070 should help use narrow down this problem.

**Comment by ddragana** [comment]
We have separated this errors a bit better and the general InternalErrors are not a problem any more.
