### ISSUE TITLE
Crash: assert!(body.len() <= 2048); in neqo-transport/src/crypto.rs#l549

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1053]
0 xul.dll RustMozCrash mozglue/static/rust/wrappers.cpp:16
1 xul.dll mozglue_static::panic_hook mozglue/static/rust/lib.rs:89
2 xul.dll core::ops::function::Fn::call<fn ../18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
3 xul.dll std::panicking::rust_panic_with_hook ../18bf6b4f01a6feaf7259ba7cdae58031af1b7b39//library/std/src/panicking.rs:573
4 xul.dll std::panicking::begin_panic::{{closure}}<str*> ../18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:498
5 xul.dll std::sys_common::backtrace::__rust_end_short_backtrace<closure-0, !> ../18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
6 xul.dll std::panicking::begin_panic<str*> ../18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
7 xul.dll neqo_transport::crypto::CryptoDxState::encrypt third_party/rust/neqo-transport/src/crypto.rs:552
8 xul.dll static neqo_transport::packet::PacketBuilder::build third_party/rust/neqo-transport/src/packet/mod.rs:320
9 xul.dll neqo_transport::connection::Connection::output third_party/rust/neqo-transport/src/connection/mod.rs:1408

**Comment by ddragana** [comment]
Necko bug: [1680447](https://bugzilla.mozilla.org/show_bug.cgi?id=1680447)

**Comment by KershawChang** [comment]
It seems the only possibility to hit this assertion is by encoding a very long string here [1]. However, it's not clear to me how this could happen.
@martinthomson , do you have any idea here?

[1] https://github.com/mozilla/neqo/blob/0b1a39872a1c8d0d3c58fcd0e48d8fa22ec63a87/neqo-transport/src/connection/mod.rs#L1534

**Comment by martinthomson** [comment]
Ahh, if this is `output_close` then we can avoid that by truncating the reason phrase.  I don't know why that would be long, but the number of places that it is called from would make it hard to diagnose.  How about we truncate the string to `min(256, available space)`?

**Comment by ddragana** [comment]
This is not fixed.

**Comment by martinthomson** [comment]
I don't see a trace in the bug.  Is it the same stack?

**Comment by ddragana** [comment]
There are 2 different:
(the session is not in closing state) https://crash-stats.mozilla.org/report/index/3999a8e4-cc60-4549-8c99-b49fe0201216
and 
(the session is in Closing/Draining state) https://crash-stats.mozilla.org/report/index/3c930eac-4010-452e-acb4-b9da80201216

**Comment by ddragana** [comment]
The crash started around November 3rd. We had a neqo update short before that.
The bug is introduce between version 0.4.13 and 0.4.14:
https://github.com/mozilla/neqo/compare/v0.4.13...v0.4.14

**Comment by ddragana** [comment]
probably this commit:
https://github.com/mozilla/neqo/commit/a7d7354975d31d76b2ab64edbf845d39df956e20

**Comment by ddragana** [comment]
I am wondering if the stack for the crashes in the "Closing" state are correct. Maybe just the stack is wrong and all crashes are in the other code path.

**Comment by martinthomson** [comment]
Yeah, same.  We should concentrate on the non-closing case.

I found a bug here: https://github.com/mozilla/neqo/blob/ec22f2f9590dae27242b5f7814f5d6270665a6ae/neqo-transport/src/flow_mgr.rs#L359-L363

Note that the comparison doesn't count the length of the frame type.  Hard to see how that would turn into ~700 bytes though.

I'll keep looking.

**Comment by martinthomson** [comment]
I was looking at the migration code and it added the following to the `PacketBuilder`:
```rust
        if self.len() > self.limit {
            qwarn!("Packet contents are more than the limit");
            debug_assert!(false);
            return Err(Error::InternalError);
        }
```

Maybe we can use that as a safeguard.  It's not perfect, but it shouldn't crash with that guard in place.  I've verified that we never set the limit higher than our (currently fixed) MTU.

**Comment by ddragana** [comment]
This is also wrong, bu it is not cause this crash:
[link](https://github.com/mozilla/neqo/blob/a7d7354975d31d76b2ab64edbf845d39df956e20/neqo-transport/src/flow_mgr.rs#L345-L350)

                    if builder.remaining() < 1 + data.len() {
                        builder.encode_varint(frame.get_type());
                        builder.encode(data);
                        tokens.push(RecoveryToken::Flow(self.next().unwrap()));
                        continue;
                    } else {

**Comment by ddragana** [comment]
I have spent a big part of my day today, trying to figure it out, except the comment above, I have not found anything.

**Comment by martinthomson** [comment]
Yikes, that token thing is bad.  But you are right that it isn't likely to be our culprit.

**Comment by ddragana** [comment]
It looks like this has been fixed. Lets wait for a bit longer before closing the issue.

**Comment by ddragana** [comment]
There is no indication that this is still an issue.
