### ISSUE TITLE
Add a new HTTP3 server to reject 0-rtt

### ISSUE THREAD

**Issue by KershawChang** [mozilla/neqo#1058]
Not sure if we already have something similar in our code. This needs to be figured out.

**Comment by martinthomson** [comment]
There is an API, but it's buried.  You need to implement `ZeroRttChecker`, which is in neqo-crypto.  You pass a reference to that into the `enable_0rtt` function on the server side.  There are four outcomes for this.  

You might find it useful to support all outcomes when you implement a flag for neqo-server, though I realize that inducing HelloRetryRequest could be fiddly (you could just pass a zero-length array to keep things simple).  The nice thing about HelloRetryRequest is that it adds latency in a reliable fashion.

**Comment by ddragana** [comment]
Fixed by #1150
