### ISSUE TITLE
neqo-client will (successfully) fetch from an unspecified address

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1080]
This is a little bizarre, but apparently this works.  Up to a point.  It hits a debug assertion because we have created a path with a remote address that is unspecified and that doesn't work so well.  Still, it might be worth blocking a remote address that is unspecified.

**Comment by larseggert** [comment]
OBE?

**Comment by larseggert** [comment]
Closing on the assumption that this is OBE.
