### ISSUE TITLE
Fetch API is difficult to use

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#110]
Right now we have:

```rust
fn fetch(&mut self, method: &str, scheme: &str, host: &str, path: &str, headers: &[(String, String)])
```

Which leads to things like:

```rust
         let request_stream_id = hconn
            .fetch(
                &"GET".to_string(),
                &"https".to_string(),
                &"something.com".to_string(),
                &"/".to_string(),
                &Vec::<(String, String)>::new(),
            )
```

Though this makes the signature horrific, this is much nicer to use:

```rust
fn fetch<SM,SS,SN,SP,IH>(
    &mut self, method: SM, scheme: SS, host: SN, path: SP, headers: IH
)
where
  SM: AsRef<String>,
  SS: AsRef<String>,
  SN: AsRef<String>,
  SP: AsRef<String>,
  IH: IntoIterator<HeaderField>
```

That requires making a new type for header fields (the tuple is a problem anyway), and using separate types for each.  That enables flexible mixes of string literals (`&str`) and owned values (`String`) for all arguments aside from the last, where I think that we want to encourage the use of a type.

**Comment by agrover** [comment]
Current code allows `hconn.fetch("GET", "https", "something.com", "/", &[])` I think we just missed cleaning up a few spots from when fetch took owned strings.

**Comment by martinthomson** [comment]
I was basing this off the changes in #108.  I think we're good except for the HeaderField piece.  Which can be done separately.
