### ISSUE TITLE
does client support migration? how to use it in my code

### ISSUE THREAD

**Issue by xcy19920603** [mozilla/neqo#1111]

**Comment by martinthomson** [comment]
Connection has a [migrate function](https://github.com/mozilla/neqo/blob/fac4753e108d64e2b107b49eac3062f8106fbdc6/neqo-transport/src/connection/mod.rs#L1527-L1537).  I don't believe that this is exposed at the HTTP/3 layer though.

**Comment by xcy19920603** [comment]
done think you
