### ISSUE TITLE
H3 Client connecting NssError

### ISSUE THREAD

**Issue by xcy19920603** [mozilla/neqo#1115]
H3 Client connecting: V4(0.0.0.0:57951) -> V4(127.0.0.1:12345)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NssError { name: "SEC_ERROR_NO_TOKEN", code: -8127, desc: "The security card or token does not exist, needs to be initialized, or has been removed." }', neqo-transport/src/crypto.rs:378:30
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: core::result::Result<T,E>::unwrap
  10: neqo_transport::crypto::CryptoDxState::new_initial
  11: neqo_transport::crypto::CryptoStates::init
  12: neqo_transport::connection::Connection::new_client
  13: neqo_client::client
  14: neqo_client::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal
  17: std::rt::lang_start
  18: main

**Comment by martinthomson** [comment]
This looks like an NSS initialization error.  The `-d` option needs to refer to a valid database (one is included in the repository in `test-fixture/db`).
