### ISSUE TITLE
Investigate dash.cloudflare.com connection errors

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1117]
From folks at CF:
> we've noticed intermittent failures on dash.cloudflare.com in Firefox beta and Nightly with HTTP/3 enabled. This seems slightly reproducible: login, navigate around the tabs, maybe step away for a few minutes and then return to browsing. requests start faling and the console reports "NetworkError while attempting to fetch resource". This can manifest as popups reporting failures about API endpoints, and worse case the page changes to "it looks like we're having some internal issues" 

As we're seeing non-trivial numbers of connection errors, this might be a good place to start looking.  Maybe this is just a case of us needing to properly interpret error codes as safe to retry.

**Comment by ddragana** [comment]
The patch that should treat some errors as safe to retry landed yesterday(maybe it is only in today's Nightly). This is worth retesting.

**Comment by ddragana** [comment]
@martinthomson can you recheck with reporter if this is still a issue?

**Comment by martinthomson** [comment]
Checked and we can open a new issue if things come up.
