### ISSUE TITLE
I am hitting an assertion in hrtime.rs

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1118]
https://github.com/mozilla/neqo/blob/d086a329fd4ac17c9f6d146ac72d3ac5e3f0ace9/neqo-common/src/hrtime.rs#L179

**Comment by martinthomson** [comment]
Maybe we can just remove those assertions.  If this doesn't work, the consequence isn't that severe.  Is this reproducible?

**Comment by ddragana** [comment]
yes, I am debugging it.

I found out that this may fail, e.g. if system is busy. But the failure is very reproducible on 2 neqo tests, so I am no sure if it is the problem with the system being busy.
