### ISSUE TITLE
how to make neqo client use tls1.3？

### ISSUE THREAD

**Issue by shaocongliang** [mozilla/neqo#1129]
I am trying to test http3 use nginx-quic(server) and neqo-client, but the web-server return  error. nginx's error log:
````
SSL_do_handshake() failed (SSL: error:100000a4:SSL routines:OPENSSL_internal:MISSING_EXTENSION:extension 65445 error:100000be:SSL routines:OPENSSL_internal:PARSE_TLSEXT)
````
I try to use wireshark to find the reason and blow is the first network packet screenshot
![image](https://user-images.githubusercontent.com/30583506/111308191-56d54a80-8695-11eb-81b2-ee0e3c883527.png)

It seems the neqo-client use tls1.2 and this cause the handshake fail. 

- OS version: ubuntu:20.04 (client and server are the same version, they run on the docker container with host network mode)
- nginx version: [nginx-quic](https://hg.nginx.org/nginx-quic/shortlog/quic)

**Comment by martinthomson** [comment]
The "error" you highlight is just how TLS 1.3 works.  (If you expand the supported_versions extension, you will see TLS 1.3 listed there.)

The problem might be down to version skew.  The alert is the result of nginx-quic missing the quic_transport_parameters extension, which is identified as 65445 (or 0xffa5).  That number is the identifier for the TLS extension that was used for draft versions of QUIC.  As neqo uses QUIC version 1 now, the extension is 0x39 instead.  I don't know why nginx-quic accepts QUIC version 1 without the right extension, but I suspect that it is the result of not having the right version of BoringSSL or something like that.  I would take this issue up with nginx-quic people after checking whether it is a local configuration issue.
