### ISSUE TITLE
QUIC over IP support

### ISSUE THREAD

**Issue by erkinalp** [mozilla/neqo#1147]
QUIC, despite being specified as over UDP, could also work without UDP since it carries all necessary information. Add QUIC over IP support.

**Comment by align-dk** [comment]
IMO, it will require new IP [protocol number](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers), which cause some problems with routers and firewall not knowing about new proto.

**Comment by martinthomson** [comment]
@align-dk is right (it also requires a few other changes or constraints).  But this isn't really the place to discuss this.  The venue for discussing modifications to the protocol is the IETF (quic@ietf.org specifically).
