### ISSUE TITLE
How to cite neqo in a thesis?

### ISSUE THREAD

**Issue by CrashingBrain** [mozilla/neqo#1148]
As part of my thesis I worked on the codebase of neqo adding functionalities regarding Website Fingerprinting.

What would be the appropriate way to cite neqo or the codebase (possibly BibTex)?

**Comment by martinthomson** [comment]
We haven't done anything here in the past, but you can follow established conventions for academic research.  Treating this like a URL and using something like: `[2]  Mozilla neqo implementation. <https://github.com/mozilla/neqo>.  Accessed:  $DATE.` would probably do the trick.  I don't know how to produce the associated BibTex.

Good to hear that work continues on WF.  I'd be interested in what you learn from your research.  The last research we saw on QUIC and HTTP/3 showed that the WF leakage was worse than TLS and HTTP/2.  More information here could mean that we can find practical mitigation strategies.

**Comment by CrashingBrain** [comment]
Thanks that will do.

We are also working on a paper connected to my thesis' work so I can't say much more without asking my supervisor. But pretty soon it will be available to the public I guess.
