### ISSUE TITLE
Maybe don't save so many datagrams

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1152]
MAX_SAVED_DATAGRAMS is currently 32.  That's quite a bit of stuff to hold on to (~40k at worst).

Telemetry for HTTP3_SAVED_DGRAMS shows a very sharp drop off:

| Packets | Cumulative Count |
|---|---|
| 1 | 2.24B (95.86%) |
| 2 | 2.29B (98.04%) |
| 3 | 2.31B (98.93%) |
| 4 | 2.32B (99.42%) |
| 5 | 2.32B (99.57%) |
| 6 | 2.33B (99.69%) |
| 7 | 2.33B (99.75%) |
| 8 | 2.33B (99.81%) |
| 9 | 2.33B (99.84%) |

No point in saving many beyond 8.  It would be reasonable to stop at 4.  2 would be defensible.

**Comment by JaydenElliott** [comment]
Can this issue be closed?

**Comment by martinthomson** [comment]
Yep.  Thanks.
