### ISSUE TITLE
Point out differences to Quiche

### ISSUE THREAD

**Issue by mre** [mozilla/neqo#117]
[quiche](https://github.com/cloudflare/quiche/) is another QUIC implementation written in Rust.
It would be helpful to point out major differences between the two projects in the documentation.

**Comment by o0Ignition0o** [comment]
I think it would be a great idea indeed.

FWIW [I've been digging a bit](https://bugzilla.mozilla.org/show_bug.cgi?id=1158011#c15) and a quinn / quiche integration into gecko would be too hard (I think the TLS / Crypto modules are part of [NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS)), which is the reason why this crate was born.

IMHO It would indeed be better if it was clearly shown in the readme. 
I can submit a patch if a main contributor of neqo would like me to :)

**Comment by martinthomson** [comment]
See #81.
