### ISSUE TITLE
Move some functions from RecvMessage into the Header structure

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1174]
Maybe for later, but large chunks of this function can now move to Header.  Think about a function that returns `Res<enum {
  Pseudo(MessageType, enum { Method, Authority, ... } ),
  Regular,
}>`

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/1172#discussion_r657570069_

Also we may consider making a Headers structure that wraps Vec<Header> has functions to classify headers as interim response, verify headers, etc.

**Comment by ddragana** [comment]
This will be fixed by #1275

**Comment by larseggert** [comment]
Closing, since #1275 got merged.
