### ISSUE TITLE
Disable PTO at server if path is not validated

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1183]
We currently send probes on PTO always.  However a server is not allowed to when the active path hasn't been validated.  This is preventing us from passing amplification limit tests.

This is not particularly urgent as we don't ship a server currently.  But it is also a relatively small amount of work.  The only challenge might be getting the path validation state to the right place(s).  We have tests for the amplification limit, but these are flawed (they pass, they should not), so the biggest part of this work is in tweaking those tests.

**Comment by larseggert** [comment]
Things seem to have deteriorated in the meantime. The server makes the initial path permanent before it sends the server-initial, so the entire (possibly still flawed) amplification logic is disabled.
