### ISSUE TITLE
Bug 1727148

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1209]
Bug [1727148](https://bugzilla.mozilla.org/show_bug.cgi?id=1727148)

This may be:
https://searchfox.org/mozilla-central/rev/4cca5d2f257c6f1bcef50a0debcbd66524add703/third_party/rust/neqo-transport/src/recovery.rs#651

**Comment by ddragana** [comment]
It looks like the same installation (on Linux) fails multiple times.

**Comment by martinthomson** [comment]
Another case where we might not have monotonic time.

How about:

```rust
if let Some(sample) = now.checked_sub(send_time) {
    rtt.update(&mut self.qlog, sample, ack_delay, confirmed, now);
}
```

And just let the sample disappear if time is not moving in a forward direction.

**Comment by martinthomson** [comment]
We should also do an audit for subtractions and see if we have any more cases that need similar treatment.

**Comment by ddragana** [comment]
yes, to both comments.
