### ISSUE TITLE
qpack uses lots of Vec<u8> args

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#121]
`&[u8]` would be better in almost every case I've seen.  That would simplify the code and likely make things more performant.

**Comment by undef1nd** [comment]
Heya,
I'm a newbie in Rust, but I'd like to give it a try if nobody is working on it.

**Comment by ddragana** [comment]
I think I have fix this in #440. I do not think any are left.

**Comment by ddragana** [comment]
Fixed by #440.
