### ISSUE TITLE
Time to raise the minimum rust version?

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1215]
https://app.circleci.com/pipelines/github/mozilla/neqo/3053/workflows/330fc7f3-1d6e-4ae6-85ea-ab410e7edd9b/jobs/3032 shows that the latest clap won't compile with the version of rust we are using in CI.

**Comment by ddragana** [comment]
Yes, we should.

**Comment by martinthomson** [comment]
Dupe to #1168.
