### ISSUE TITLE
Crash when running in FIPS-mode

### ISSUE THREAD

**Issue by msirringhaus** [mozilla/neqo#1239]
We are currently having the following problem with FF91esr: When run in FIPS-mode, Firefox crashes in neqo.
As it turns out the call to `hkdf::import_key(TLS_VERSION_1_3, cipher, salt)` in `new_initial()` in `third_party/rust/neqo-transport/src/crypto.rs` fails, because it tries to create a key from raw key material, which is not allowed in FIPS-mode.

**Comment by msmeissn** [comment]
It does PK_ImportSymKey to store key material, but a raw key import is not allowed in NSS in FIPS mode.

This seems just to do key derivation if I see this correctly, the key is discarded after the hdkf::expand without any further use.
perhaps this could be done without involving temporary keys?

**Comment by martinthomson** [comment]
Confirmed as working.
