### ISSUE TITLE
SendMessage could use BufferedStream

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1265]
SendMessage buffers header and on the server side also the response data. SendMessage could be simplify by using [BufferedStream](https://github.com/mozilla/neqo/blob/0961ba9dc1e36778effd8e7607665dbfa700e48c/neqo-http3/src/buffered_send_stream.rs#L11).

**Comment by larseggert** [comment]
It seems `BufferedStream` was introduced to `SendMessage` in #1270.
