### ISSUE TITLE
Avoid calling neqo_transport::dump_packet when not logging

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1268]
[1741031](https://bugzilla.mozilla.org/show_bug.cgi?id=1741031)

**Comment by valenting** [comment]
I think we should check `::log::max_level() `like we do [here](https://searchfox.org/mozilla-central/rev/fb8d77331582639ea6848a61dd8ee812fac31b77/third_party/rust/neqo-common/src/log.rs#15,29) and early return [here](https://searchfox.org/mozilla-central/rev/fb8d77331582639ea6848a61dd8ee812fac31b77/third_party/rust/neqo-transport/src/dump.rs#26) if we don't need to log anything.
