### ISSUE TITLE
test timeout in chaos mode test_http3_prio.js

### ISSUE THREAD

**Issue by mb** [mozilla/neqo#1271]
Came up in https://bugzilla.mozilla.org/show_bug.cgi?id=1734132#c11

> TEST-UNEXPECTED-TIMEOUT | netwerk/test/unit/test_http3_prio.js | Test timed out
> https://treeherder.mozilla.org/logviewer?job_id=358340689&repo=autoland&lineNumber=2007

Maybe related to neqo server. Opening due to discussion in meeting.

**Comment by larseggert** [comment]
@mb still an issue?

**Comment by mb** [comment]
I think dragana fixed fixed most/all http3 timeout bugs in [Bug 1768090](https://bugzilla.mozilla.org/show_bug.cgi?id=1768090). That fixed a lot of intermittent test timeouts including "[Intermittent netwerk/test/unit/test_http3_prio.js | single tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1760125)".

There are still some tests disabled due to this ([Bug 1773916](https://bugzilla.mozilla.org/show_bug.cgi?id=1773916) and [Bug 1675008](https://bugzilla.mozilla.org/show_bug.cgi?id=1675008)), but the root cause got fixed in one of draganas PRs here (not sure which) or the patch [D146951](https://phabricator.services.mozilla.com/D146951).
