### ISSUE TITLE
Currently CONNECTION_CLOSE is sent only in epoch 3.

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#128]
```
                State::Closing {
                    error,
                    frame_type,
                    msg,
                    ..
                } => {
                    if epoch != 3 {
                        continue;
                    }

                    if self.flow_mgr.borrow().need_close_frame() {
...
```

Martin's comment:

> 
> From what I can see, the frame builder should be adding the packet to every epoch on its on recognizance. Right now, we track whether CONNECTION_CLOSE has been sent, but we really need something more fine-grained. I see now that we only send CONNECTION_CLOSE in epoch 3, which is a mistake, so let's open an issue.
> 
> To add to that, we won't get loss signals for packets containing CONNECTION_CLOSE, we have to drive sending of the frame based on receipt of packets.

**Comment by agrover** [comment]
> I see now that we only send CONNECTION_CLOSE in epoch 3, which is a mistake

I think I missed in the spec where this is discussed. Can you point me to it?

**Comment by ddragana** [comment]
if you look at description for each packet type:
17.2.2.  Initial Packet has a sentence:

> PADDING and CONNECTION_CLOSE frames are also permitted

17.2.4.  Handshake Packet:

> Handshake packets MAY contain CONNECTION_CLOSE frames.

epoch 3 is clear.

**Comment by martinthomson** [comment]
The [relevant text](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#immediate-close) is:

> When sending CONNECTION_CLOSE, the goal is to ensure that the peer will process the frame. Generally, this means sending the frame in a packet with the highest level of packet protection to avoid the packet being discarded. However, during the handshake, it is possible that more advanced packet protection keys are not available to the peer, so the frame MAY be replicated in a packet that uses a lower packet protection level.

So the right thing to do (probably) is send at every epoch you have keys for.  Keeping in mind that we need to implement dropping of keys at some point, so that won't be every epoch.
