### ISSUE TITLE
Retiring the remote connection ID used during the handshake

### ISSUE THREAD

**Issue by WesleyRosenblum** [mozilla/neqo#1290]
When testing neqo server, after sending `NEW_CONNECTION_ID` frames requesting the retirement of the connection ID used during the handshake (sequence number 0), we are not receiving a `RETIRE_CONNECTION_ID` frame.

For example, when a client sends this frame to neqo:
```
NEW_CONNECTION_ID
    Frame Type: NEW_CONNECTION_ID (0x0000000000000018)
    Sequence: 1
    Retire Prior To: 1
    Connection ID Length: 16
    Connection ID: 0a0d2ab253240f0f348d03cf6bfb4bf2
    Stateless Reset Token: 6d7c068b2f8e7d0a553efae3c5147eaa
```
neqo should transmit a `RETIRE_CONNECTION_ID` frame with Sequence: 0, but it does not.

Maybe the initial connection ID is not being added to the `ConnectionIdStore`, and so it is not retired when the `NEW_CONNECTION_ID` is received?

Thanks for considering this issue and let me know if you need any further information!

**Comment by larseggert** [comment]
@WesleyRosenblum do you happen to have a way for us to reproduce this?

**Comment by WesleyRosenblum** [comment]
Looks like this is fixed! I checked a recent `DC` interop test, and I see neqo serving responding with `RETIRE_CONNECTION_ID`

**Comment by larseggert** [comment]
Thanks for confirming!
