### ISSUE TITLE
For fuzzing: we need to disable packet nember protection as well

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1324]
https://github.com/mozilla/neqo/blob/2e1785a6b3b85316a2451cdb2dc3027c192a7533/neqo-transport/src/crypto.rs#L371

I was trying to make artificial handshake packets so that fuzzing can jump to sending application data, but I run into a problem because packet numbers are protected.

**Comment by larseggert** [comment]
#1764 should address this.
