### ISSUE TITLE
Client generates misleading error output

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1334]
Our client issues this warning often:
```
Cannot create stream Err(Unavailable)
```
This is because we try to open a stream every time something changes.  Before the handshake has completed, this will fail, with the above error.  This is fine, so we probably shouldn't be printing this message.

**Comment by martinthomson** [comment]
It might be as simple as removing the message, or changing it to use our `qinfo!()` macro instead.

**Comment by dlrobertson** [comment]
Was just looking through the open issues, and I think this issue can be closed.

**Comment by martinthomson** [comment]
Closed by #1381.
