### ISSUE TITLE
Low Performance on Parallel request

### ISSUE THREAD

**Issue by feters** [mozilla/neqo#1335]
Hello, I am Feter, a Master's student at Lulea University.
I did a local test on Docker container using Neqo Server against Pico Client and the result is surprisingly low compared to other QUIC server implementations as far as I know Rust is a performance language. I used Ubuntu 20.04 image for the server and client. This is the result and how I did run the test:

Run Neqo Server
`
ionice -c 2 -n 0 nice -n -20 env RUST_LOG=trace cargo run --bin neqo-server -- [::]:7733 --db ./test-fixture/db --qlog-dir server_qlog
`

Test Case
Transfer file of 1GB in parallel 10 times

| Parallel Request | 10 | 50 | 100 |
| --- | --- | --- | --- |
| Throughput (Mbps ) | 179.468 | 23.564 | 15.011 |
| RTT (Seconds) | 1.79 | 8.043 | 13.074 |
| Transfer Time (Seconds) | 7.622 | 50.988 | 75.424 |

Are there any extra things I can do to increase the performance?
Thank you.

**Comment by martinthomson** [comment]
Rust might have low overheads, but it's possible that our code does not.

One major factor here is likely that our server is single-threaded.  It exists primarily so that we are able to test our client; no significant effort has been put into making the server performant.

**Comment by junhochoi** [comment]
@feters I think you can try again without `RUST_LOG=trace` and `--qlog-dir` option for less verbosity and see the difference.

**Comment by feters** [comment]
@martinthomson thank you
@junhochoi Okay I will try that, thank you very much

**Comment by larseggert** [comment]
Closing. @feters please reopen if this is still an issue.
