### ISSUE TITLE
WebTransport session should return the reponse headers

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#1364]
Currently when a response for a WebTransport session request is received neqo-http3 parses headers and performs some checks. The application is only informed of the response status code. neqo-http3 should return headers as well.

Current implementation returns `WebTransportEvent::Session {
        stream_id: StreamId,
        status: u16,
    },` if the response was between 200-300 and returns `WebTransportEvent::SessionClosed {
        stream_id: StreamId,
        reason: SessionCloseReason::Status(status),
    }` otherwise.  I think in both cases `WebTransportEvent::Session {...}` should be returned and should contain a response code and headers.

**Comment by dlrobertson** [comment]
Started working on this and should be able to post a PR soon. When updating something like this that will require changes to `neqo_glue`, what is the preferred workflow? Just create a bug in bugzilla for the next neqo update? Or would it be worthwhile to bump the version and update the crate?
