### ISSUE TITLE
Consider having a Headers type ? 

### ISSUE THREAD

**Issue by o0Ignition0o** [mozilla/neqo#137]
As explained in https://github.com/mozilla/neqo/pull/131#issuecomment-520134820 It might be useful to:

Move the Header type to the common crate.
Have only one Headers type, which would be `Vec<Header>`.

Replace uses of `&[Header]` (or `&[(String,String)]`) to use the new Headers type.

Not sure using a Vec instead of a slice ref for fix sized arrays has a performance impact.

What's your opinion ? :)

**Comment by agrover** [comment]
Not sure. That comment on #131 suggests the headers type but doesn't explain why it's a good idea. Would it shorten code, or make using headers less error-prone or more ergonomic?

One way see would be to just try making the change and see how it affects the code.

**Comment by martinthomson** [comment]
I think that the `Header` type can reasonably be moved to neqo-qpack (as opposed to neqo-common).  But I don't see much advantage to a collection new-type for a list of them unless we have some reason to associate behaviour with them.

Speculating, would this help ergonomics at all?

```rust
macro_rules! header {
  ($n:ident: $v:expr) => { Header { n: String::from(stringify!($n)), v: String::from($v) } };
}
macro_rules! headers {
  [ $($n:ident: $v:expr),* $(,)? ] => { [ $( header!($n: $v) ),* ] };
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5751f99a3c777461e5e07f14e31b012e

**Comment by o0Ignition0o** [comment]
I think I went a bit ahead of myself, trying to refactor too much for the sake of it ^^. A headers type is probably not required.

OTOH I tried moving the Header type to neqo-qpack, and reexporting it through neqo-http3 and it IMO looks more explicit to me.
Submitting a PR for you to decide whether it's worth it :)

**Comment by agrover** [comment]
lol I just suggested a headers type over in that PR. :smiley: I guess if we're not sure then just leave as-is for now.

**Comment by o0Ignition0o** [comment]
I think it will be changed once it gains enough traction :)
