### ISSUE TITLE
SNI/ESNI/ECH server support

### ISSUE THREAD

**Issue by DemiMarie** [mozilla/neqo#1378]

**Comment by valenting** [comment]
Hi @DemiMarie, do you mean the neqo server should support SNI/ECH?
It's only there for testing purposes, it's not meant to be a production ready server implementation.

**Comment by DemiMarie** [comment]
@valenting: what is the reason for the server not being intended for production?

**Comment by valenting** [comment]
The neqo library is a client side library that we currently use in Firefox.
