### ISSUE TITLE
Unify some of the configuration for the client and server tools

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1403]
As I noted in #1402, there is a lot of common stuff between the client and server command-line tools.  It would be good if we could unify some of this.

It might make sense to move this to a module under the mainline code (both neqo-transport and neqo-http3), covered by feature flags that the command-line tools enable.  Then, a standard build won't pull in a bunch of dependencies, but we have a single place for this stuff.

**Comment by larseggert** [comment]
CC @mxinden, since you're touching that code now.

**Comment by mxinden** [comment]
Close here in favor of the recent https://github.com/mozilla/neqo/issues/1696?

(Sorry for creating a ~duplicate in the first place.)

**Comment by larseggert** [comment]
Sure.
