### ISSUE TITLE
Support to send SETTINGS_H3_DATAGRAM to the server

### ISSUE THREAD

**Issue by KershawChang** [mozilla/neqo#1407]
Since the [implementation](https://github.com/aiortc/aioquic/blob/main/src/aioquic/h3/connection.py#L1095) of `aioquic` requires both `SETTINGS_ENABLE_WEBTRANSPORT` and `SETTINGS_H3_DATAGRAM`, maybe we should do this.

**Comment by martinthomson** [comment]
I see that aioquic is stuck on the pre-RFC version of this.  Are there changes in the RFC that might prevent us from sending them a pull request to change the codepoint?

**Comment by KershawChang** [comment]
> I see that aioquic is stuck on the pre-RFC version of this. Are there changes in the RFC that might prevent us from sending them a pull request to change the codepoint?

No, I don't think so. I'll try to create an issue and send a PR.

**Comment by bashi** [comment]
FWIW I sent a PR to update wpt test server. https://github.com/web-platform-tests/wpt/pull/39201
The PR should be merged once the CI problem is resolved.
