### ISSUE TITLE
Sort `use` statements

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1417]
I just learned that `cargo fmt` has a hidden [`imports_granularity`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity) configuration.  Even though this isn't stable and you can't create a `rustfmt.toml` file that includes the directive, you can still enable this by passing the `--config imports_granularity=Foo` parameter on the command line.

Right now, `use` statements are a bit of a mess.  Though they are sorted, no effort is made to consolidate or flatten them, so we have a mix of different patterns.  Automated application of a single style would be a big improvement.

I think we should enable this, using either the "Crate" or "Module" option.  I have a preference for "Crate", but could live with "Module".

**Comment by larseggert** [comment]
Need to use nightly
```
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
```
but then can also add it to `rustfmt.toml`.

**Comment by martinthomson** [comment]
There is a [another option too](https://github.com/private-attribution/ipa/blob/4292569224910c76231195d435dda3760cbb46f6/.github/workflows/check.yml#L52).

You can also configure your editor to do this on save:

```
"rust-analyzer.rustfmt.extraArgs": [
  "--config",
  "imports_granularity=Crate,,group_imports=StdExternalCrate"
]
```

This isn't perfect either, as a blank line will prevent use statements from being consolidated across that line.  But it would be a big improvement.

**Comment by larseggert** [comment]
I'll do a PR that adds that to the VS Code workspace settings, so at least those of us using that have it set.

(I'd also be happy to set `wrap_comments` - it's annoying to wrap those manually.)

**Comment by larseggert** [comment]
Well scratch that, because [VS Code doesn't allow non-shared workspace settings](https://github.com/microsoft/vscode/issues/40233).

**Comment by martinthomson** [comment]
@larseggert can you update our check.yml so that it checks using the `.rustfmt.toml` you added?  My understanding is that you need to run that with a nightly toolchain.  Perhaps we can switch from beta to nightly for that reason.
