### ISSUE TITLE
neqo-crypto-0.6.4 is broken in firefox nightly

### ISSUE THREAD

**Issue by stefson** [mozilla/neqo#1425]
hello everyone, 

I just learned that neqo-crypto-0.6.4 provided via the mozilla firefox source code, doesn't compile for me. It fails with: 

```
27:01.38   thread 'main' panicked at 'unable to generate bindings: ClangDiagnostic("error: unknown argument: '-mno-thumb-interwork'\n")', /var/tmp/portage/www-client/firefox-113.0/work/firefox-113.0/third_party/rust/neqo-crypto/build.rs:282:39
27:01.38   stack backtrace:
27:01.38      0:     0x55e4d261955a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0d52a35915fffbeb
27:01.38      1:     0x55e4d263e0de - core::fmt::write::hd30867c928528e61
27:01.38      2:     0x55e4d2616935 - std::io::Write::write_fmt::hc403056a57833035
27:01.39      3:     0x55e4d2619325 - std::sys_common::backtrace::print::h54d034229014d02f
27:01.39      4:     0x55e4d261ab0f - std::panicking::default_hook::{{closure}}::h4c9968a7ce9703d0
27:01.39      5:     0x55e4d261a84b - std::panicking::default_hook::h3659243b9a491a62
27:01.39      6:     0x55e4d261b219 - std::panicking::rust_panic_with_hook::h1e42a9ebf2e8998e
27:01.39      7:     0x55e4d261afb9 - std::panicking::begin_panic_handler::{{closure}}::h1aa0e1fd7f7248e0
27:01.39      8:     0x55e4d2619a0c - std::sys_common::backtrace::__rust_end_short_backtrace::hc17453f54d491454
``` 

The compile is not broken with neq-crypto-0.6.3, there are only two commits on top untill the current version, neq-crypto-0.6.4, is released. One of them: https://github.com/mozilla/neqo/commit/07c2019988a8f0a37f87cbd90f95e906e7b53258 does touch bindgen related things. 

@dlrobertson do you think something may have been unintentionally broken by your commit? 

full build log is attached: [neon-113-fails.log.gz](https://github.com/mozilla/neqo/files/11051019/neon-113-fails.log.gz)

**Comment by dlrobertson** [comment]
@stefson thanks for the report! I don't think the linked commit is causing this. Based on the log, it looks like you're cross compiling firefox on a `x86_64` for `armv7`? After a brief look in mozilla-central ([this commit](https://hg.mozilla.org/mozilla-central/rev/80c39fbdd3cc66add325ea29450293816bfec722)) looks like a likely culprit. AFAIK `thumb-interwork` flags are gcc only right? Perhaps `arm.configure` should have extra logic to avoid passing through extra arm flags that are known to be gcc only.

**Comment by stefson** [comment]
Oh wow, many thanks, that was spot on advice. I reverted the armv7 bindgen changes, and firefox compiled without errors. Thanks again, will close here and talk with upstream.

**Comment by dlrobertson** [comment]
@stefson Awesome! Could you post the bug link here?
