### ISSUE TITLE
neqo on riscv

### ISSUE THREAD

**Issue by kush930** [mozilla/neqo#1431]
Hi all,

I cloned neqo from link:- https://github.com/mozilla/neqo

During building neqo on target board, i am facing issue:- 

```
kush@Kush:~neqo$ cargo build

error: failed to run custom build command for `neqo-crypto v0.6.4 (/home/kush/Documents/neqo/neqo-crypto)`

Caused by:
  process didn't exit successfully: `/home/kush/neqo/target/debug/build/neqo-crypto-b92279dec34a68db/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NSS_DIR

  --- stderr
  thread 'main' panicked at 'can't clone nss: Os { code: 2, kind: NotFound, message: "No such file or directory" }', neqo-crypto/build.rs:111:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

Can anyone help me to build  neqo on riscv platform.

T&R
Lavkhush

**Comment by larseggert** [comment]
Could you build with `-v` and post the output here?

**Comment by martinthomson** [comment]
This looks very much like you don't have mercurial installed.  I'd hazard a guess that you don't have gyp and ninja either.  neqo has some particular requirements.

**Comment by larseggert** [comment]
Closing this due to lack of feedback. @kush930 please reopen if this is still an issue.
