### ISSUE TITLE
Block new requests after GOAWAY

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#144]
I think that we don't do anything special after receiving GOAWAY, but we should at least stop making new requests by rejecting any that are attempted.

**Comment by ddragana** [comment]
I am planning to do a big rewrite of neqo-http3/src/connection.rs next week. this should fix this as well.

**Comment by martinthomson** [comment]
Might be fixed, just confirm that it is properly tested.

**Comment by agrover** [comment]
fixed by #573
