### ISSUE TITLE
Cache randomness used for scrambling the packet header

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1456]
A small performance optimization here is probably justified.  We spend a lot of time just setting up to generate randomness, relative to the number of bits we get.

If we instead generated a bunch of bits, we could maybe save a lot of overhead.

See [this profile](https://profiler.firefox.com/public/9jv9xqck90eaab0gmqdwh1qb7z6qa9a12y1d4yr/flame-graph/?globalTrackOrder=b0wa&hiddenGlobalTracks=1w8&hiddenLocalTracksByPid=20412-1wdf~20176-0~3532-0~3480-01~8528-01~10760-01~7972-01~13352-01~18232-0w2~15688-013w7~19208-0wcewn&range=13606m7867&sourceView=hg%3Ahg.mozilla.org%2Freleases%2Fmozilla-release%3Athird_party%2Frust%2Fneqo-transport%2Fsrc%2Fpacket%2Fmod.rs%3A326212e7271a9c9f0776153095cf48d7153260aa&thread=1&transforms=ff-247&v=9)

**Comment by larseggert** [comment]
I think this was addressed in #1640.
