### ISSUE TITLE
investigate high CPU use in neqo_transport::send_stream::TxBuffer::next_bytes

### ISSUE THREAD

**Issue by jesup** [mozilla/neqo#1487]
See https://share.firefox.dev/3tXRSIb
next_bytes uses ~24% of the CPU in this trace, almost all of it in <alloc::collections::btree::map::Iter as core::iter::traits::iterator::Iterator>::next

**Comment by mb** [comment]
It seems to be this function being called repeatedly

https://github.com/mozilla/neqo/blob/2582acda8c9c2a1b00304e07f46be43246c56db7/neqo-transport/src/send_stream.rs#L168-L181

`self.used` is a [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html):

https://github.com/mozilla/neqo/blob/2582acda8c9c2a1b00304e07f46be43246c56db7/neqo-transport/src/send_stream.rs#L145-L151

`first_unmarked_range` is called repeatedly in
https://github.com/mozilla/neqo/blob/2582acda8c9c2a1b00304e07f46be43246c56db7/neqo-transport/src/send_stream.rs#L413-L414

**Comment by martinthomson** [comment]
The output of `first_unmarked_range()` looks to be totally cacheable.
