### ISSUE TITLE
Build needs `python` executable

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1493]
At least on MacOS, Python 3 no longer installs an executable named `python`, it's now `python3`. 

`gyp` and/or `neqo` seem to require the Python executable to be called `python`, however.

I can work around by creating a symlink from `python3` to `python`, but it would be better to fix this.

**Comment by martinthomson** [comment]
See #1343.  I had a patch up for that, but I believe that it bounced for reasons that elude me.

**Comment by larseggert** [comment]
Closing in favor of #1343.
