### ISSUE TITLE
Retry -- client role

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#15]

**Comment by martinthomson** [comment]
I have some code in there, but this needs:

1. tests
2. sending the original destination connection ID transport parameter from the server.
3. checking the original destination connection ID transport parameter at the client.

**Comment by agrover** [comment]
@martinthomson are you still hacking on this or were you looking for someone to pick up the work for the things mentioned?

**Comment by martinthomson** [comment]
Still hacking on this.  I just needed to write down what needs to happen.

**Comment by agrover** [comment]
@martinthomson let me know if you can work on this soon, or if I should pick it up. This is currenly blocking us from interoperating with F5, Cloudflare, and probably also other server implementations too.
