### ISSUE TITLE
macos CI seems to be building the wrong feature profile.

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1521]
https://github.com/mozilla/neqo/actions/runs/7257208473/job/19770667986?pr=1502#step:13:52 says:

```
warning: neqo-crypto v0.6.8 (/Users/runner/work/neqo/neqo/neqo-crypto) ignoring invalid dependency `mozbuild` which is missing a lib target
```

That suggests that we are looking at an error that is the result of passing the wrong features to `build.rs`.  Maybe we should avoid ~~`--all-features`~~ `--all-targets` [updated] when it comes to this repository.

**Comment by larseggert** [comment]
Did you mean `--all-targets`? (Because I don't see `--all-features` in the workflow file.)

**Comment by martinthomson** [comment]
Sorry, yes, that. :)

**Comment by larseggert** [comment]
I'm only getting this warning with `nextest`, not `test`. Hm.
