### ISSUE TITLE
`mio-extras` not being updated for mio>0.6

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1535]
See https://github.com/dimbleby/mio-extras:
> This library is not compatible with mio 0.7. However, there's a similar project named [mio-misc](https://github.com/onurzdg/mio-misc) that works with mio 0.7.

I haven't checked whether and how `mio-misc` could be used to provide `Timer` functionality for `neqo-server.`

See #1511

**Comment by mxinden** [comment]
@larseggert how about moving away from `mio` and instead use the higher-level [`tokio`](https://docs.rs/tokio/latest/tokio/) in `neqo-server` and `neqo-client`? Note that `tokio` is based on `mio`.

With my limited knowledge of `neqo-*`, I consider `tokio` the better fit for the problem. It has support for UDP sockets and timers and, given its higher level abstractions, is easier to use.

In case there is interest, I am happy to give it a shot and propose a pull request.

Related: https://github.com/mozilla/neqo/issues/530

**Comment by larseggert** [comment]
I'm running into issues trying to use quinn-udp for ECN packet I/O with the client and server code based on that old version of mio, so I'm even more in favor of tokio now.

CC @martinthomson @KershawChang

**Comment by KershawChang** [comment]
> I'm running into issues trying to use quinn-udp for ECN packet I/O with the client and server code based on that old version of mio, so I'm even more in favor of tokio now.
> 
> CC @martinthomson @KershawChang

+1 for using `tokio`.
I think the reason why we used `mio-extras` is that we want to use `mio_extras::timer`, but I assume we should be able to find an alternative for it.

**Comment by mxinden** [comment]
I have a draft in https://github.com/mozilla/neqo/pull/1581 with a basic client/server interaction working. Still needs more work. Will ping folks once it is ready. Not sure I will get to it this week though.

> I'm running into issues trying to use quinn-udp for ECN packet I/O with the client and server code based on that old version of mio, so I'm even more in favor of tokio now.

Yes. I expect the move to `quinn-udp` to be easy once https://github.com/mozilla/neqo/pull/1581 is merged. Happy to do that as a follow-up.

**Comment by larseggert** [comment]
I have some draft code for quinn-udp in https://github.com/larseggert/neqo/tree/feat-ecn-io, if you want to make that part of this PR.

**Comment by mxinden** [comment]
> I have some draft code for quinn-udp in https://github.com/larseggert/neqo/tree/feat-ecn-io, if you want to make that part of this PR.

:+1: porting https://github.com/larseggert/neqo/tree/feat-ecn-io onto https://github.com/mozilla/neqo/pull/1581 now @larseggert.

**Comment by larseggert** [comment]
We're now using `tokio`.
