### ISSUE TITLE
Don't format packets for dumping if qlog has not been configured to log

### ISSUE THREAD

**Issue by jesup** [mozilla/neqo#1548]
If the log::max_level() is Debug or Info, we'll spend the time to format packets in dump_packet() even if the qdebug!() will end up as a no-op, since we haven't configured a file for logging.

This can cost us 10% of a core when downloading over h3 on a high end machine.

The log level is a shared resource, so it can get bumped by other modules: https://bugzilla.mozilla.org/show_bug.cgi?id=1874215

**Comment by mxinden** [comment]
Maybe I can help here, though I would need some pointers. Sorry in case I am missing something obvious.

As far as I can tell the `qdebug!` call in `dump_packet` boils down to a call to `init` and `do_log!`:

https://github.com/mozilla/neqo/blob/9e6cd932b140fde141e6414d53f539b6d296d4f9/neqo-common/src/log.rs#L52-L72

https://github.com/mozilla/neqo/blob/9e6cd932b140fde141e6414d53f539b6d296d4f9/neqo-common/src/log.rs#L15-L33

`init` initializes the logger. While one can provide a custom target via `Builder::target` (i.e. an `fmt::Target`, e.g. a file), this is not done here, hence the default is chosen which is logging to `stderr`.

`do_log!` then takes the above initialized logger via the global `::log::logger()` and logs to it, i.e. logs to `stderr`.

> since we haven't configured a file for logging.

How would that file be configured? Are you referring to a pipe of the processe's `stderr` to a file? If so, how could one know within `dump_packet`?

Are you potentially confusing the `qdebug!` call with the similar [`qlog.rs`](https://github.com/mozilla/neqo/blob/main/neqo-common/src/qlog.rs) infrastructure?

Thank you @jesup. Again, sorry in case I am missing something obvious.

**Comment by larseggert** [comment]
I think the issue is that the condition `::log::Level::Debug > ::log::max_level()` is not sufficient to determine whether `qdebug!` will actually produce output.

For example, if I run with `RUST_LOG=info,neqo_transport::cc=debug`, the condition is not satisfied, but the `qdebug!` call still isn't logging anything.

**Comment by mxinden** [comment]
Thank you @larseggert. This was helpful. I created https://github.com/mozilla/neqo/pull/1601.
