### ISSUE TITLE
consider building and pushing Interop Runner Docker image in CI

### ISSUE THREAD

**Issue by marten-seemann** [mozilla/neqo#1552]
I noticed that the neqo interop runner image is now 3 years (!) old: https://hub.docker.com/r/neqoquic/neqo-qns/tags. I assume that building / pushing was done manually using [this script](https://github.com/mozilla/neqo/blob/main/qns/update.sh) so far.

May I suggest to push a new interop runner on every push to master, or on a daily (?) cron job? GitHub Actions has some predefined workflows that should make building and pushing Docker images pretty straightforward. For inspiration, [here](https://github.com/quic-go/quic-go/blob/master/.github/workflows/build-interop-docker.yml) is quic-go's workflow, and Quinn has [one](https://github.com/quinn-rs/quinn-interop/blob/main/.github/workflows/dockerhub.yml) as well.

**Comment by mxinden** [comment]
I am happy to contribute the required GitHub Action in case there is interest from the neqo maintainers.

**Comment by martinthomson** [comment]
@mxinden that would be great.  I had a cron job setup, but I can supply the necessary secrets to get something running if you want to do the initial work.  I remember having a bunch of problems with the docker hub setup at the time, so it might be easier to use the GitHub image store (I've moved to that for other projects).

**Comment by mxinden** [comment]
I prepared https://github.com/mozilla/neqo/pull/1554/. Let me know what you think.
