### ISSUE TITLE
CI Test fail

### ISSUE THREAD

**Issue by o0Ignition0o** [mozilla/neqo#156]
While working on #140 I triggered a weird CI error :

https://circleci.com/gh/mozilla/neqo/382

```
 test basic ... 0s  0ms ERROR error 1 Instant { tv_sec: 21764, tv_nsec: 122110911 } 

[...]

failures:

---- time::test::convert_stable stdout ----
thread 'time::test::convert_stable' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    time::test::convert_stable

test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

I'm having a very hard time trying to figure out what happened, and trying to make sure It won't ever happen again.

Maybe a good first step would be to default our CI test runs with RUST_BACKTRACE=1 or RUST_BACKTRACE=full so we make sure we have as much context as possible when hunting for such subtle/hard to reproduce quirks ?

It would have probably not helped in this case (It seems Instant/Time related) but It might prove useful later :)

**Comment by martinthomson** [comment]
This should be addressed by #147.
