### ISSUE TITLE
Crash in [@ neqo_transport::path::Path::remote_cid]

### ISSUE THREAD

**Issue by KershawChang** [mozilla/neqo#1566]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1874582
Apparently, `remote_cid` can be `None` when sending a `ClosingFrame`, but it's not clear why the `remote_cid` is not set.

**Comment by larseggert** [comment]
@valenting Would it be sufficient to not crash and instead terminate the connection? Or is an actual fix needed?

**Comment by valenting** [comment]
That's definitely better than crashing.

**Comment by larseggert** [comment]
@KershawChang says oin https://bugzilla.mozilla.org/show_bug.cgi?id=1874582#c4 this will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1882863, i.e., https://github.com/mozilla/neqo/issues/1697. So we may be done here?

**Comment by KershawChang** [comment]
> @KershawChang says in https://bugzilla.mozilla.org/show_bug.cgi?id=1874582#c4 this will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1882863, i.e., #1697. So we may be done here?

Right! I think this is fixed.
