### ISSUE TITLE
Fairness and sendorder methods on HTTP/3 SendStream

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#1651]
@jesup added these, but clippy is very confident that the methods are not used:

```rust
    fn set_sendorder(&mut self, conn: &mut Connection, sendorder: Option<SendOrder>) -> Res<()>;
    fn set_fairness(&mut self, conn: &mut Connection, fairness: bool) -> Res<()>;
```

Can they be removed?  Or do we really not need these?

**Comment by mxinden** [comment]
`SendStream` is a private trait. None of the trait method implementations are called within `neqo-http3`. Thus I assume they can be removed (https://github.com/mozilla/neqo/pull/1668). Am I missing something?

**Comment by martinthomson** [comment]
> Am I missing something?

That's my question as well :)
