### ISSUE TITLE
`neqo-interop` still in use?

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#1670]
Is [`neqo-interop`](https://github.com/mozilla/neqo/tree/main/neqo-interop) still used anywhere?

If I understand correctly it has been used to test interoperability with other QUIC implementations. Though as far as I can tell, only `neqo-client` and `neqo-server` are used today for https://interop.seemann.io/.

https://github.com/mozilla/neqo/blob/5074583553e77fcacd609e70e4bcc454b9960c49/qns/Dockerfile#L33-L34

Does `neqo-interop` provide a feature outside of the QUIC interop realm, that `neqo-client` and/or `neqo-server` does not?

**Comment by martinthomson** [comment]
I think that with [interop.seemann.io](https://interop.seemann.io/) we might be able to drop it.
