### ISSUE TITLE
Consider GitHub Merge Queue feature

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#1673]
Recently the Neqo repository required pull requests to be up-to-date with `main` before merge. See https://github.com/mozilla/neqo/pull/1575#issuecomment-1906258743 on past discussion. With many concurrent pull requests, this now requires maintainers to merge `main` into a pull request multiple times before it can be merged. See e.g. https://github.com/mozilla/neqo/pull/1671 with 3 `main` merges before the actual pull request merge.

A solution to this problem is a merge queue, where automation shepherds a pull request in its final stage. I have had good experience with @mergify. Also GitHub recently released their own: https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

What are your thoughts? I can do the required `.github/workflow/*` updates, but a person with privileged access would need to first enable the feature.

**Comment by martinthomson** [comment]
We used to use mergify on this repository and it broke far too often.  If you would be willing to do the merge queue, then I'd be very happy to review that.

**Comment by larseggert** [comment]
I'd be happy to either give mergify another go or try the new  GitHub one.

**Comment by mxinden** [comment]
https://github.com/mozilla/neqo/pull/1674 does the required code changes in `.github/`. You would need to make the corresponding changes in the GitHub settings (see pull request for details).
