### ISSUE TITLE
Have the C bindings produce the correct type 

### ISSUE THREAD

**Issue by o0Ignition0o** [mozilla/neqo#168]
While preparing to use clippy::pedantic, we noticed the C bindings may sometimes not be configured to produce the correct type.

https://github.com/mozilla/neqo/pull/153#discussion_r313673051

Creating an issue here so it will be handled in a subsequent PR on our road to clippy::pedantic

**Comment by martinthomson** [comment]
In looking into this, I realized that this is an ABI-compatibility invariant that we can't change.  For instance, if we have an enum declared as:

```c
typedef enum {
  a,
  b,
  c,
} SimpleEnum;
```

Then the type of that has a certain size in C that Rust bindings can't arbitrarily change.  What needs to change is the C declaration.  The fun part is that NSS (the C library in question) has an ABI compatibility promise that prevents us from altering public type declarations in ways that might cause incompatibility with binaries built against older headers.  That leads me to conclude that this is unfixable.

We can use `try_into()`/`try_from()` or `as` depending on circumstance, but we will have to accept that some amount of casting is inevitable.
