### ISSUE TITLE
Is `env_logger` useful for release builds?

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1684]
We seem to spend around 8% of cycles in `neqo_common::log::init` (see `transfer.perf` in [this artifact](https://github.com/mozilla/neqo/actions/runs/8052648773/artifacts/1276017609)). That's quite a lot.

Is there even any use in having `env_logger` do something in a release build? Should we simply make the logging macros no-ops for release builds?

**Comment by KershawChang** [comment]
> We seem to spend around 8% of cycles in `neqo_common::log::init` (see `transfer.perf` in [this artifact](https://github.com/mozilla/neqo/actions/runs/8052648773/artifacts/1276017609)). That's quite a lot.
> 
> Is there even any use in having `env_logger` do something in a release build? Should we simply make the logging macros no-ops for release builds?

I think we still need it for release builds, since sometimes we still need to collect logs from users.
However, it should be possible to make it configurable via a gecko pref.

**Comment by larseggert** [comment]
Are we collecting `stdout` logs from users, or qlogs?

(A gecko pref doesn't really help, since the calls would then still need to be made.)

**Comment by mxinden** [comment]
My suspicion from the H3 call just now is wrong. `INIT_ONCE`, despite being defined within the `init` function, is not instantiated once per `init` function call. It is defined as a `static` and `Once::new` is `const`, thus being defined within `init` only concerns namespacing.

https://github.com/mozilla/neqo/blob/7f6fc8bdf60d026c87980c9fe6974166fc2455c5/neqo-common/src/log.rs#L53-L55

See also https://stackoverflow.com/questions/70230937/initialization-of-a-static-variable-in-the-scope-of-a-function-or-a-module.

Sorry for the noise.

**Comment by larseggert** [comment]
Thanks for checking! Really wonder where all the cycles go then...

**Comment by larseggert** [comment]
@KershawChang do we really need to ship the ability to capture `stdout` logs from Fx? The logging macros add up to quite a bit of overhead.

**Comment by KershawChang** [comment]
> Thanks for the background. Is `5` equivalent to `trace` here?
> 

Yes, it is. The mapping can be found [here](https://searchfox.org/mozilla-central/rev/202c48686136360a23b73a49b611a19e64f3e1b8/xpcom/rust/gecko_logger/src/lib.rs#123).

> I wonder if it would be possible to disable (= not compile in) the log statements for other components for release builds. Are we ever using something other than the `MOZ_LOG` stanza above?

I think it's absolutely possible. Historically, we haven't needed logs from other components beyond these. However, it's challenging to say that we won't ever require logs from other components in the future.

Is adding a check in each log function helpful?
I mean something like:
```
macro_rules! qerror {
  if LOG_ENABLED  {
    neqo_common::log::init();
    neqo_common::do_log!();
  } else {
    ::neqo_common::qnoop!();
  }
}
```

**Comment by larseggert** [comment]
Yes, if `LOG_ENABLED` can be statically evaluated at compile-time, so no code gets generated if it's false.

**Comment by larseggert** [comment]
Also, instead of relying on `std::sync::Once` to implicitly initialize, could we introduce an explicit `neqo_init` function that a user of the library has to explicitly call?

**Comment by martinthomson** [comment]
We effectively do already.  The trick there is that we want to only run the initialization once, and the initialization function could be called from multiple threads.  So we'd still need something like this.  However, we could remove it from the critical path.

**Comment by larseggert** [comment]
Closing, since the atomic was optimized out with #1751.
