### ISSUE TITLE
Rethink `CODEOWNERS`

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1685]
Now that we're using a merge queue, the auto-merge feature really depends on all branch protection conditions being met. For info, this is our current `CODEOWNERS` file:
```
*    @KershawChang @martinthomson @larseggert
/docker/	@martinthomson
/hooks/    @martinthomson
/neqo-crypto/    @martinthomson
/neqo-http3/    @KershawChang
/neqo-qpack/    @KershawChang
/qns/    @martinthomson
```
For PRs that hit branches where not everyone under `*` is an owner, this means we need reviews from more than a single person, which delays things.

Proposals:
1. Just remove all lines other than `*`
2. Or, make sure there are at least two owners listed for all lines other than `*`, to lower the hurdle.

CC @martinthomson @KershawChang

**Comment by martinthomson** [comment]
Happy to take the extra lines out.  We can all answer for everything.
