### ISSUE TITLE
qlog spends CPU time even when not enabled

### ISSUE THREAD

**Issue by jesup** [mozilla/neqo#1691]
In high-bandwidth transfers, qlog can use ~9% of CPU cycles used in socket thread.

"it looks like that with a disable qlog, even a release build will [execute until here](https://github.com/mozilla/neqo/blob/8fb0652d58cddf8d50bb4cb80af3320c15424484/neqo-common/src/qlog.rs#L95) before determining that there is no qlog and bubble back up the stack."

**Comment by jesup** [comment]
https://share.firefox.dev/3wyQP2u

**Comment by larseggert** [comment]
@jesup Could you share how you generated the perf data file for this flamegraph? Because it looks very different from what the bencher is generating during CI.

**Comment by larseggert** [comment]
I think this is fixed - @jesup, could you confirm?
