### ISSUE TITLE
Merge neqo-client and neqo-server

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#1696]
`neqo-client` and `neqo-server` have a lot of logic in common, yet each duplicates it.

A couple of examples

- A lot of command line arguments are shared between client and server:
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-client/src/main.rs#L123-L219
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-server/src/main.rs#L92-L151
- Each has (at least) one `process` implementation calling `client.process` and handling its return value.
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-client/src/main.rs#L860-L881
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-server/src/main.rs#L646-L665
- Each has a similar run loop.
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-client/src/main.rs#L819-L858
    - https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-server/src/main.rs#L686-L707
- ...

Before making any major changes to `neqo-client` and `neqo-server`, like e.g. https://github.com/mozilla/neqo/issues/1693, I thus suggest merging the two into one crate, and thereby deduplicating the shared logic.

Suggestion:
- Introduce `neqo-bin/` crate.
- Move `neqo-common/src/udp.rs` into `neqo-bin/src/udp.rs`.
- Consolidate shared logic between `neqo-client` and `neqo-server` in `neqo-bin/src/lib.rs` and submodules.
- Move `neqo-client/src/main.rs` into `neqo-bin/bin/client.rs` and `neqo-server/src/main.rs` into `neqo-bin/bin/server.rs`.

What do folks think? Why have they been split into two separate crates thus far?

**Comment by larseggert** [comment]
Done via #1724
