### ISSUE TITLE
Crash in [@ neqo_transport::path::Path::local_cid]

### ISSUE THREAD

**Issue by KershawChang** [mozilla/neqo#1697]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1882863.

The crash is at this [line](https://github.com/mozilla/neqo/blob/ad027cfe2901dc98b3dae20574349f52621c5622/neqo-transport/src/path.rs#L664).
It seems the reason is that `local_cid` is called before `make_permanent`, but I am not exactly sure how this could happen.

**Comment by larseggert** [comment]
We need to find better ways to create reproducers from these crash reports. (In general, not just for this one.) What can we do?

**Comment by larseggert** [comment]
Was fixed by #1698
