### ISSUE TITLE
client: work with privateoctopus server

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#17]
This currently fails:

```
RUST_LOG=trace ./target/debug/neqo-http3-client http://test.privateoctopus.com:4433/ --db ./neqo-crypto/db
```

but client is still waiting for something instead of exiting. The ConnectionClose should be exposed in some (both?) event APIs so the client code can see it and do the right thing?

**Comment by martinthomson** [comment]
Why does this work with `http://` and not `https://` ?  Just curious.

**Comment by agrover** [comment]
Not sure of the current status of this, we should retry and see if it works and if it doesn't then investigate.

**Comment by agrover** [comment]
current cmdline:
```
RUST_LOG=trace ./target/debug/neqo-client http://test.privateoctopus.com:4433/222 --db ./test-fixture/db
```

**Comment by agrover** [comment]
> Why does this work with http:// and not https:// ? Just curious.

https works for me too.
