### ISSUE TITLE
Tweak interop runner CI output

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1716]
Is there a way to make the output from the interop runner more intuitively meaningful?
* Is it possible to highlight tests where the test result is not the expected test result? (Or at least where the test result was not a success, since I guess that is what we would expect.)
* I think we only really need the table. The lines before it are noise.
* The table (almost) looks like Markdown already. Can we make it proper Markdown and then render it as such (instead of raw text)?
* Can we rename the bot to something other than "github-actions" and give it a non-generic icon? (Maybe just the neqo logo?)
<img width="850" alt="Screenshot 2024-03-07 at 08 30 57" src="https://github.com/mozilla/neqo/assets/200328/77626d2e-d4f7-4415-bc6d-d66cbbf907f6">
CC @mxinden

**Comment by mxinden** [comment]
Despite the fact that I introduced the comment in the first place, I actually suggest removing it entirely :slightly_smiling_face: 

1. For boolean (success / failure) CI workflows I think the single line result at the bottom of a pull request is good enough.
    
    ![image](https://github.com/mozilla/neqo/assets/7047859/e958a372-d785-418f-b5ff-80a8ec16fe09)
2. For metrics based (e.g. code coverage of 90%) CI workflows I think a Pull Request comment makes sense.

In my eyes, the Interop CI workflow is part of (1), i.e. it either succeeds or fails. Having to look at the above table for each pull request isn't efficient but instead error prone given its manual nature. For now we can keep the workflow as non-required. Once we have a way to pin implementation versions (e.g. the concrete quic-go docker image) for reproducible test runs, we can make it required.

Detailed logs would still be uploaded as artifacts and are available on the _Summary_ page of the _quic-network-simulator_ workflow for debugging.

![image](https://github.com/mozilla/neqo/assets/7047859/02c9a55d-5d1a-4308-a91a-d1bb0ce15eab)

Objections @larseggert?

**Comment by larseggert** [comment]
For a succeeding test, I think the brief summary under (1) is fine.

For a failing one, I think showing the table is nice, because it lets one spot the failure easily.

(Also, can the comment be updated rather than a new one added on updates? https://github.com/mozilla/neqo/pull/1712)

**Comment by larseggert** [comment]
We definitely need to update the comment rather than adding new ones on each push, the current behavior is much too noisy.

**Comment by martinthomson** [comment]
I have used the pull request summary before, with some success: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary  Then you will get report details if you click through to the workflow run.

**Comment by larseggert** [comment]
@mxinden for the Markdown table, see https://github.com/quic-interop/quic-interop-runner/pull/372
