### ISSUE TITLE
SendStreamWritable is not really useful

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#175]
I would say SendStreamWritable is wrong. It does not take the flow control into account, so neqo-transport will post SendStreamWritable if there is more space in buffer even if the flow control does not allow to send more data.

**Comment by ddragana** [comment]
This is a bit complicated because connection flow-control is involved as well and then it is not easy to decide when to post SendStreamWritable events.

**Comment by agrover** [comment]
Can we say it's worth the app trying to write to the stream when it gets this event but doesn't ensure the write will succeed? I agree that we can't guarantee it will accept data. Maybe we posted this event for a few streams, and the first one used up all the conn flow credits.

**Comment by ddragana** [comment]
We should check available credit and buffer before sending event and we may trigger event when buffer get empty, stream limit changes or connection limit changes.

We should also have an event when connection flow control gets more credit, although in am not sure about this one. We also need to know when we hit it....
Lets fix the first one and the second can be done later.
