### ISSUE TITLE
"A hard maximum to keep plenty of space for other stuff"?

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1815]
https://github.com/mozilla/neqo/blob/c0ca26d6fd4ff85b7c0609da6ed84623137b1a92/neqo-transport/src/tracking.rs#L575-L586
Why do we "apply a hard maximum to keep plenty of space for other stuff"? If we need to ACK lots of things, we're likely not at the same time uploading lots, so we should have space. Needlessly limiting is likely suboptimal for the sender, because it will need to RTX things that were not lost but that we did not ACK.

**Comment by martinthomson** [comment]
32 ranges seems like it is a lot.  We only get to that number of ranges if the other side is not acknowledging.

With high BDP - and lots of loss or reordering - it's possible that we'd reach this point before the peer has a chance to acknowledge our ACKs.  But in that case we are send an ACK when we see any gaps, so we would have sent 31 previous ACKs in this RTT.  Those earlier ACKs will include the ranges we don't include in this ACK.

On the other hand, if this is a two-way flow (not all flows are badly asymmetric), limiting the space we spend on ACK seems like a win.  Is there are concrete problem with this that you have observed?

**Comment by larseggert** [comment]
Nope. Just wondering why this was put in. (As a TCP person, not being as complete/explicit as possible with ACKs just feels wrong.)
