### ISSUE TITLE
Mark `amplificationlimit` QNS test as unsupported

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1849]
So the QNS results aren't full of failures. Until we fix #1183.

**Comment by martinthomson** [comment]
...for our server, that is.

**Comment by mxinden** [comment]
I am afraid we can not "mark" the test as unsupported, i.e. `exit(127)`. Both client and server do not know the concrete testcase, but instead are told by the Interop Runner that they should execute a `transfer`. See `def testname` below.

https://github.com/quic-interop/quic-interop-runner/blob/e15a1e523d915bed008cfc6359f79e1a1458ba6f/testcases.py#L735-L742

An alternative solution would be some heuristic in `neqo-client` and `neqo-server`, though at this point, I assume https://github.com/mozilla/neqo/issues/1183 is the easier solution.
