### ISSUE TITLE
Use `indexmap` 2.* instead of 1.*

### ISSUE THREAD

**Issue by ErichDonGubler** [mozilla/neqo#1858]
It's actually possible to upgrade to `indexmap` 2.\* transparently for this project. 1.9.3 is source-compatible, `mozilla-central` uses the SemVer trick to persuade 2.\*-dependent crates to use 1.9.3 for now, and otherwise, the only obstacle to dropping 1.\* is formally migrating over. 🙂

There are also a mounting number of minor dependencies (like `hashbrown`) that are blocked on an upgrade like this in `mozilla-central`.

**Comment by larseggert** [comment]
Thanks for the background and the PR! I wasn't clear what the motivation for the SemVer trickery for Fx was and wanted to be on the safe side.
