### ISSUE TITLE
Client spews "Setting timeout of" messages

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1864]
Running the `test/test.sh` script generates a ton of messages like
```
0s356ms DEBUG [Client e4cf3ef0326dc9b16338] pn=9 type=Short pri-path:1bf8e83784f7e3129ce7 0.0.0.0:53440->127.0.0.1:4433 IpTos(Cs0, NotEct)
  TX -> ConnectionClose { error_code: Application(0), frame_type: 0, reason_phrase: [107, 116, 104, 120, 98, 121, 101, 33] }
0s357ms DEBUG [LossRecovery] packet ap-9 sent
0s357ms DEBUG Setting timeout of 141.61858ms
0s357ms DEBUG Setting timeout of 141.612121ms
0s357ms DEBUG Setting timeout of 141.607246ms
0s357ms DEBUG Setting timeout of 141.602788ms
0s357ms DEBUG Setting timeout of 141.598496ms
0s357ms DEBUG Setting timeout of 141.594246ms
0s357ms DEBUG Setting timeout of 141.590163ms
0s357ms DEBUG Setting timeout of 141.58608ms
0s357ms DEBUG Setting timeout of 141.581955ms
0s357ms DEBUG Setting timeout of 141.577871ms
```
after the client closes the connection.

Anyone got any idea where those come from? Maybe @mxinden?
[client.log](https://github.com/mozilla/neqo/files/15166658/client.log)

**Comment by mxinden** [comment]
Both the client and the server log when setting a timeout (aka. callback):

https://github.com/mozilla/neqo/blob/dcc88e323edfb5d2c4ad483bca0a93b89c5f22c2/neqo-bin/src/client/mod.rs#L418-L422

https://github.com/mozilla/neqo/blob/dcc88e323edfb5d2c4ad483bca0a93b89c5f22c2/neqo-bin/src/server/mod.rs#L516-L520

I am not sure why the client continuously sets the same timeout. I would expect the timeout to be continuously increasing until eventually the connection attempt times out.

I can take a deeper look in the next couple of days.

**Comment by martinthomson** [comment]
This is probably the PTO time for the request.  We should just bump that message down to TRACE.  If it is as commonplace as it is, then we don't need to see it in logs.

**Comment by larseggert** [comment]
But why would the client busy-wait like this? There are thousands of these in the log.

**Comment by martinthomson** [comment]
Is there some way in which the tokio select would exit early?  The expected outcome is that the client should indicate it wants to wait for a PTO.  The next thing should either be a new datagram arriving or the PTO expiring.

**Comment by martinthomson** [comment]
Ahh, I think that I can see what is happening.  We're setting `self.timeout`, but we don't bother to tell the socket about it.  The `recv` call therefore just polls without delay.

I think that the fix here is to have `process_multiple_input` exit once the timeout becomes `Some`.  Otherwise, yes, the loop is a busy one.

**Comment by mxinden** [comment]
The problematic instruction is this `continue`, continuously closing a closing connection:

https://github.com/mozilla/neqo/blob/14cafbaa7fa88434def2c1d19e932c08e00173f8/neqo-bin/src/client/mod.rs#L388-L391

https://github.com/mozilla/neqo/pull/1866 fixes the issue.

Regression introduced in https://github.com/mozilla/neqo/pull/1837. Sorry about that. Thank you for raising it.
