### ISSUE TITLE
Discuss addition of Glean probes to neqo

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1970]
@mxinden has a [patch](https://phabricator.services.mozilla.com/D216034) that adds Glean probes to the `neqo_glue` code in Firefox.

I guess we could use a similar approach to add Glean probes to other parts of neqo. We should discuss which ones we might want.

**Comment by larseggert** [comment]
@mxinden can be closed?

**Comment by mxinden** [comment]
I am fine closing here.

First metrics are landing with https://phabricator.services.mozilla.com/D216034.

Once we can no longer instrument from the outside of Neqo, we can revisit here.
