### ISSUE TITLE
Is macOS supposed to be supported?

### ISSUE THREAD

**Issue by onpaws** [mozilla/neqo#208]
Sorry if this is the wrong venue for this question, please feel free to edit as appropriate.

I'm on an up to date Mac and trying to build neqo, but it looks like someting about neqo-crypto isn't playing nice. 
1. Installed Rust using [Homebrew](https://brew.sh/).
2. git clone git@github.com:mozilla/neqo.git
3. cargo build, which returns:
```
$ cargo build
   Compiling neqo-crypto v0.1.1 (/Users/paws/projects/neqo/neqo-crypto)
error: failed to run custom build command for `neqo-crypto v0.1.1 (/Users/paws/projects/neqo/neqo-crypto)`

Caused by:
  process didn't exit successfully: `/Users/paws/projects/neqo/target/debug/build/neqo-crypto-b8a6aa57833561da/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=NSS_DIR

--- stderr
thread 'main' panicked at 'can't clone nss: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I see [this](https://github.com/mozilla/neqo/issues/83) issue seems similar regarding the symptom, but I believe appears to be different root cause.

I'm pretty new to Rust and HTTP/3 and was hoping to "learn by doing" on this.
I see there's a `Dockerfile` and I suppose building with Docker may work. However if possible would prefer to compile on my Mac to avoid the cross environment hopping, so to speak.

Any hints would be appreciated. Thank you! :)

```
$ rustc -V
rustc 1.37.0

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by martinthomson** [comment]
The important message is "can't clone nss".  NSS is hosted in a mercurial repository.  Once you install mercurial (`pip install --user mercurial` should work), then you will need to deal with all the issues described in #83.

**Comment by jasikpark** [comment]
https://github.com/mogemimi/pomdog/wiki/How-to-Install-GYP

is this helpful?

**Comment by onpaws** [comment]
Thanks @jasikpark -- yes, it was! 
After running `python3 setup.py install`, `cargo buid` _seems_ to have succeeded.
Now, I'm looking at a new one. The command is from README.md
```
$ ./target/debug/neqo-server 12345 -k key --db ./test-fixture/db
dyld: Library not loaded: @executable_path/libplds4.dylib
  Referenced from: /Users/paws/projects/neqo/./target/debug/neqo-server
  Reason: image not found
Abort trap: 6

```

**Comment by onpaws** [comment]
Looking into it a bit more it seems like I need to install `nss`, which I just did using homebrew, and things seem to be working OK now. Thanks guys for the pointers 🥂 

Future macOS users will probably find this works for them:
```
brew install python3 rust nss
git clone https://chromium.googlesource.com/external/gyp
cd gyp
python3 setup.py install
cd ..
git clone git@github.com:mozilla/neqo.git 
cd neqo
cargo build
```
...and then invoke the server/client per the README.

**Comment by martinthomson** [comment]
So yeah, running the server directly doesn't work because the alternative (`cargo run`) sets DYLD_LIBRARY_PATH appropriately.  There's a hack where you can rewrite the binary so that it references the shared libraries, but I haven't worked that out.  Nice work finding the workaround.
