### ISSUE TITLE
ci: macos failing with bindings/nspr_io.h:7:10: fatal error: 'prio.h' file not found

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#2141]
CI on MacOS is currently failing with:

> bindings/nspr_io.h:7:10: fatal error: 'prio.h' file not found

See e.g. https://github.com/mozilla/neqo/actions/runs/11112117096/job/30873528067?pr=2136.

I am looking into it now.

Happening on e.g. #2136, https://github.com/mozilla/neqo/pull/2093

**Comment by mxinden** [comment]
Maybe related to the fact that we are now using the homebrew NSS version?

Previously (succeeding):

> System NSS is too old: 3.104

https://github.com/mozilla/neqo/actions/runs/11029596600/job/30632387433

Now (failing):

> System NSS is suitable: 3.105

https://github.com/mozilla/neqo/actions/runs/11112117096/job/30873528067?pr=2136

**Comment by mxinden** [comment]
Unable to reproduce on an ARM Mac locally thus far.

**Comment by larseggert** [comment]
This is an NSPR header.

**Comment by mxinden** [comment]
As far as I can tell, this is what is happening:

1. On MacOS we install NSS via brew. NSPR is installed as a dependency of NSS.
2. We check the NSS version. Recently the brew version updated to 3.105, and is now considered valid.
3. We would skip all the local build steps given that `BUILD_NSS` would be `0`.
4. We would still set `NSS_DIR` to a local NSS installation. Note that `NSS_DIR` indirectly also determines the NSPR installation location.
5. Building `neqo-crypto` would fail, given that `NSS_DIR` would (indirectly) point to a non-existing local NSPR installation and thus imports like the one below wouldn't resolve.
  https://github.com/mozilla/neqo/blob/55e3a9363c28632dfb29ce91c7712cab1f6a58da/neqo-crypto/bindings/nspr_io.h#L7

https://github.com/mozilla/neqo/pull/2142 fixes the problem.

**Comment by larseggert** [comment]
I think we need a new env variable to indicate that a pkf-config NSS should be used.
