### ISSUE TITLE
transport: handle connection close better

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#22]
We're currently transitioning state and sending an event but we should also probably be cleaning up streams, and maybe sending events that they have been closed/reset as well? Refer to the spec for desired behavior.

**Comment by agrover** [comment]
Current code now clears all send & recv streams and disallows creation of new ones. 

I'm leaning against sending separate connection events for these, instead of that just being implicit in the connectionclose event

**Comment by martinthomson** [comment]
That seems reasonable.  Closing should be hard, so streams will all be "reset" and no more can be opened.

**Comment by agrover** [comment]
Not sure what further needs to be done here. We should open more specific bugs if issues remain.
