### ISSUE TITLE
test: use provided (simulated) time in qlogs

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#2211]
When logging qlog events, we currently use `qlog`'s [`add_event_data_now`](https://docs.rs/qlog/0.13.0/qlog/streamer/struct.QlogStreamer.html#method.add_event_data_now) which internally calls `std::time::Instant::now()`.

https://github.com/mozilla/neqo/blob/e08c14f5b26dfb9190caedf793ce59acf9634773/neqo-common/src/qlog.rs#L117

This is fine when capturing qlogs in real-time.

Problem arises when used with the [`text_fixtures::Simulator`](https://github.com/mozilla/neqo/blob/main/test-fixture/src/sim/mod.rs), which simulates time, i.e. where `std::time::Instant::now()` has no meaning.

I suggest we use `qlog`s [`add_event_data_with_instant`](https://docs.rs/qlog/0.13.0/qlog/streamer/struct.QlogStreamer.html#method.add_event_data_with_instant), using `now: Instant` available e.g. through `now` parameter on `Connection::process`.

https://github.com/mozilla/neqo/blob/e08c14f5b26dfb9190caedf793ce59acf9634773/neqo-transport/src/connection/mod.rs#L1165

Status: preparing a draft. Thus far, this is very noisy, given that `now` needs to be passed across many layers.

**Comment by larseggert** [comment]
Sound good.

Related, it would be nice to see virtual time in the debug output for tests, and not clock time.

**Comment by mxinden** [comment]
I sketched a fix for this issue in https://github.com/mozilla/neqo/pull/2212. Long story short, I don't think it is worth it. See PR description in https://github.com/mozilla/neqo/pull/2212. 

Let me know if you think otherwise, or have a better solution.
