### ISSUE TITLE
Optimize `SentPackets::take_ranges`

### ISSUE THREAD

**Issue by mxinden** [mozilla/neqo#2242]
When CPU profiling a `test_fixtures::Simulator` run transferring 10 MiB from a server to a client, I see the following flamegraph:

 
![flamegraph2](https://github.com/user-attachments/assets/940a7bf3-9ddd-4318-bfe1-92a9f0b417d9)

The majority of CPU time is spent in `SentPackets::take_ranges`:

https://github.com/mozilla/neqo/blob/f3d01912b9a2d5962fffae1a192a3f62e738f745/neqo-transport/src/recovery/sent.rs#L189-L213

More specifically in the two calls to `BTreeMap::extend`:

https://github.com/mozilla/neqo/blob/f3d01912b9a2d5962fffae1a192a3f62e738f745/neqo-transport/src/recovery/sent.rs#L200-L211

Adding some logging, the following seems to be the case:

- Assume we have two nodes, A and B, where A sends 10 MiB to B.
- A has 100 packets in flight.
- A receives an ACK from B, acknowledging the first 2 packets.
- At the end of the first loop iteration:
  - `packets.len()` will be `0`, given the ACK from B acknowledges the first 2 packets.
  - `acked.len()` will be `2`, containing the two new acked `SentPacket`s.
  - `keep.len()` will be `98`, containing all remaining packets
- We then execute `self.packets.extend(keep)`, e.g. in the above scenario, adding all remaining 98 packets to the now empty `self.packets`.
- In other words, we re-insert all remaining packets on each ACK.

Unfortunately `BTreeMap` does not allow splitting out a full range. The closest to that is [`BTreeMap::extract_if`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.extract_if) which is currently Nightly only.

That said, I think the following change, optimizing for the scenario above, would get us a long way already:

``` diff
modified   neqo-transport/src/recovery/sent.rs
@@ -197,18 +197,17 @@ impl SentPackets {
     {
         let mut result = Vec::new();
         // Remove all packets. We will add them back as we don't need them.
-        let mut packets = std::mem::take(&mut self.packets);
         for range in acked_ranges {
-            // For each acked range, split off the acknowledged part,
-            // then split off the part that hasn't been acknowledged.
-            // This order works better when processing ranges that
-            // have already been processed, which is common.
-            let mut acked = packets.split_off(range.start());
-            let keep = acked.split_off(&(*range.end() + 1));
-            self.packets.extend(keep);
+            let mut packets = std::mem::take(&mut self.packets);
+
+            let mut keep = packets.split_off(&(*range.end()));
+            let acked = packets.split_off(range.start());
+
+            keep.extend(packets);
+            self.packets = keep;
+
             result.extend(acked.into_values().rev());
         }
-        self.packets.extend(packets);
         result
     }
 ```

CPU profiling once more, this resolves the hot-spot on `SentPackets::take_ranges`:

![flamegraph](https://github.com/user-attachments/assets/7edf230d-f645-468e-a74f-1e8e4ae18e10)

Let me know if I am missing something? E.g. the above scenario not being something worth optimizing for.

See also past discussion: https://github.com/mozilla/neqo/pull/1886/files#r1591830138

**Comment by larseggert** [comment]
I think this makes sense. Might want to add a bench for it first, to get a performance baseline for a number of different ACK patterns, before doing a fix PR?
