### ISSUE TITLE
refactor Connection

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#23]
* Break out self-contained things into their own files
  * streamId/StreamIdx structs
  * FlowMgr
  * Events
  * Generators
* get StreamIndexes out of struct Connection

@martinthomson any more?

**Comment by ddragana** [comment]
lost-recovery?

**Comment by agrover** [comment]
FlowMgr does things that are not flow-control related.

**Comment by martinthomson** [comment]
packet encoding has a ton of unnecessary copying, it uses detached public functions rather than methods attached to the type
