### ISSUE TITLE
Reading multiple tls records

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#233]
The issue occur when I was testing cloudflare-quic.com.
The first 2 packets from server are reordered. Therefore after the second packet is received neqo-crypto gets data from both packets to read at once.

So nss consumes the encrypted extensions but never proceeds to read certificate, although we have a compete certificate.
I was looking a bit, but I do not understand how this should work. @martinthomson can you give me a short explanation I would really like to understand how this suppose to work.
Calling SSL_RecordLayerData we supply data to nss. Should nss take all data or just a single tls record? Reading comments it should take all data.
I think the problem is that SSL_ForceHandshake does not handle properly data that are written using SSL_RecordLayerData. ? SSL_ForceHandshake does nothing. I notice that SSL_RecordLayerData also handles data(i.e. consumes records) and that is why this works in normal case. In the cloudflare case we should drive handshake once more after the encrypted extensions, but we do not do it and we hang.

**Comment by martinthomson** [comment]
Do you have traces?  Or are you able to produce a test case that shows this problem?  Is it enough to have a two-packet server flight and to reorder the two packets?

`SSL_RecordLayerData` requires that the data be provided in order.  Are we providing the data in the right order?

**Comment by ddragana** [comment]
a log has been sent.

**Comment by martinthomson** [comment]
I just looked at the log and while we get 1363 bytes in, the Certificate message reports a length that is far longer than that (5k-ish).  Seems like a server issue.
