### ISSUE TITLE
implement standard "qlog" logging format

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#246]
https://tools.ietf.org/id/draft-marx-qlog-event-definitions-quic-h3-00.html

**Comment by Shivansh2407** [comment]
Can I work on this issue? please explain also what to do?

**Comment by agrover** [comment]
see https://github.com/quiclog/internet-drafts and https://qvis.edm.uhasselt.be/ .

Basically the work here involves understanding the format and then coming up with a scheme so the main Neqo code can have hooks added so that if logging is enabled then the log is generated in the correct format. This is a very kind of "figure it out" kind of task, that should have a distinct separate module to work in (the logging and its format) as well as be an introduction to the QUIC protocol, and also a way to become familiar with Neqo (locating the proper spots to call qlog code from the protocol-specific code).

I'd also recommend joining the QUIC Slack as mentioned on https://quicwg.org/ and joining the #neqo and #qlog channels.

**Comment by agrover** [comment]
https://docs.rs/qlog/0.1.0/qlog/

https://quiclog.github.io/internet-drafts/draft-marx-qlog-event-definitions-quic-h3.html

see also #387
