### ISSUE TITLE
Http3Connection::new() should not take a Connection as param

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#25]
Maybe just make one internally?

**Comment by martinthomson** [comment]
[Dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) ?

**Comment by agrover** [comment]
This is connected to #26, and basically is solved by it. If there are separate server and client new methods then these can create underlying connection with the proper role internally.

**Comment by ddragana** [comment]
This one is fix by #234
