### ISSUE TITLE
Discard initial and handshake keys

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#274]
We should be discarding initial and handshake keys at some point.

We also should remove unacked initial and handshake packets from bytes in flight, as mentioned in recovery 5.3.

**Comment by martinthomson** [comment]
We probably want to avoid expensive iterations over dead information when we go to send packets.  That might be worth building in to this.

**Comment by agrover** [comment]
If we just set the cryptostates for initial and handshake back to `None` after we're connected, then I think `obtain_crypto_state()` will just try to re-read them from TLS? Is that so, @martinthomson? If so do you have a solution in mind or should I take a stab?

**Comment by ddragana** [comment]
When I was fixing #296, my first solution was:
https://github.com/mozilla/neqo/commit/c85b0b606da4836d5505ed968e6ea46e6490a92e
you may want to take that approach.

(the 0-rtt keys are done a bit differently now)
or mt has something else in mind.
