### ISSUE TITLE
Support multiple wire-compatible draft versions

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#275]
It would be helpful if Neqo could claim support for multiple draft versions that are wire-compatible. This would help ease the transitions between our work for a new draft version, and still allow connections to hosts that have different schedules for updating to the latest version.

**Comment by martinthomson** [comment]
How would we switch between them?  We don't have compatible version upgrade, so - as a client - we have to pick a version to stick with.

**Comment by ddragana** [comment]
> How would we switch between them? We don't have compatible version upgrade, so - as a client - we have to pick a version to stick with.

We will pick one that is in altt-svc header.

**Comment by ddragana** [comment]
I think this is already fix?

**Comment by martinthomson** [comment]
Yes.  Andy did this.
