### ISSUE TITLE
crypto: Should we use Pin<Box<>> instead of just Box<>?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#282]
@martinthomson  see https://github.com/cloudflare/quiche/pull/249 maybe we want to do something similar? I know some of the Box-ing of things in neqo-crypto was to get references that are immovable and can be shared with C code, but maybe this is better? 

Low priority, if-you-are-bored kinda thing I'd say...

**Comment by martinthomson** [comment]
`Pin<>` is probably worth looking into for some of our uses.  But most of the code only assumes that C won't move stuff while we call into it.  That is, when neqo-crypto calls into NSS, we care that the memory doesn't move, but it could happily move between calls (for the most part).

Given that calling into C won't move rust objects, we only need to care about pointers that we hand out once.  I don't think that we have many (or even any) of those, but it's worth checking.

Let's use this issue to audit the code to determine which uses need the extra confidence.

**Comment by martinthomson** [comment]
Just double-checked, we can pin and - if we implement `Unpin` - unpin as we need to.  We should just do that.
