### ISSUE TITLE
assertion failed: encoder.len() <= self.pmtu()

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#285]
This may be already fixed.
This is reported in bugzilla bug [1595337](https://bugzilla.mozilla.org/show_bug.cgi?id=1595337)

**Comment by ddragana** [comment]
We should update neqo in mozilla central soon, maybe after #280 as been fixed.

**Comment by martinthomson** [comment]
I think that #280 is going to take at least a few days.  Depends on how much you want to iterate on this.

**Comment by ddragana** [comment]
@agrover can we remove this assertion until #280 is fixed?
Is it worth trying to get some logs from the reporter or #280 will fix it for sure?

**Comment by agrover** [comment]
@ddragana yeah let's just remove that assertion for now. #280 will re-add it and also fix things so it does not fail, but 280 is going to need some work before it lands so let's not wait.

I've opened PR #287, for a quick ack and merge.
