### ISSUE TITLE
Cannot publicly create a `neqo_transport::Connection::TransportParameter`

### ISSUE THREAD

**Issue by hawkinsw** [mozilla/neqo#316]
Right now, `neqo_transport::Connection::set_local_tparam` is public but cannot actually be used because there is no way to publicly create a `neqo_transport::Connection::TransportParameter`. Refactor to correct for this.

This seems like an oversight. Please let me know if I am misunderstanding. Just trying to help! 

PR to follow.

**Comment by agrover** [comment]
@hawkinsw I think you fixed this, closing. Plz reopen if I'm mistaken.
