### ISSUE TITLE
thread 'main' panicked at 'assertion failed: delta < self.items.len()', neqo-common/src/timer.rs:85:9

### ISSUE THREAD

**Issue by hawkinsw** [mozilla/neqo#319]
To repro, 

`RUST_BACKTRACE=1 cargo run --bin neqo-http3-server -- -d test-fixture/db/`

and wait longer than the duration of the server's underlying timer wheel (3 minutes will do). Then, 

`cargo run --bin neqo-client https://localhost:4433`

There are other ways to trigger this, but this is the easiest. I have found the reason we have this problem, and would like to get your advice on the solution. 

It happens in the scenario where:
1. The server's timer wheel is not getting tick'd because there are no connections to service for the entirety of the timer wheel's span, and
2. a newly-accepted client connection, `a`, is `process()`'d resulting in a callback. 

At that point, the server will attempt to remove the timer at `a.last_time` (which matches the time the connection was accepted). Unfortunately, the assertion is triggered because that is outside the span of the timer wheel. 

The solution seems to be rather simple:
gate the logic in `Timer::remove(t)` so that it immediately returns `None` if `t` is somewhere in the future beyond `Timer::now + Timer::span()`. That seems reasonable since there is no way that `t` could somehow be in the timer wheel. 

I have a patch that uses that logic and I will put in a PR. I tested with `cargo test` and everything passes. If that's bad logic, please feel free to tell me so. I'm glad to work with you on a fix that follows best practices, etc. 

As ever, thanks!
Will

**Comment by agrover** [comment]
fixed by #320
