### ISSUE TITLE
Send blocked signal when qpack is blocked

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#32]
In addition to the interface in #31, we should add a means of forcing the transport to send an appropriate blocked frame.

**Comment by martinthomson** [comment]
Maybe this isn't the right approach.  If a sending stream was aware of flow control limits (which they are not currently). then it could block entire writes and trigger a STREAM_BLOCKED frame if they exceeded the available space.  Then QPACK could just attempt to make atomic writes for each insertion or duplication.

**Comment by agrover** [comment]
@martinthomson is this still valid now that Connection has an API to get send stream flow control limits? Thanks.

**Comment by martinthomson** [comment]
Yes. What we should be doing is building table insert instructions, checking if there is enough flow control credit to send them, and either sending them, or sending a blocked signal. That won't happen with the current API because we won't try to send an instruction that only partially fits.

**Comment by agrover** [comment]
Would an all-or-none send API be helpful here?

**Comment by martinthomson** [comment]
I thought about that; it depends on how often we think that this sort of all-or-none arrangement is truly necessary.  If it is a common pattern, then we should have an all-or-none send function rather than a query flow control function.  If it is rare (I'm only aware of this one instance), then we might get by with the query interface.

**Comment by agrover** [comment]
So we either need a send-all-or-none method (implicitly sends StreamDataBlocked if none), or else a way for the application to signal it is blocked (and send a StreamDataBlocked), even though the transport still thinks it is not yet blocked?

Or would it be more natural to change qpack to try to send partial instructions?

cc @ddragana

**Comment by ddragana** [comment]
> So we either need a send-all-or-none method (implicitly sends StreamDataBlocked if none), or else a way for the application to signal it is blocked (and send a StreamDataBlocked), even though the transport still thinks it is not yet blocked?
> 
> Or would it be more natural to change qpack to try to send partial instructions?
> 

we should not send partial instruction. It is unknown if an instruction will be useful at the point in time when the stream gets unblocked.

(qpack algorithm will need some thinking, current one is a very very simple one and it needs optimization. I will open a issue for that)

> cc @ddragana

**Comment by agrover** [comment]
We now have `stream_credit_avail_send()` so h3 just needs to starting using it?

**Comment by ddragana** [comment]
Update: qpack can send partial instructions now. If it gets block it will still work. 
 I will suggest to do some measurement how often this is happening and do something if needed.

**Comment by martinthomson** [comment]
When you say partial instructions, I hope that doesn't apply to the encoder stream.  Because a partial instruction there could lead to a deadlock.

**Comment by ddragana** [comment]
> When you say partial instructions, I hope that doesn't apply to the encoder stream. Because a partial instruction there could lead to a deadlock.

you are write and i should not look at issues that late (I am not really productive at 1:30AM)

**Comment by ddragana** [comment]
Fixed by #616
