### ISSUE TITLE
Maybe refacrot  0rtt

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#340]
Issue #296 fixes a problem with 0rtt, but maybe we should do it in a better way.
My thoughts:
- we should mode 0rtt keys into neqo_transport::crypto, that will make some code in connection.rs nicer.
- thinking about this, output_pkt_for_path should probably iterate over encryption level not epoch or packet number space.
- As I remember Martin suggested that neqo_transport::crypto should have a list of crypto states per packet number space not epoch as it is now. How about using the encryption level and we could put 0rtt stat there as well?

**Comment by martinthomson** [comment]
I have implemented these recommendations in #397.
