### ISSUE TITLE
StreamId should be in the public interface

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#346]
Everywhere that we use `u64` for a stream ID, we should be using `StreamId`.  Then that type can be moved to the public interface.

**Comment by ddragana** [comment]
The reason why I use u64 and not streamId is because http3 code do not care of stream types, streamId is just a identifire. it just trust what neqo-transport gives it. 
Also I did not want to expose StreamId  structure to c++ code.

**Comment by agrover** [comment]
`StreamId` is basically helper methods on a u64. The value of exposing `StreamId` would be that clients could call these methods -- but if it's just used as an opaque token/identifier then the value is lost. I haven't looked but it sounds like that's how neqo_glue & Necko code treat stream id, so there wouldn't actually be a benefit, and actually might require some conversions in neqo_glue if this change is made.

That said, I'm still in favor of this change. Typing things is good. We just need to be aware that this may be nice on the Neqo side of things but actually adds a little work on the Gecko/Necko side of things to adapt to the change.

**Comment by mahakbansal2019** [comment]
Hello!!
I want to work on this so could you please tell more details about this ?
