### ISSUE TITLE
CC: Initial window may vary depending on PMTU

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#349]
Initial PMTU will be different based on ipv4 or v6, so initial window calculation should take this into account and not use 1200 as max datagram size.

**Comment by agrover** [comment]
see also https://github.com/mozilla/neqo/pull/348#discussion_r356390109

**Comment by martinthomson** [comment]
See also #422.

**Comment by agrover** [comment]
Actually, shouldn't matter all that much. low priority

**Comment by ddragana** [comment]
I will close this one. If we decide to reevaluate this we will open a separate issue.
