### ISSUE TITLE
output_pkt_for_path may not (or incorrectly) pad a packet

### ISSUE THREAD

**Issue by hawkinsw** [mozilla/neqo#380]
While working on #379, I came across this issue and I was hoping that I could get some feedback. 

Looking at the code, it seems like there is a possibility that neqo does not (properly?) pad a datagram that contains an Initial packet. I had a long discussion on slack with some other implementers and I think that I understand this correctly. Please, please tell me if I am wrong. And, if I am, I am sorry for wasting time!

There is code in `output_pkt_for_path` that sets a `needs_padding` flag when there will be an Initial packet in the output datagram. However, it unsets that flag as soon as it sees that a QUIC packet with a short header will be coalesced into the output datagram. The problem, I think, is that according to the spec, if a datagram contains an Initial packet, it must _always_ be at least as long as the initial path MTU.  

Assume that there is a datagram that contains an Initial packet and several packets with short headers and the size of the entire datagram is 1232 bytes. Unsetting the `needs_padding` flag in this case _*is not*_ a problem. 

Assume, however, that there is a datagram that contains an Initial packet and several packets with short headers and the size of the entire datagram is 800 bytes. Unsetting the `needs_padding` flag in this case *_is_* a problem. 

There are several simple solutions to this problem (and several solutions that seem simple but will not work). And, though I have implemented one, I was hoping that someone would be willing to first verify that this is actually a problem. 

I hope that my description makes sense and that this report is not a waste of time. If it is confusing and there is anything I can do to clarify, please let me know. If it is a waste of time or not an issue, please tell me that, too.

**Comment by martinthomson** [comment]
The problem here is that a short header can't be followed by padding in the way we define it.  So even if we should be padding (because there is an Initial packet), we can't.

But it pays to look more closely at the state machine.  There is just one case where it is possible to include a packet with a short header and an Initial in the same datagram.  That's at the server when it sends its first flight.  But the server doesn't need to pad Initial packets.

A client that sends a short header packet never has cause to send an Initial.  A client is required to drop Initial keys [when it starts sending Handshake packets](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#name-discarding-initial-keys).

**Comment by hawkinsw** [comment]
> The problem here is that a short header can't be followed by padding in the way we define it. So even if we should be padding (because there is an Initial packet), we can't.

Yes, it seems like we are on the same page with our understanding which makes me happy! Thank you! 


> 
> But it pays to look more closely at the state machine. There is just one case where it is possible to include a packet with a short header and an Initial in the same datagram. That's at the server when it sends its first flight. But the server doesn't need to pad Initial packets.


So then unsetting that flag is ok. Makes sense. A client would never reach this point because they will never have a crypto context at the 1-rtt level at the same time they are sending an Initial packet. That's an accurate statement, right? 

> A client that sends a short header packet never has cause to send an Initial. A client is required to drop Initial keys [when it starts sending Handshake packets](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#name-discarding-initial-keys).

That's what I was asking about on slack and couldn't quite convey but thought was the case! There's no coalescing that could happen. Thank you for confirming.

**Comment by martinthomson** [comment]
A lot of changes have been made here, including changing to add padding inside short packets.  I think we're OK now.
