### ISSUE TITLE
Multiple ping frames in the same packet

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#382]
If we need to send a ping because pto has expired and we do not have any other frames to send we will send a ping in each epoch.
A server will not ack packets(pings) for epoch 0 and 2 if we already have keys for epoch 3, therefore we will always have outstanding unacked packets even if a connection is idle.

**Comment by agrover** [comment]
@martinthomson wdyt?

And, if we fixed #274 would that improve or even fix this issue?

**Comment by ddragana** [comment]
> @martinthomson wdyt?
> 
> And, if we fixed #274 would that improve or even fix this issue?

yes, that would be a proper fix.
I can work on that fix, but I would like to land this hack so that we can turn http3 on on nigthly.
Although maybe #274 is not that hard to fix. I will look at it tomorrow.

**Comment by ddragana** [comment]
i forgo that pto now is per packet number space, so we will need a bit different approach here.

**Comment by ddragana** [comment]
issue #308
