### ISSUE TITLE
Limit ACK Ranges more

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#389]
We might want to track fewer ACK Ranges than 100.  It's highly unlikely that we will ever have a problem with the ACK frame size at this (all hundred ranges with 2^30 or more contiguous packets in each and 2^30 or more gaps between each range would produce a 1600+ byte ACK frame), but more to the point we just don't need to keep acknowledging packets that are so sparsely distributed.  I think we could drop this to 32 happily.

**Comment by Mika-net** [comment]
How would someone go about completing this task?

**Comment by martinthomson** [comment]
There is a number in the code that describes how many ranges we keep.  Reduce it.

**Comment by Mika-net** [comment]
Alright, I think I can take this task.

**Comment by undef1nd** [comment]
Folks, is it done? Can I take it?

**Comment by ddragana** [comment]
@Mika-net  are you still working on this?
