### ISSUE TITLE
Send better PTO packets

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#411]
This is from the code:  
              // TODO
                // if (has unacknowledged crypto data):
                //   RetransmitUnackedCryptoData()
                // else if (endpoint is client without 1-RTT keys):
                //   // Client sends an anti-deadlock packet: Initial is padded
                //   // to earn more anti-amplification credit,
                //   // a Handshake packet proves address ownership.
                //   if (has Handshake keys):
                //      SendOneHandshakePacket()
                //    else:
                //      SendOnePaddedInitialPacket()
                // TODO
                // SendOneOrTwoPackets()
                // PTO. Send new data if available, else retransmit old data.
                // If neither is available, send a single PING frame.

                // TODO(agrover): determine if new data is available and if so
                // send 2 packets worth
                // TODO(agrover): else determine if old data is available and if
                // so send 2 packets worth
                // TODO(agrover): else send a single PING frame

**Comment by martinthomson** [comment]
Dragana suggested that we mark the frames from a handful of packets "lost" when we fire a PTO.  Then, we should be able to send "new" data on PTO and dispense with the special PTO mode for frame building.  We shouldn't mark many packets lost, but we need enough that we will probably be sending old, lost data, but not so much that we risk some nasty thrashing that might arise from marking everything lost.

**Comment by ddragana** [comment]
Fixed by #448
