### ISSUE TITLE
Make better use of enums with associated data

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#415]
Starting with `State` and `Role` in transport, it might be nice to use enums with associated data to limit amount of raw `Option` fields when the option is only really there because a data field is only valid in a certain state or role.

One issue with this is that `State` and `Role` are part of the API, and we don't want to expose private associated data. I think we might want to instead have e.g. `PrivState` where we are free to use associated data, and then a data-less `State` that is trivially obtained from the `PrivState` that is safe to hand out.

Could we for example automatically drop keys and other per-pnspace data by making them State associated, which would be automatically dropped when transitioning to a different state?

To what degree is there Role associated data for Connection? Much server-role-related behavior and data is already in `Server`. The only client-specific-role item is RetryInfo, I think.

We'd want this to result in a greater resistance to bugs and simplify code flow -- would need to more than offset complexity added for Foo/PrivFoo scheme mentioned above.

**Comment by martinthomson** [comment]
we've done enough of this, I think
