### ISSUE TITLE
Establish common time base for tests using Once

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#42]
https://github.com/mozilla/neqo/pull/39#discussion_r292239695

> This changes the tests significantly. It exposes the tests to timing variance that the fixed value didn't. If we can fix the value here, that will help a lot.

> I like that this now uses now() instead of 0 in a lot of places, but I think that we want a constant function. In doing the 0-RTT code, I need a lot more control over the way that we manage timers and tying this to the system clock is unworkable.

> I know that it's hard to get a concrete Instant instance, but maybe we can use Once for picking that point in time.

**Comment by martinthomson** [comment]
I have something of a solution for this.  Once #39 lands, I can fix up the code in neqo-transport to pass `Instant` and `Duration` to neqo-crypto and we should be golden.

Preview at #45.  Pay particular attention to how this uses the provided `Instant` to prime the starting value.  That's a little janky, and I'm not completely sure that we need it if this initialization happens at the same time as us initializing neqo-crypto, but the inability to go back in time with `Instant` produced some interesting crashes in testing, where I'm doing a little bit of time-travel to allow 0-RTT to work.
