### ISSUE TITLE
accessor for latest_rtt

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#43]
https://github.com/mozilla/neqo/pull/39#discussion_r292242836

**Comment by o0Ignition0o** [comment]
I was about to add an accessor for rtt:

`
   fn rtt(&self) -> Duration {
        self.smoothed_rtt.unwrap_or(self.latest_rtt)
    }
`

But I'm a bit confused with the variable naming. Does the issue name mean we would like an rtt accessor, or just a latest_rtt member accessor ?

Would such a method be named rtt or latest_rtt ?

I feel like the latter would be more spec compliant, but a bit more confusing wrt the (private) member name.

FWIW, the [Persistent congestion](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#persistent-congestion) handling seem to only care about the smooth rtt, so I feel like an rtt accessor would do.

Thanks a lot for your time :)

**Comment by martinthomson** [comment]
We want the best estimate that we have for RTT.  As soon as we have a sample, then `self.smoothed_rtt` will have a value, but we need to use `self.latest_rtt` as a fallback for new network paths.

**Comment by o0Ignition0o** [comment]
I think we can now close the issue
