### ISSUE TITLE
Receiving a RETIRE_CONNECTION_ID should affect valid_cids

### ISSUE THREAD

**Issue by hawkinsw** [mozilla/neqo#447]
**Please read the second comment, too, before responding this. After writing the second comment, I realize that this first note is not 100% precise. However, I still believe that there is _an_ issue here -- I'm just not sure it is _this_ one.**

I have been reading the spec for connection id handling and correlating that with our implementation, and I think that I have found a discrepancy. I hope that it is a genuine issue and that I am not wasting your time by suggesting otherwise. Again, I am nervous to submit this, but here it goes ...

In a connection, neqo tracks:

1. `valid_cids`: According to the comment on that field and its usage in the code, these are cids that this endpoint is willing to _accept_ as an indicator of packets in this connection.
1. `connection_ids`: These appear to be cids that this endpoint can use to _send_ packets to the peer so that they are associated with this connection.

Neqo inserts cids into `connection_ids` when it receives a NEW_CONNECTION_ID frame. I believe that this is correct. A `NEW_CONNECTION_ID` frame tells us that the _peer_ is willing to accept packets with an additional connection id and correlate them with the current connection. 

However, https://github.com/mozilla/neqo/blob/8f69ff30da72f95b0785d2e4a2ff87738f781900/neqo-transport/src/connection.rs#L1646  _removes_ from `connection_ids` when it receives a `RETIRE_CONNECTION_ID` frame. I think that this should be manipulating `active_cids` and not `connection_ids` because:

> When an endpoint issues a connection ID, it MUST accept packets that carry this connection ID for the duration of the connection or until its peer invalidates the connection ID via a RETIRE_CONNECTION_ID frame (Section 19.16). Connection IDs that are issued and not retired are considered active; any active connection ID can be used.
(https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-5.1.1-3)

Consider endpoints **a** and **b**:

1. **a** knows the number of active connection ids that **b** is willing to track for this connection via the `active_connection_id_limit` TP.
1. If **b** can accept additional connection ids and **a** needs an additional connection id, **a** makes a new **C1**, adds it to its `valid_cids` and sends **C1** in a `NEW_CONNECTION_ID` frame to **b** indicating that it will accept **C1** as a connection id for this connection. 
1. **b** would process that frame by adding **C1** into its `connection_ids`
... **b** could send packets to **a** using any **CN** from its `connection_ids` ...
1. **b** could indicate that it no longer intends to use **C1** to address packets to **a** using a `RETIRE_CONNECTION_ID` frame. When **b** sends such a frame, **b** will remove **C1** from `connection_ids`. 
1. **a** receives the `RETIRE_CONNECTION_ID` frame which should cause a change to `valid_cids`

Am I reading the spec correctly? Am I reading the code correctly? This is an area of the spec and our code that I have not entirely comprehended, at least I don't think. Your feedback is really appreciated.

**Comment by hawkinsw** [comment]
As I look into the code more, it appears that neqo paths also keep track of their own cids and the connection validates against those when it is deciding how to correlate packets. If it's okay, I'd like to draft here my understanding of the different sets of connection ids that each connection needs to maintain. I think that will help me understand: (Note: The names in this description are intentionally different than the ones in neqo source code, unless otherwise specified)

1. `receive_active`: The connection id(s) that a receiving connection endpoint uses to determine whether to accept packets.
2. `send_active`: The connection id(s) that a sending connection endpoint can use to address packets to the destination.

The `NEW_CONNECTION_ID` and `RETIRE_CONNECTION_ID` frames affect these sets and have different semantics depending on whether they are sent or received.

1. Received:
- `NEW_CONNECTION_ID`: If possible, add a connection id to the `send_active` set. This is not possible if doing so would mean that the size of the `send_active` set is larger than the `active_connection_id_limit` TP.
- `RETIRE_CONNECTION_ID`: Remove a connection id from the `receive_active` set. 
2. Sent:
- `NEW_CONNECTION_ID`: Add a connection id to the `receive_active` set. 
- `RETIRE_CONNECTION_ID`: Remove a connection from the `send_active` set. 

The `send_active` and `receive_active` sets seem like they should be properties of the connection itself. Paths on the other hand, seem to have a single source cid and destination cid at any particular time. Changing either of those values indicates a connection migration of some kind and, therefore, a new path construction. 

In neqo, the path's `remote_cid` seems to be the currently active destination cid; the path's `local_cids` vector seems to be a vector of cids from which the peer will choose a source cid. In other words, the path's `remote_cid` should be a member of the `send_active` set while the path's `local_cids` is the `receive_active` set. Finally, there is the `connection_ids` vector in neqo that does not appear to correspond to either of these sets in a meaningful way (as I described above). 

I would love your feedback on this description and I would love to be corrected where I am (inevitably) wrong. If it is possible to settle on language around these sets of connection ids, perhaps it would be possible to hash out a plan to make their handling a little more consistent and make it easier for the future when the neqo implementation uses the `NEW_CONNECTION_ID` and `RETIRE_CONNECTION_ID` frames more extensively.

**Comment by agrover** [comment]
`connection_ids` is just placeholder code. see #130 and #104, the code for handling RetireConnectionId is just wrong. Please send a PR to fix this brokenness? :smiley:

**Comment by hawkinsw** [comment]
I have some code I am working on! I hope to have some time this weekend to
work on it!

**Comment by hawkinsw** [comment]
Just wanted to leave an update on where I am with overall progress on dealing with connection ids. This is mostly a note to myself, but I also was hoping to make it obvious that my work on this continues. If you are interested in what is in this note, please let me know. I have not tried very hard to make this useful to anyone but me, so I apologize if it is confusing or unclear. I am happy to clarify!

I have a branch (not online yet), that has changes to `Connection`:

- Added an `ActiveCids` data structure. This can be used to manage multiple, active connection ids.

- Removed `valid_cids` and replaced it with two structures:
1. `send_cids`: The Cids that this connection will use for transmitted packets
2. `receive_cids`: The cids that this connection will accept in transmitted packets.

- Changed Connection's `is_valid_cid` to check against `receive_cids` using the `ActiveCids::is_valid()` function

- Updated the `receive_cids` during handshake. Removed that value once the new connection handshake is complete.

- Added a `valid_connection_id_limit()` function that checks whether the connection-id-related transport parameters agreed during during handshake are valid. This includes things like ... This function is called from `Connection::set_connected()`. Added unit tests for these things.

- Added additional handling to the `input_frame` function for `Frame::NewConnectionId` frames.

- Added additional handling to the `input_frame` function for `Frame::RetireConnectionId` frames.

Changes to `Path` will be necessary as well. Those changes are coming next. There's some more to do, but I think that I am getting close. I am sorry about not having as much time to work on implementing this as I said I would. I hope that there will be more rapid progress in the future (I am slowly getting used to the rhythms of my new job!).
