### ISSUE TITLE
Reset loss recovery timers when discarding keys

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#450]
> When Initial or Handshake keys are discarded, the PTO and loss detection timers
are reset

This is new in specs, but it was previously unclear.

**Comment by agrover** [comment]
depends on #472?

**Comment by martinthomson** [comment]
This doesn't depend on #472.  It's more that we should be ensuring that when we make progress with the handshake, we also bump the PTO timer.  Right now, we base PTO on the time of the last packet we sent.  This would create a different base, which is when keys were dropped.

**Comment by martinthomson** [comment]
Already fixed.  I don't know when.
