### ISSUE TITLE
Update README.md to indicate that mercurial is "required"

### ISSUE THREAD

**Issue by hawkinsw** [mozilla/neqo#469]
If a user has not compiled nss separately (according to `Faster Builds with Separate NSS/NSPR` in the README.md), they "must" have mercurial installed in order to build nss. If the user does not have that package installed, neqo-crypto cannot clone nss (an obvious prerequisite for building it) and it fails with no informative error message. 

Would you be open to a PR to the README.md that indicates that is required? (Perhaps it is also a good idea to list that `gyp` is required for building, as well?)

**Comment by AyoAlfonso** [comment]
Hi @hawkinsw check if this is descriptive enough

https://github.com/mozilla/neqo/pull/470

**Comment by martinthomson** [comment]
I just landed #470, so this is done.

**Comment by hawkinsw** [comment]
Thanks @martinthomson !!
