### ISSUE TITLE
Do the massive Huffman decode tables help?

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#48]
huffman_decode_helper.rs is pretty big.  In theory, this is to help make the decoding process more efficient, but we don't have any evidence that a simpler design is significantly less efficient.  These files are impossible to review, so they really have to justify their existence pretty well.

**Comment by ddragana** [comment]
I implemented in this way because our http2 code uses it. I do not know if we have ever tested a simpler design.
