### ISSUE TITLE
NSS_Initialize failed

### ISSUE THREAD

**Issue by EngAlaaEmad** [mozilla/neqo#482]
i followed the readme instruction to build Neqo but when i ran this command 
`./target/debug/neqo-server 12345 -k key --db ./test-fixture/db` i got this error 

```
thread 'main' panicked at 'NSS_Initialize failed: NssError { name: "PR_LOAD_LIBRARY_ERROR", code: -5977, desc: "Failure to load dynamic library" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
any help please , Thanks in advance

**Comment by martinthomson** [comment]
This is the result of not having `$LD_LIBRARY_PATH` (or `$DYLD_LIBRARY_PATH`) set.  When you build using an external NSS, the binaries don't get correctly annotated and so you have to tell it where NSS is manually.  I haven't worked out why the linker ignores instructions that should have fixed this.

**Comment by EngAlaaEmad** [comment]
i understood but how can i fix it, please?

**Comment by abbcdfin** [comment]
Hi @martinthomson,
Just want to check by "correctly annotated", do you mean the rpath inserted during the building process? I would like to have a look at this issue if it has not been resolved yet. Thanks.

**Comment by martinthomson** [comment]
Yes, attempting to set the rpath by passing arguments to the linker doesn't seem to work (or at least I tried several approaches and got nowhere).  If you have more experience with this, then I'd be very happy for the help.

**Comment by abbcdfin** [comment]
Hi @martinthomson,

Sorry for could not attending this issue earlier, got stuck with something at work.

Previously the thing does not make sense to me is that if NSS was built inside the project, then we do not need to set the LD_LIBRARY_PATH. After reading the Cargo Book, it makes sense now.
>The rustc-link-search instruction tells Cargo to pass the -L flag to the compiler to add a directory to the library search path. The optional KIND may be one of dependency, crate, native, framework, or all. See the rustc book for more detail.
>These paths are also added to the dynamic library search path environment variable if they are within the OUT_DIR. 

Regarding setting the rpath in the build script, seems it is still an open issue in Cargo:
[https://github.com/rust-lang/cargo/issues/5077](https://github.com/rust-lang/cargo/issues/5077)

So far I could not think of any cleaner way of doing this. What was your plan previously?

Cheers.

**Comment by martinthomson** [comment]
Don't stress about timing.  We're muddling along with LD_LIBRARY_PATH :)

All I had was the rpath tweak, which [the docs seem to imply is possible](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-cdylib-link-argflag), but as you say it doesn't work (I will concede that maybe I'm just not holding it right).

**Comment by edgul** [comment]
I haven't had a moment to fully investigate, but in case this is helpful to someone, here is my experience with this issue.

After building neqo in `$HOME/mozilla/neqo` with external `$HOME/nss` and `$HOME/nspr` with environment variable set, I was able to run `cargo run --bin neqo-server -- [::]:12345 --db ./test-fixture/db`. But then in new shell `./target/debug/neqo-client http://127.0.0.1:12345/` was yielding similar error as [comment 1](https://github.com/mozilla/neqo/issues/482#issue-577334563).

Exporting proper variables did not work.
Exporting variables in new shell did not work.
Rebuilding nss (clean) and neqo (clean) did not work.

It was only after re-cloning neqo in a different dir `$HOME/neqo` and rebuilding did I get past the error. (At this point I am not certain if re-clone into same dir location would have worked, so worth mentioning).
