### ISSUE TITLE
Can Neqo use NSS system libs on Linux?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#499]
My Fedora install has nss-devel 3.49.2. Do we need to continue to build NSS as part of the Neqo build process, or can there be an option to rely on the prebuilt system library, @martinthomson? If this is not currently possible, will there be some future NSS version where it will be possible?

**Comment by martinthomson** [comment]
We'd have to avoid attempts to statically link, but it should be possible to use list libraries and not add to the search path.  Maybe as an option, mostly because Fedora is rare in that it includes NSS, and we don't want to have to probe for NSS.
