### ISSUE TITLE
Ack timers for discharged pn spaces

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#513]
In the current implementation, it cannot happen that the ack_timer is set for a space for which we have discharged keys. I am afraid that we will reorder something in the code and produce a bug that we have a timer but we do not have keys. Such a state will cause us to return timer == 0ms until the end of a connection. This is not good.
We should make sure to disable an ack_timer when we remove keys.

**Comment by martinthomson** [comment]
Note also that there are cases that require us to send when we have disposed of Initial keys.  That's massively awkward for us (that might be a separate bug).
