### ISSUE TITLE
Investigate why #511 is needed, given that SentPackets list should be cleared in recovery code

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#514]
as mentioned in [this comment](https://github.com/mozilla/neqo/pull/511#issuecomment-605283472), I don't understand the circumstances under which the recovery code would still be tracking `SentPacket`s for dropped `PNSpace`s, given it looks like they are cleared out. Are more being added somehow??

Should we implement a scheme to make it impossible to add SentPackets to recovery tracking after the pnspace is dropped?

**Comment by ddragana** [comment]
@martinthomson I think we can close this one? All this code has been refactored.

**Comment by martinthomson** [comment]
Yeah, I think that this is OBE.
