### ISSUE TITLE
Docker image is too big

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#515]
See https://github.com/mozilla-necko/neqo-qns/

We should slim this down, although I'm not sure what the goal should be for total size? 1GiB? @martinthomson?

**Comment by martinthomson** [comment]
My estimation would be much closer to 200Mb.  Alpine is only 5Mb, NSS libraries are < 15Mb, and there might be a few system libraries to pull in.  Assuming we only need our client and server binaries (and that they are statically linked) our binaries dominate the space at <50Mb each. We should need only two or three.  We could strip them to bring them down further, but we probably want debug info.

**Comment by martinthomson** [comment]
This is fixed.
