### ISSUE TITLE
Use Vec::drain_filter when available

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#522]
This code has bothered me for a while, because it seems inefficient (two inverse filters means redundancy).   It's better than dumb iteration, but it isn't perfect.

https://github.com/mozilla/neqo/blob/44dfdbf112b62a423258683629762cb023d4b81a/neqo-qpack/src/decoder.rs#L68-L75

Turns out that `Vec::drain_filter` is [coming](https://github.com/rust-lang/rust/issues/43244).  When that becomes stable, we should move to using that.  `drain_filter(|i| {/* logic here */}).collect()` will be much nicer.

**Comment by MightyPork** [comment]
ftr, I solve a similar problem with the combination of drain.filter_map.collect, moving the removed elements to a separate vec in the filter_map callback

https://github.com/rust-lang/rust-clippy/issues/4433#issuecomment-611006622

**Comment by larseggert** [comment]
@martinthomson this is now https://github.com/mozilla/neqo/blob/32ef2c3cb2f0f13c6b46222d98c3316a69d7b411/neqo-qpack/src/decoder.rs#L93-L98

Anything left to do?

**Comment by martinthomson** [comment]
This would be better with drain_filter(), but what we have is fine.  Given that drain_filter is taking SOOOO long to stablize, we might just give up on it.
