### ISSUE TITLE
hex() should just convert to hex, it shouldn't prepend the length in brackets

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#524]
This is limiting its use cases. For the times we do want the length, maybe we can add a second function, maybe `hex_with_len()` or similar.

**Comment by undef1nd** [comment]
@agrover hey, 
does only one line `ret.push_str(&format!("[{}]: ", buf.len()));` need to be removed from the function? Or do I need to change something except that?

**Comment by agrover** [comment]
That fixes `hex` but you also should look at all the places it is used and decide if we want the length field printed or not, maybe we want to use the version that does include the length. Some judgment calls to make here.

**Comment by undef1nd** [comment]
> Some judgment calls to make here.
@agrover So here's my version #532  :-)
