### ISSUE TITLE
Implement support for more interop tests (Client)

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#529]
We'd like to implement support for more tests than just the one I started with, the "http3" test. Here's a brain dump of how I did work on our interop Docker image.

Steps:
1. Get a Linux box
1. install Docker
1. Clone git repo that contains our QNS image Dockerfile from https://github.com/mozilla-necko/neqo-qns/
1. Run `sudo docker build .` from within the repo.
1. Note the hex value after "Successfully built".
1. Clone interop runner repo from https://github.com/marten-seemann/quic-interop-runner
1. Run something like: `sudo ./run.py -d --server quicgo --client neqo -t http3 -m "" -r neqo=<hex value>` where hex value is from the earlier step.

This is running the test using the container you built as client. "-t http3" means run the http3 test, as one of the tests listed [here](https://github.com/marten-seemann/quic-interop-runner#test-cases). Giving another test will undoubtedly fail. Adding support for a new test may probably involve making neqo-client have behavior it previously did not have. neqo-client has a `qns-mode`, where such behavior can be customized (although this is extremely simple at the moment.)

### Developing within containers
One thing is that running the interop tests requires the client and server to be containerized. This makes development and debugging somewhat more difficult -- one can use the -r flag to point at a locally-built container, but each time the Dockerfile or neqo-client binary are changed, the image needs to be rebuilt, and the new image id hex value used.
### Updating neqo-client
The Dockerfile build script handles cloning the repo and compiling neqo-client, and by default it pulls mozilla/neqo master branch. For development I had to modify the Dockerfile to point somewhere else (I pointed it at agrover/neqo, and checked out a special temp branch). So, trying out code involved committing it locally, pushing it to the temp branch, rebuilding the image (recompiles everything) and then I could test it. There's also aggressive image caching so running `docker build` won't actually re-pull the repo unless I cleared out images and containers first.

Part of all this difficulty was that our Docker image is Ubuntu-based, whereas I run Fedora. A neqo-client built natively did not have proper library versions available to run when copied into the container. If the host OS and the container OS match so this is not an issue, I'd suggest shortening the dev/debug loop by instead modifying the Dockerfile to just `COPY` a new neqo-client binary into the container.

If you need additional info, or find out improved ways to do things, please let me know! There's also an online course [here](https://mozilla.udemy.com/course/docker-tutorial-for-devops-run-docker-containers/) that might not be a total waste of time.
### Tests
- [ ] versionnegotiation
- [x] handshake
- [x] transfer
- [x] retry
- [x] resumption
- [x] zerortt
- [x] http3
- [x] multiconnect
- [x] chacha20

**Comment by marten-seemann** [comment]
> 1. Get a Linux box
> 1. install Docker
> 1. Clone git repo that contains our QNS image Dockerfile from https://github.com/mozilla-necko/neqo-qns/
> 1. Run sudo docker build . from within the repo.

Docker **should** run on OSX (and Windows, for that matter) as well. Or is there any reason why you're mandating building on Linux here?

> 4. Run sudo docker build . from within the repo.
> 5. Note the hex value after "Successfully built".
> 6. Clone interop runner repo from https://github.com/marten-seemann/quic-interop-runner
> 7. Run something like: sudo ./run.py -d --server quicgo --client neqo -t http3 -m "" -r neqo=<hex value> where hex value is from the earlier step.

Tip: You can run `docker build . -t <tagname>` in 4. and then use that name in 7.: `-r neqo=<tagname>`. This might alleviate some of the pain you experienced when developing with containers (although of course you still have to rebuild your container after you change your code).
Also, thanks to https://github.com/marten-seemann/quic-interop-runner/pull/82, the `-m ""` is not needed any more.

>  So, trying out code involved committing it locally, pushing it to the temp branch, rebuilding the image (recompiles everything) and then I could test it. There's also aggressive image caching so running docker build won't actually re-pull the repo unless I cleared out images and containers first.

This caching issue annoyed me as well when working on the quic-go image. I use the following trick to force Docker into rebuilding the image: https://github.com/lucas-clemente/quic-go/blob/4ae1a1350368c2e21f4213b71faf492f487e14bf/interop/Dockerfile#L11-L12.

**Comment by agrover** [comment]
> Or is there any reason why you're mandating building on Linux here?

Not a mandate, just what I used. Maybe Docker on Windows Just Works but I didn't try it...

**Comment by vonasek** [comment]
versionnegotiation is disabled at this moment, so we're not going to implement it now
