### ISSUE TITLE
Convert http3-server to use Tokio instead of mio

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#530]
Could be cool, and possibly interesting to see how Neqo worked with an async event model. It already kind of does so this might actually be a good fit.

**Comment by xpepermint** [comment]
Actually, it would be great to support arbitrary async runtime.

**Comment by larseggert** [comment]
CC @mxinden

**Comment by mxinden** [comment]
I am not sure what `http3-server` refers to nowadays. https://github.com/mozilla/neqo/pull/1581 and https://github.com/mozilla/neqo/pull/1612 move `neqo-server` and `neqo-client` to `tokio`.

While I believe asynchronicity is a helpful tool, I do very much agree with the argument that it adds complexity and that it is infectious to a codebase (e.g. read ["what color is your function"](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/)). Thus I suggest driving I/O in an asynchronous fashion, but keeping the core of `neqo` (i.e. `neqo-common`, `neqo-transport`, `neqo-http3`, `neqo-crypto`) synchronous.

With the two pull requests and the above argumentation, I believe this can be closed. Agreed @larseggert?
