### ISSUE TITLE
Take another look at encoder.rs, decoder.rs and table.rs

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#539]

**Comment by mahakbansal2019** [comment]
hey @ddragana  !!
I would like to work on this 
Could you please explain what I need to do here?
Thanks

**Comment by ddragana** [comment]
I do not know what exacly needs to be done here. The issue is to actually figure out that to do.

**Comment by ddragana** [comment]
Closing this. There was some refactoring of this code already (#616 #598 #617 #611 #612 #614 )
