### ISSUE TITLE
Second Initial packet from a client wil open a new connection at a server

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#540]
In log posted at https://github.com/mozilla/neqo/issues/505#issuecomment-610590139
our http3  server receives a PTO packet with a PING in the Initial pn space and itt is opening a separate connection.
From the log the second connection is open at:
0s200ms INFO [CryptoStates] Creating initial cipher state role=Server dcid=[8]: fbeb94be4f96d8f4

**Comment by ddragana** [comment]
Also at line:
0s227ms INFO [CryptoStates] Creating initial cipher state role=Server dcid=[8]: fbeb94be4f96d8f4

**Comment by martinthomson** [comment]
This isn't inherently a problem unless the server doesn't have a neat way of discarding state.  In theory at least, these could be separate connection attempts.  That they share a network path in addition to the destination connection ID is probably an indication that they aren't though.  So we should dedupe.
