### ISSUE TITLE
Enforce maximum values for stream offsets and stream ID limits

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#546]
STREAM and CRYPTO frames could include unreferenceable data if the sum of the offset and length exceed 2<sup>62</sup>-1.  We should check that.

MAX_STREAMS or the max_stream_limit transport parameter can encode values larger than 2<sup>60</sup>.  Those values are unusable and so they are not permitted in the protocol. 

We don't enforce either restriction, but we could and fairly easily.  The frame parser is easy to tweak to return an error if these values are too large.  Same for the handling of the transport parameter.

**Comment by ddragana** [comment]
Fixed by #608
