### ISSUE TITLE
Turn on clippy pedantic for neqo-transport

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#553]
Like #547 did for neqo-http3, and the previous work on crypto and other of our crates.

**Comment by abbcdfin** [comment]
Hi @agrover,

Good day. I was trying to work on this issue, but when I tried to do the clippy check I got this:
[jian@arch-dev neqo]$ cargo clippy -p neqo-transport -- -W clippy::pedantic
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s

However, when I use the same method to check neqo-server, seems it kind of worked.
[jian@arch-dev neqo]$ cargo clippy -p neqo-server -- -W clippy::pedantic
    Checking neqo-server v0.3.1 (/home/jian/openlab/neqo/neqo-server)
error: integer type suffix should be separated by an underscore
...

I am new to rust, would you please let me know the proper way to start the check?

Thanks and Best Regards

**Comment by i-am-jeetu** [comment]
Yes, @abbcdfin is right. Apart from removing `#![deny(clippy::pedantic)]` from neqo-transport, there is nothing else to do.

**Comment by martinthomson** [comment]
`cargo clippy -- -W clippy::pedantic` returns a lot of warnings for me (though I'm on rust 1.44 and so a little ahead of the curve).

Here's a taste:

```
warning: binding's name is too similar to existing binding
    --> neqo-transport/src/connection.rs:5387:13
     |
5387 |         let scid = dec.decode_vec(1).expect("client SCID");
     |             ^^^^
...
error: Unnecessary boolean `not` operation
   --> neqo-transport/src/cc.rs:183:9
    |
183 | /         if !self.in_congestion_recovery(sent_time) {
...
error: item name starts with its containing module's name
   --> neqo-transport/src/crypto.rs:239:1
    |
239 | / pub enum CryptoDxDirection {
...
error: adding items after statements is confusing, since items exist from the start of the scope
   --> neqo-transport/src/crypto.rs:292:9
    |
292 | /         const INITIAL_SALT_27: &[u8] = &[
```
