### ISSUE TITLE
Handshake fails with custom client

### ISSUE THREAD

**Issue by piano-man** [mozilla/neqo#555]
I'm using a custom client to connect to the neqo server.
However, the handshake never completes and this is what I get on the server side :-

_Event: StateChange { conn: ActiveConnectionRef { c: RefCell { value: ServerConnectionState { c: Server Connection: Closing { error: Transport(CryptoAlert(120)), frame_type: 6, msg: "CryptoAlert(120)", timeout: Instant { tv_sec: 21793, tv_nsec: 997789700 } } None, last_timer: Instant { tv_sec: 21793, tv_nsec: 997789700 } } } }, state: Closing(Transport(376)) }_

Are there any obvious reasons this could be happening ?
NOTE :- The client being used successfully completes handshakes with several other QUIC Implementations.

**Comment by agrover** [comment]
Just to be clear, neqo-server or neqo-http3-server?

**Comment by piano-man** [comment]
neqo-http3-server

**Comment by martinthomson** [comment]
`Transport(376)` is a failure to agree on ALPN.

That means that you are likely not advertising a value that we like for the application protocol name.  Tip of tree insists on 'h3-27'.

**Comment by piano-man** [comment]
Ah, I updated the alpn to h3.
I now run into this :- 

thread 'main' panicked at 'assertion failed: `(left == right)`                                                                                                                
left: `20`,                                                                                                                                                                
right: `22`', neqo-transport/src/crypto.rs:159:13                                                                                                                          
stack backtrace:                                                                                                                                                               
0:     0x7f0ac6419294 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30                                                                                                                       
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-
0.3.40/src/backtrace/libunwind.rs:88                                               1:     0x7f0ac6419294 - 
backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732                                                                                                                   
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66                                                     
2:     0x7f0ac6419294 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2                                                                                                                       
at src/libstd/sys_common/backtrace.rs:84                                                                                                        
3:     0x7f0ac6419294 - <std::sys_common::backtrace::_print::DisplayBacktrace as 
core::fmt::Display>::fmt::hfe37fa5de6572965                                                                            at 
src/libstd/sys_common/backtrace.rs:61                                                                                                        
4:     0x7f0ac643674c - core::fmt::write::h74887d18db27282c                                                                                                                                             
at src/libcore/fmt/mod.rs:1025                                                                                                                  
5:     0x7f0ac6414e27 - std::io::Write::write_fmt::h6808f3d5eceed5e5                                                                                                                                    
at src/libstd/io/mod.rs:1426                                                                                                                    
6:     0x7f0ac641b42e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef                                                                                                                           
at src/libstd/sys_common/backtrace.rs:65                                                                                                        
7:     0x7f0ac641b42e - std::sys_common::backtrace::print::h1c9c5c1c0505592d                                                                                                                            
at src/libstd/sys_common/backtrace.rs:50                                                                                                        
8:     0x7f0ac641b42e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59                                                                                                                    
at src/libstd/panicking.rs:193                                                                                                                  
9:     0x7f0ac641b121 - std::panicking::default_hook::h1b037d2bf0657ab3                                                                                                                                 
at src/libstd/panicking.rs:210                                                                                                                 
10:     0x7f0ac641bb0b - std::panicking::rust_panic_with_hook::h787d7f532b084b9a                                                                                                                         
at src/libstd/panicking.rs:471                                                                                                                 
11:     0x7f0ac641b6be - rust_begin_unwind                                                                                                                                                               
at src/libstd/panicking.rs:375                                                                                                                 
12:     0x7f0ac641b600 - std::panicking::begin_panic_fmt::h8df736026eee128c                                                                                                                              
at src/libstd/panicking.rs:326                                                                                                                 
13:     0x7f0ac5eef62b - neqo_transport::crypto::Crypto::buffer_records::h43b53b85c5fd3fc0                                                                                                               
at neqo-transport/src/crypto.rs:159                                                                                                            
14:     0x7f0ac5e6fb41 - neqo_transport::connection::Connection::handshake::hfc12860b485b2e93                                                                                                            
at neqo-transport/src/connection.rs:1462                                                                                                       
15:     0x7f0ac5e71883 - neqo_transport::connection::Connection::input_frame::h8d02c8e50a472a01                                                                                                          
at neqo-transport/src/connection.rs:1566                                                                                                       
16:     0x7f0ac5e675ba - 
neqo_transport::connection::Connection::process_packet::hbff52fcaebddd70c                                                                                                       
at neqo-transport/src/connection.rs:992                                                                                                        
17:     0x7f0ac5e65e8b - neqo_transport::connection::Connection::input::h0414558a769fb7f6                                                                                                                
at neqo-transport/src/connection.rs:934                                                                                                        
18:     0x7f0ac5e5fc3b - neqo_transport::connection::Connection::process_input::h8b50c45f8448edef                                                                                                        
at neqo-transport/src/connection.rs:691                                                                                                        
19:     0x7f0ac5e61b57 - neqo_transport::connection::Connection::process::h8d0aedd2804ca45c                                                                                                              
at neqo-transport/src/connection.rs:782                                                                                                        
20:     0x7f0ac5e80e20 - neqo_transport::server::Server::process_connection::hbbaa36339416808e                                                                                                           
at neqo-transport/src/server.rs:256                                                                                                            
21:     0x7f0ac5e8510e - neqo_transport::server::Server::accept_connection::hb57a336992ab4dcf                                                                                                            
at neqo-transport/src/server.rs:409                                                                                                            
22:     0x7f0ac5e825a8 - neqo_transport::server::Server::handle_initial::h3285b7d345e1877e                                                                                                               
at neqo-transport/src/server.rs:306                                                                                                            
23:     0x7f0ac5e86f4f - neqo_transport::server::Server::process_input::h99b044c4bee45c0d                                                                                                                
at neqo-transport/src/server.rs:454                                                                                                            
24:     0x7f0ac5e87dc8 - neqo_transport::server::Server::process::he36139ca1a0c9fed                                                                                                                      
at neqo-transport/src/server.rs:485                                                                                                            
25:     0x7f0ac5d0f7e0 - neqo_http3::server::Http3Server::process::h0ce5eca15795c05f                                                                                                                     
at neqo-http3/src/server.rs:63                                                                                                                 
26:     0x7f0ac5cce121 - neqo_http3_server::process::ha08b621eafde3ecf                                                                                                                                   
at neqo-http3-server/src/main.rs:138                                                                                                           
27:     0x7f0ac5cd07f1 - neqo_http3_server::main::hebe15f369bb38384                                                                                                                                      
at neqo-http3-server/src/main.rs:293                                                                                                           
28:     0x7f0ac5cfac45 - std::rt::lang_start::{{closure}}::h543a3431d1265556                                                                                                                             
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
29:     0x7f0ac641b553 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7                                                                                                                    
at src/libstd/rt.rs:52                                                                                                                         30:     
0x7f0ac641b553 - std::panicking::try::do_call::hccaa7cebf2335ab2                                                                                                                                 
at src/libstd/panicking.rs:292                                                                                                                 
31:     0x7f0ac641f8da - __rust_maybe_catch_panic                                                                                                                                                        
at src/libpanic_unwind/lib.rs:78                                                                                                               
32:     0x7f0ac641bfa0 - std::panicking::try::h3ce8e2e4440720f0                                                                                                                                          
at src/libstd/panicking.rs:270                                                                                                                 
33:     0x7f0ac641bfa0 - std::panic::catch_unwind::h2a767bac361346af                                                                                                                                     
at src/libstd/panic.rs:394                                                                                                                     34:     
0x7f0ac641bfa0 - std::rt::lang_start_internal::h14e7168ba039f170                                                                                                                                 
at src/libstd/rt.rs:51                                                                                                                         35:     
0x7f0ac5cfac19 - std::rt::lang_start::ha2b0340a149d5c46                                                                                                                                          
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
36:     0x7f0ac5cd1d9a - main                                                                                                                                               
37:     0x7f0ac4971b97 - __libc_start_main                                                                                                                                  
38:     0x7f0ac5cc436a - _start                                                                                                                                             
39:                0x0 - <unknown> 

Is this because of a version mismatch ?

**Comment by martinthomson** [comment]
I need to make that error more visible, or work out why it happens to people so often.

This is the result of either TLS 1.2 being negotiated or TLS 1.3 compatibility mode being enabled.  That only happens if the client does something wrong.  I haven't had time to track it down.

**Comment by piano-man** [comment]
Oh, this is pretty surprising considering the client that I'm using uses only TLS 1.3. 
It's also strange that I haven't run into this issue with other server side implementations if there is something wrong at the client side.

**Comment by martinthomson** [comment]
If the client sends a session ID in its ClientHello, then our stack will flip into TLS 1.3 compatibility mode and send a ChangeCipherSpec message.

**Comment by piano-man** [comment]
Ah, okay.
So just to be clear, is this a problem from the client side or is this something that should be handled by neqo-http3-server ?

**Comment by martinthomson** [comment]
Both in fact.  The client shouldn't be doing this, but we should reject the connection and not crash.

**Comment by martinthomson** [comment]
Resolved this in #556 and in the spec.
