### ISSUE TITLE
Hit expect in DynamicTableEntry::add_ref

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#566]
https://bugzilla.mozilla.org/show_bug.cgi?id=1628886

Hit expect [here](https://github.com/mozilla/neqo/blob/45b963f41bd8ed6a44f2ab9b2b8afb436fc9ed1c/neqo-qpack/src/table.rs#L172)

**Comment by agrover** [comment]
Dynamic tables are currently disabled, right? So maybe this should be medium priority. @ddragana what say you?

**Comment by ddragana** [comment]
the problem is that this is happening when the dynamic table is disabled.
I am looking at issue #539. That will fix this one. (although I would like to understand why this is happening. I was looking at the issue but could not figure out the reason)

**Comment by ddragana** [comment]
I have figured out this. I will make PR and explained it.
