### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)` ;  neqo-transport/src/connection.rs:1800:13

### ISSUE THREAD

**Issue by piano-man** [mozilla/neqo#571]
I'm running into this assertion repeatedly while trying to test the server :-

thread 'main' panicked at 'assertion failed: `(left == right)`                                                                                                                
left: `Closing { error: Application(3), frame_type: 0, msg: "HTTP/3 error: 
TransportError(InvalidStreamId)", timeout: Instant { tv_sec: 49070, tv_nsec: 915562528 } }`,    right: 
`Closing { error: Transport(NoMoreData), frame_type: 0, msg: "NoMoreData", timeout: Instant { 
tv_sec: 49070, tv_nsec: 915562528 } }`', neqo-transport/src/connection.rs:1800:13                                                                                                                                                                 
stack backtrace:                                                                                                                                                               
0:     0x7ff79a01c274 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30                                                                                                                       
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-
0.3.40/src/backtrace/libunwind.rs:88                                               1:     0x7ff79a01c274 - 
backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732                                                                                                                   
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66                                                     
2:     0x7ff79a01c274 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2                                                                                                                       
at src/libstd/sys_common/backtrace.rs:84                                                                                                        
3:     0x7ff79a01c274 - <std::sys_common::backtrace::_print::DisplayBacktrace as 
core::fmt::Display>::fmt::hfe37fa5de6572965                                                                            at 
src/libstd/sys_common/backtrace.rs:61                                                                                                        
4:     0x7ff79a03972c - core::fmt::write::h74887d18db27282c                                                                                                                                             
at src/libcore/fmt/mod.rs:1025                                                                                                                  
5:     0x7ff79a017e07 - std::io::Write::write_fmt::h6808f3d5eceed5e5                                                                                                                                    
at src/libstd/io/mod.rs:1426                                                                                                                    
6:     0x7ff79a01e40e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef                                                                                                                           
at src/libstd/sys_common/backtrace.rs:65                                                                                                        
7:     0x7ff79a01e40e - std::sys_common::backtrace::print::h1c9c5c1c0505592d                                                                                                                            
at src/libstd/sys_common/backtrace.rs:50                                                                                                        
8:     0x7ff79a01e40e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59                                                                                                                    at src/libstd/panicking.rs:193                                                                                                                  
9:     0x7ff79a01e101 - std::panicking::default_hook::h1b037d2bf0657ab3                                                                                                                                 
at src/libstd/panicking.rs:210                                                                                                                 
10:     0x7ff79a01eaeb - std::panicking::rust_panic_with_hook::h787d7f532b084b9a                                                                                                                         
at src/libstd/panicking.rs:471                                                                                                                 
11:     0x7ff79a01e69e - rust_begin_unwind                                                                                                                                                               
at src/libstd/panicking.rs:375                                                                                                                 
12:     0x7ff79a01e5e0 - std::panicking::begin_panic_fmt::h8df736026eee128c                                                                                                                              at src/libstd/panicking.rs:326                                                                                                                 
13:     0x7ff799a79513 - neqo_transport::connection::Connection::set_state::h2871015810c14670                                                                                                            
at neqo-transport/src/connection.rs:1800                                                                                                       
14:     0x7ff799a70891 - neqo_transport::connection::Connection::close::h83845dea1166ad8b                                                                                                                
at neqo-transport/src/connection.rs:1387                                                                                                       
15:     0x7ff79994b62c - neqo_http3::connection_server::Http3ServerHandler::check_result::h0c9126ad37f52fb3                                                                                              
at neqo-http3/src/connection_server.rs:108                                                                                                     
16:     0x7ff799916118 - 
neqo_http3::connection_server::Http3ServerHandler::process_http3::he248611ac0ded248                                                                                             
at neqo-http3/src/connection_server.rs:78                                                                                                      
17:     0x7ff799939cfa - neqo_http3::server::Http3Server::process_http3::h933c900f859b7173                                                                                                               
at neqo-http3/src/server.rs:115                                                                                                                
18:     0x7ff799938fdb - neqo_http3::server::Http3Server::process::hab5803e3dd1c29dd                                                                                                                     
at neqo-http3/src/server.rs:69                                                                                                                 
19:     0x7ff7998f3b71 - neqo_http3_server::process::h3a149c14fa5dc438                                                                                                                                   at neqo-http3-server/src/main.rs:138                                                                                                           
20:     0x7ff7998f6241 - neqo_http3_server::main::h6aa7153e49695641                                                                                                                                      
at neqo-http3-server/src/main.rs:293                                                                                                           
21:     0x7ff7998d5055 - std::rt::lang_start::{{closure}}::hc1b0e3b5c168faf0                                                                                                                             
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
22:     0x7ff79a01e533 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7                                                                                                                    
at src/libstd/rt.rs:52                                                                                                                         
23:     0x7ff79a01e533 - std::panicking::try::do_call::hccaa7cebf2335ab2                                                                                                                                 
at src/libstd/panicking.rs:292                                                                                                                 
24:     0x7ff79a0228ba - __rust_maybe_catch_panic                                                                                                                                                        
at src/libpanic_unwind/lib.rs:78                                                                                                               
25:     0x7ff79a01ef80 - std::panicking::try::h3ce8e2e4440720f0                                                                                                                                          at src/libstd/panicking.rs:270                                                                                                                 
26:     0x7ff79a01ef80 - std::panic::catch_unwind::h2a767bac361346af                                                                                                                                     
at src/libstd/panic.rs:394                                                                                                                     27:     
0x7ff79a01ef80 - std::rt::lang_start_internal::h14e7168ba039f170                                                                                                                                 
at src/libstd/rt.rs:51                                                                                                                         28:     
0x7ff7998d5029 - std::rt::lang_start::hfa029e01f5dc3197                                                                                                                                          
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
29:     0x7ff7998f77ea - main                                                                                                                                               
30:     0x7ff798571b97 - __libc_start_main                                                                                                                                  31:     0x7ff7998c44ba - _start                                                                                                                                             
32:                0x0 - <unknown>

**Comment by piano-man** [comment]
I was wondering what exactly is the cause for this ?

**Comment by ddragana** [comment]
neqo_transport::Connection is probably in "Closed" state and the http3 server calls close() that try to change state into "Closing". We should have check somewhere that connection is already in Closed state and ignore this state change.
If you can make me a log, I want to figure out what is the right place to do it in the Http3 code or in transport or both.

**Comment by piano-man** [comment]
Sure, how do you recommend I make the log ?

**Comment by ddragana** [comment]
This has bin fixed by #649
