### ISSUE TITLE
Time loss recovery uses two variables

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#574]
The following test crashes:

```rust
    #[test]
    fn loss_recovery_crash() {
        const TIME_SHIFT: Duration = Duration::from_secs(1);
        let mut client = default_client();
        let mut server = default_server();
        connect(&mut client, &mut server);
        let now = now();

        // The server sends something, but we will drop this.
        let _ = send_something(&mut server, now);

        // Then send something again, but let it through.
        let ack = send_and_receive(&mut server, &mut client, now);
        assert!(ack.is_some());

        // Have the server process the ACK.
        let cb = server.process(ack, now).callback();
        assert!(cb > Duration::from_secs(0));

        // Now we leap into the future.  The server should regard the first
        // packet as lost based on time alone.
        let dgram = server.process(None, now + TIME_SHIFT).dgram();
        assert!(dgram.is_some());

        // This crashes.
        let _ = send_something(&mut server, now + TIME_SHIFT);
    }
```

This appears to be the result of using two different variables when we move to time loss recovery.  I need to do more investigation to track this down.

**Comment by martinthomson** [comment]
OK, after some digging, I think that we might need to re-examine how we integrate loss recovery into the code.

Right now, two functions drive loss recovery state: 

1. we call `detect_lost_packets` at the start of `process_output`, this sets `enable_timed_loss_detection` as necessary

2. we call `calculate_timer` at the end of `process_output`, but only do that if we don't have a packet to send.  This updates `loss_recovery_state`.

Unfortunately, these two variables are linked.  If you don't send anything, but have ack-eliciting packets outstanding, then you will be on a loss recovery timer.  In the test above, that happens when the server consumes the ACK.

If you call back after some time, then you are likely to resend lost packets (the next call to `process` in the above.  This doesn't update `loss_recovery_state`, but it does update `enable_timed_loss_detection`.

The result is that we are now in a state where these two variables are out of sync.

**Comment by ddragana** [comment]
This is #505. Michal was debugging it and came to the same conclusion.
This is partially a reason I want to rethink how we call timers and output() function (my comment on #550 ).
We can fix this separately, but we should rethink these couple of functions: process, process_timers, next_delay, output...

**Comment by ddragana** [comment]
I am wandering should the output of process_output be multiple Datagrams? That would make the code in process_output easier, because we do not need to care if app called process_output as many time as we want, it will not be app dependent.
Some thoughts:
- check loss-recover (process lost packets, or pto), calculate next timer for lost_recovery, return back cwnd and flags
- check pacing and adjust cwnd and the timeout value
- if (cwnd >0) -> produce output Datagrams (this may trigger app-limited state... need to think about this more)
- return Datagrams and a timeout value

**Comment by martinthomson** [comment]
After digging in here, I think that most of this is the result of implementing the spec.  I don't like the spec very much in terms of the design that is suggests.  Our faithful implementation of the spec has resulted in this bug, and has made our code a little more complex and less performant than it should be.

This is a long post, and it might look like lots of changes, but I don't think that it is that bad.

# Actions/inputs

## ACK

Here we need to:
* adjust the RTT estimate
* increase/decrease the congestion control window
* detect lost packets
** maybe enable time-based recovery (if we detect a gap)
** maybe cancel the PTO timer (if the highest sent packet number is acknowledged)

## Send Packet

In this case we adjust our accounting:
* reduce the available congestion control window
* reduce the pacing budget
* shift the PTO timer

## On a Time-Based Recovery Timeout

Here we need to find and mark packets as lost.  The time-based recovery timer is reset if there are outstanding packets lower than the largest acknowledged still outstanding.

The reference code uses the same function for this and the processing that is performed after receiving an ACK.  This could be separate code, as this invocation will never declare a packet lost due to the packet number threshold.  We could decide that the time-based threshold only applies here and the number-based threshold applies only to the ACK handling.  That might open up some optimization options.

## On a PTO Timeout

Here we increase the PTO counter and add a budget of PTO packets (we currently allow two packets to be sent).

We should also skip a sending packet number to better encourage the sending of an ACK from our peer, but that is something we need to investigate more.

## Instructions

These inputs can all accrue to a set of instructions to the main connection.

### Timing Instructions

If the time-based loss recovery is active, that 9RTT/8 timer will always be smaller than the PTO, so we should go with that.  That timer runs even if there are no ack-eliciting packets outstanding.  

Otherwise, if we have ack-eliciting packets outstanding, then the PTO timer should dictate the time.

If the pacer blocks the sending of a packet, then we should check that timer against any other timer.

(We also have the ACK delay, the key update timer, and the idle timer to add to this mix, in case any of those are sooner.)

### Sending Instructions

We can (and probably should) build these up as we go.  That saves us from duplicating work, and - more importantly - it avoids us having two ways to calculate the same information that might end up disagreeing.

Other than the disagreement on the time-based loss recovery here, the main consideration there is that when the PTO timer fires we should save which packet number space had the PTO.

So then sending becomes something like:

```
if PTO:
    send a regular packet
    take from PTO budget
else:
    if CC budget available:
        if pacing budget available:
            send a regular packet
            take from CC and pacing budgets
        else:
            activate pacing timer
            don't send anything
    else:
        send a packet that can only contains an ACK
```

**Comment by martinthomson** [comment]
After tooling around with this for a good while, I've concluded that the maintenance of a single timer is the problem.  A single enum with Null, TimedLossDetection, PtoTimer, and PtoExpired doesn't work because needing time-based loss detection is not orthogonal to needing to PTO.

Though the time-based loss detection timer is always shorter than a PTO interval, it does not always start before.  If you send an ack-eliciting packet that goes to probing, you can subsequently send a bunch of ACK-only packets, in which you might detect some being out of order and engage time-based loss recovery.

The only sensible approach here is to do as we have done and keep independent state and then synthesize that state into a single value.  Contrary to my previous comment, I don't think that we should have a state variable for tracking the outcome of that calculation.  It is fairly easy to iterate through packet number spaces and pull off the timers.  Similarly, it is easy to iterate through each space looking for actions.  (We can optimize later by dropping the Initial and Handshake spaces if necessary.)  For the PTO packet counter, that can just sit on the loss recovery object directly.
