### ISSUE TITLE
client: parse html and fetch subresources

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#582]
It would be neat if neqo-client could fetch a URL and then parse the output for subresources, and then fetch those too.

This would let us use neqo-client to test usage more akin to browser usage model -- multiple streams and multiple origins.

I think this would be a good first issue for someone because it doesn't require a lot of QUIC knowledge, it would just require finding and using existing crates for HTML parsing to generate a list of additional URLs, and then mods to client to fetch these.

**Comment by ddragana** [comment]
We are not planning to implement this.
