### ISSUE TITLE
Multiple Connection support

### ISSUE THREAD

**Issue by piano-man** [mozilla/neqo#590]
Does the neqo-http3-server support multiple parallel connections currently ?
If yes, is there a defined limit to the number of parallel connections it can support ?

**Comment by ddragana** [comment]
> Does the neqo-http3-server support multiple parallel connections currently ?

yes, it supports multiple connections

> If yes, is there a defined limit to the number of parallel connections it can support ?

There is no limit

**Comment by piano-man** [comment]
Thanks :)
