### ISSUE TITLE
Reduce timer granularity constant

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#593]
from https://github.com/mozilla/neqo/pull/591#issuecomment-622251047

> We should also look to reducing our timer granularity constant. It's currently 20ms, which is far too high.

**Comment by agrover** [comment]
It used to be that 10ms was the standard timer resolution on non-realtime OSes. It may be shorter now but don't know for sure.

**Comment by martinthomson** [comment]
We should probably be running our networking process at a high enough priority so that we can rely on a better resolution.  Maybe we should attempt to measure this.

(My recollection is that Windows was 15.6ms, but that was a long time ago.)

**Comment by ddragana** [comment]
I think there is an API to retrieve this. We can try to get it in necko(it is probably easier to get it in c++ code) and set it as a parameter in neqo. I will open a bug for this.

**Comment by ddragana** [comment]
15.6ms is correct at least on some windows versions. I have seen it in some telemetry probes.

**Comment by agrover** [comment]
How would Neqo behave differently if it knows the OS's timer granularity vs just asking for a timeout and then being called later than expected due to the OS timer granularity?

**Comment by martinthomson** [comment]
We force certain values to be greater than the timer granularity.  The rttvar component of the PTO calculation and the loss detection timer are two.  In cases where we have a very small RTT (in the order of 20ms currently) a larger granularity will degrade performance.  Given how common that sort of RTT is in practice, it's worth spending a little time on getting finer timer granularity.

With a dedicated socket process, perhaps we can experiment with asking the OS for higher resolution timers, such as by using [these Windows APIs](https://docs.microsoft.com/en-us/windows/win32/multimedia/timer-resolution), though there might be some abstraction that gecko provides instead.  The process might decide what resolution to ask for based on what our stack asks for.

**Comment by martinthomson** [comment]
I think that we should just tweak this value.  Take a look at [this simple program](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=a1ebe1012d4ba6dbbaf9e265b788ed98).  It reliably reports a delay of no more than 130μs in every run I have ever tried there.  But that runs on Linux.  The same program shows a lag of up to about 15.6ms on windows, again consistent with experience.

I think that this might be contributing to our laggardly performance in some synthetic testing.  It would be good to understand how to improve the timer resolution here.

**Comment by martinthomson** [comment]
More digging with https://github.com/martinthomson/rust-hrtimer shows that the windows media APIs work and produce in the order of 1ms resolution (there was one instance that was very slightly over this target).  Next step is to build something that can be used from Rust to manage this safely.  We can grab one of those and attach it to a connection.

**Comment by ddragana** [comment]
I was searching m.-c. and it looks like we use a higher resolution timer sometimes. In the necko code we use it when there are many http1.1 requests or when we do not know that server speaks H2 or H3 (it is used when we try to pace request). So we probably already run firefox from time to time with the higher resolution timer.
We can easily implement this in necko (just copy a couple of lines), but to make neqo better as an independent project probably it would be better to do it in neqo
