### ISSUE TITLE
ACK more when we think peer is still in slow start

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#594]
from https://github.com/mozilla/neqo/pull/591#issuecomment-622251047

> ...send ACK more often while the peer is likely still in slow start. This is the least important, but mainly only because it is essentially impossible to know what the status of the peer congestion controller is. The way that others have done this is apply a guess. I can see us doing all sorts of things for this, but a simple function of the packet number might be an easy way to do something reasonable.)

**Comment by agrover** [comment]
if pn < 100 ack_every_other else ack_every_ten?

Or do some logarithmic thing. We could call it exponential ACK-off :drumfill:

**Comment by martinthomson** [comment]
Exponential ACK-off sounds good.  We can make it a logarithm of the CWND measured in PMTU units, capped by `log(pn)`.

**Comment by martinthomson** [comment]
Let's do #966 instead.
