### ISSUE TITLE
Rewrite to avoid usage of SliceDeque crate

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#60]
transport send stream uses SliceDeque to get a single slice of bytes to send, even though the buffer is circular and therefore can sometimes require two slices if the buffer wraps. (It does this with virtual memory magic.)

This is cool but probably not worth the added dependency. We should rewrite to use a regulat VecDeque. Either the users of `next_bytes` must handle two slices, or maybe we're ok with next_bytes not returning the entire range of available bytes if it wraps (could lead to two smaller stream frames instead of one, perhaps?)

**Comment by gnzlbg** [comment]
The commit message mentions that `slice_deque` does not work on FreeBSD, but I use it on FreeBSD regularly. What was the reason for the removal?

**Comment by ddragana** [comment]
the reason was:
https://bugzilla.mozilla.org/show_bug.cgi?id=1594342
it was OpenBSD.

**Comment by gnzlbg** [comment]
This was reported to slice deque a couple of months ago, and support for OpenBSD was added immediately :/
