### ISSUE TITLE
Make sure loss recovery works with very high reordering

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#602]
A long time ago (so I hope I remember this correctly) someone was telling me that they have seen a very high reordering of UDP packets where a packet was received after 100 other packets. The cause was some priority mechanism in a router that that was preferring small packets over big packets.

**Comment by martinthomson** [comment]
I can confirm that transferring 100M with randomized delay between 0 and 50ms in the simulation works fine after fixing #867, but I'm confident that we're OK now.
