### ISSUE TITLE
qlog: Add mode that includes payload

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#607]
@vonasek mentioned that it might be useful if qlog included payload. This could help make using tools like Wireshark less needed.

Since payload is 1) large and 2) possibly sensitive, we probably don't want to do this by default when doing qlog.

**Comment by hawkinsw** [comment]
Working on this. Currently blocked by https://github.com/cloudflare/quiche/issues/785

**Comment by ddragana** [comment]
Thanks!

**Comment by hawkinsw** [comment]
FYI: Patch accepted to fix qlog issue. Upstream will roll a new crate asap and then we can continue work on this issue.

**Comment by larseggert** [comment]
We're using qlog much less than expected, so I'm not sure if this is worthwhile to pursue.
