### ISSUE TITLE
neqo-http3-server: Handle UdpSocket::send_to() errors

### ISSUE THREAD

**Issue by vonasek** [mozilla/neqo#628]
We need to handle errors returned from UdpSocket::send_to() instead of expecting a success.

**Comment by agrover** [comment]
I'm :+1:  for this but just curious, did you actually see this fail so far in practice?

**Comment by vonasek** [comment]
I've seen the error thrown from UdpSocket::send() in neqo-client, so I guess UdpSocket::send_to() can fail too. Btw. what exactly we need to do in this case to release everything related to that connection in Http3Server?

**Comment by agrover** [comment]
This is in `emit_packets` -- by that time there's no way to link this back to which connection the packet was for. Also, I'm not sure it's the right thing to do to close connection if `send_to` fails. I don't have a full picture why it would fail, other than some kernel queue is full? Knowing that I think would really help. Should we drop the datagram... or just wait until we can try to send it again?

**Comment by larseggert** [comment]
OBE
