### ISSUE TITLE
Does it make sense to limit stream send buffer size?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#63]
Right now we have a fixed 64KiB buffer per stream. Along with connection and stream-level flow controls, this buffer's capacity also restricts the application's ability to queue data for sending.

Does this make sense? Doesn't this just mean that the application will end up queueing data above the SendStream queue -- even though flow control credits are available -- that the application could free if the SendStream took ownership, so there's no real memory savings from limiting sendstream buffer capacity?

**Comment by martinthomson** [comment]
I don't think so.  If an application wants to hand data off to us, and the peer is willing to receive it into their flow control window, then I don't see why we shouldn't just take it.  Sure, we might be congestion- or rate-limited and unable to send, but maybe the app wants to offload it.

It's different when it's flow control, for which we should provide back pressure.

That all said, for responsiveness reasons, we shouldn't buffer more than we really need to keep the congestion window full.  That's a function of how fast the app can respond to the buffer draining, how fast it wants to keep calling in, and how fast the network is.

**Comment by ddragana** [comment]
If we look at Firefox as the primary user of neqo, Firefox will keep data in HttpTransaction even if it gives it to neqo, because it may need to replay it.

And responsiveness is important so we should not buffer too much data. We want to be able to react on priority changes.

**Comment by martinthomson** [comment]
Yes, Firefox might need to replay an HTTP transaction, but I think that we can treat that logically as having received different values, as it will be on a different stream (or even a different connection, protocol, etc...).

**Comment by ddragana** [comment]
> Yes, Firefox might need to replay an HTTP transaction, but I think that we can treat that logically as having received different values, as it will be on a different stream (or even a different connection, protocol, etc...).

yes, of course it will be different values. I was just responding to Andy's comment about freeing buffers above SendStream queue(in this case Firefox's buffers). Firefox will not do it until it gets response. Large buffering in neqo will not help the memory usage. But it is important to buffer a bit more than the congestion window, if possible.

**Comment by martinthomson** [comment]
To be correct, you mean a BDP, right?  Doesn't that depend more on how able we are to provide new data?  If we can turn around new bytes in less than N msec, then we only need the estimated bandwidth times N in the buffer.

**Comment by ddragana** [comment]
yes, it would be N x bandwidth. 

Note: On the. client side (our main scenario) this is not that important. In firefox, the same loop will drive writing data to quic and writing quic packets to the network, the buffering will not have much influence. We should add some telemetry to measure how jittery is our packet sending, how fast we actually send out packets when we can send packets. This will be influenced by operations on other sockets.
