### ISSUE TITLE
Attempting 0-RTT when not possible

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#637]
The h3 client sets `Http3State::ZeroRtt` when resumption is attempted.  It doesn't consult the transport to determine whether 0-RTT is possible.  Of course, any attempt to send will be blocked by the transport, but maybe it shouldn't try.

Should we expose the transport's zero_rtt_state variable somehow, to let the h3 code make a better decision?

**Comment by ddragana** [comment]
We should check the transport's zero_rtt_state variable.
