### ISSUE TITLE
Can RxStreamOrderer::read only return u64?

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#646]
Can we remove try in this line:
let copy_offset = (max(range_start, self.retired) - range_start).try_into()?;

https://github.com/mozilla/neqo/blob/6d3af7c667dc6361b70e80cdd957eacf5f861679/neqo-transport/src/recv_stream.rs#L233

This will let read() only return u64.
(I am documenting some neqo-transport errors that are important for reasoning about what errors http3 can get so to better document http3 code)

**Comment by martinthomson** [comment]
As this is a count, shouldn't we instead return `usize`?
