### ISSUE TITLE
Macro for display functions

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#672]
Having to write out the display function (which we use in logging) is annoying.  A macro that routed to `format!()` would make this a lot less painful.

**Comment by martinthomson** [comment]
This task is largely mechanical.  Most of our implementations of `Display` are essentially the same, containing a single `write!()` macro.  Building a macro to do the entire implementation in a form something like `display!(Connection, "{:?}...", self.role)` seems simple enough for someone with basic Rust macro knowledge.

**Comment by martinthomson** [comment]
Hi @akshay26031996, it's unusual to have patches contributed in this way.  Generally we prefer pull requests.  

That said, the code you have seems like a great start.  Can you create a pull request?  That will make it easier to discuss.

**Comment by akshay26031996** [comment]
Hi @martinthomson 
I have created a [pull request](https://github.com/mozilla/neqo/pull/712).
Please review.
Thanks

**Comment by hawkinsw** [comment]
Is this issue still open? I am confused by the PRs from @akshay26031996 . If it's still open, I'd be happy to take a look at it.

**Comment by martinthomson** [comment]
I think that we can set this aside.  Thanks for the reminder.

(Andy suggested a crate that might help, but our needs are modest enough.)
