### ISSUE TITLE
Draft 28

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#679]

**Comment by agrover** [comment]
@martinthomson do you mind commenting on the scope of changes needed for draft 28? I heard there was one that didn't make it into the changelog....?

Also, thoughts on supporting both draft 27 and 28 in the code. We want to support 28 since interop testing has moved to it rather quickly, but 27 is already in use by major sites and we'd like to keep support for 27 because who knows how long before they support 28.

**Comment by martinthomson** [comment]
The main change here is the one that missed the changelog (it's in the editor's copy though).

The main task here will be to bump version numbers again.  But if we want to support two concurrent versions, it gets a little interesting.  We don't have compatible upgrades, so we still have to pick a version, I'm guessing based on Alt-Svc.

We could do the client end of this, but it might be easier to do both ends for testing purposes.

Mostly the changes are trivial, but the rules for handling connection ID authentication change a lot between the versions.  We'd have to put in two sets of logic if we wanted to support both versions.  I don't know how much work that would be, but probably not a whole lot.


Changelog analysis follows
----

Allowed CONNECTION_CLOSE in any packet number space, with a requirement to use a new transport-level error for application-specific errors in Initial and Handshake packets -> #625 

Clearer requirements for address validation -> noop for us currently

Security analysis of handshake and migration -> noop

The entire payload of a datagram is used when counting bytes for mitigating amplification attacks -> not sure what happens, but we can ignore it

Connection IDs can be used at any time, including in the handshake -> noop

Only one ACK should be sent for each instance of reordering -> already done

Remove text allowing a server to proceed with a bad Retry token -> already done

Ignore active_connection_id_limit with a zero-length connection ID -> feature not implemented

Require active_connection_id_limit be remembered for 0-RTT -> feature not implemented

Require ack_delay not be remembered for 0-RTT -> already done

Redefined max_packet_size to max_udp_datagram_size -> we probably need to implement this TP

Guidance on limiting outstanding attempts to retire connection IDs -> feature not implemented 

Restored text on dropping bogus Version Negotiation packets -> already done

Clarified that largest acknowledged needs to be saved, but not necessarily signaled in all cases -> not affected

Addressed linkability risk with the use of preferred_address -> feature not implemented

Added authentication of handshake connection IDs -> IMPORTANT

Opening a stream in the wrong direction is an error -> already done

**Comment by martinthomson** [comment]
@agrover let me know if you need help with the handshake connection ID authentication thing.  I don't currently plan to do the work, but it isn't that hard if you need the extra help.
