### ISSUE TITLE
stream_send_atomic -> Res<bool>

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#680]
There are only three valid return values from this function 1. error, 2. nothing was sent, 3. everything was sent.  That leads me to recommend `Res<bool>` rather than `Res<usize>` for this.

**Comment by agrover** [comment]
Would be a good first contribution but I think #644 already did this..

**Comment by martinthomson** [comment]
Ooops.  Shows how carefully I reviewed that :p
