### ISSUE TITLE
Rename enable_ciphers() to set_ciphers()

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#683]
opened as a minor tangent to reviewing #681..

If you don't call `Connection::enable_ciphers()`, it doesn't mean that ciphers aren't enabled (that would not work of course), it just means the default ciphers are chosen and used. So, not a bug but an unclear implication.

A clearer name would be `set_ciphers()` for the methods in both `Connection` and `Agent`.

**Comment by i-am-jeetu** [comment]
Created a PR  #737 :). A tiny contribution.
