### ISSUE TITLE
neqo-client: use common logging macros

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#685]
Now that neqo-client is getting more attention and gaining features (and failure modes) it's probably time to move beyond our current text output to something a little better.

Right now it is only using `println` for normal output and `eprintln` for error output. We should look at these callsites and see if they should be log messages instead, using neqo-common's qerror, qinfo, qwarn, qdebug, and qtrace macros.

**Comment by larseggert** [comment]
CC @mxinden since you are touching this code now.
