### ISSUE TITLE
meta: Implement support for more interop tests (Server)

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#699]
See #529 for client equivalent

### Tests
- [x] versionnegotiation
- [x] handshake
- [x] transfer
- [x] retry
- [x] resumption
- [x] zerortt
- [x] http3
- [x] multiconnect
- [ ] amplification limit

**Comment by agrover** [comment]
Since we mainly want to support server interop tests because it will give us insight into our client upload performance and congestion control implementation, supporting all of these is probably not needed. If we support some of: (transfer, transferloss, multiconnect, http3) that might be enough.

**Comment by agrover** [comment]
see #676

**Comment by martinthomson** [comment]
Closing in favour of #1183, as that is the last remaining piece here.
