### ISSUE TITLE
Sending request body is broken after PR657 landed

### ISSUE THREAD

**Issue by vonasek** [mozilla/neqo#713]
Tests test_post and test_patch don't work anymore after https://github.com/mozilla/neqo/pull/657 landed. SendMessage::send_body() returns 0 at https://github.com/mozilla/neqo/blob/fe7dc008b4b93060cb32998f59114069c464c75c/neqo-http3/src/send_message.rs#L136 which is translated to NS_BASE_STREAM_WOULD_BLOCK on necko side. This triggered an assertion due to bug [1644374](https://bugzilla.mozilla.org/show_bug.cgi?id=1644374). After fixing bug [1644374](https://bugzilla.mozilla.org/show_bug.cgi?id=1644374) the connection times out.

**Comment by ddragana** [comment]
This needs to be fixed in necko.

**Comment by agrover** [comment]
Going to be fixed (likely) in Necko, but there may be Neqo changes at some point too.
