### ISSUE TITLE
Automate generation of QNS Docker images

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#738]
We do this already for Docker image used for CI (pushing to "docker" branch kicks it off")

For QNS interop, could we regenerate QNS docker image for every PR that lands?

**Comment by martinthomson** [comment]
dockerhub will do builds on push if you configure it to do so.  But you can't have the Dockerfile in a different repository.  This would require moving the QNS Dockerfile into this repository.  That's probably worth doing anyway.

**Comment by agrover** [comment]
Yeah we should do that. I really just put it in another repo so I wouldn't muck up the main one, early on.

**Comment by martinthomson** [comment]
It's demonstrated its value, and the amount of code seems manageable, yeah.

**Comment by martinthomson** [comment]
OBE
