### ISSUE TITLE
We do not send MaxStreamData and we do not respond to StreamDataBlocked

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#741]
https://interop.seemann.io/logs_2020-06-16T18:21:06UTC/quic-go_neqo/transferloss/output.txt

In this log the test tiems out because server cannot send us more data and we never send MaxStreamData. We get a StreamDataBlocked but we do not respond to it.

**Comment by ddragana** [comment]
in this log https://interop.seemann.io/logs_2020-06-16T18:21:06UTC/quic-go_neqo/transfercorruption/output.txt

we send some MaxStreamData frames but at the end of the log server is blocked. I think it is connected to loss packet or maybe we do not consume data (consuming data is not in the log).

**Comment by ddragana** [comment]
there is a issue #35

**Comment by agrover** [comment]
Keeping this open until we're sure the issue is resolved.
