### ISSUE TITLE
0-RTT test on interop runner fails

### ISSUE THREAD

**Issue by vonasek** [mozilla/neqo#743]
https://interop.seemann.io/logs_2020-06-16T18:21:06UTC/quic-go_neqo/zerortt/output.txt

**Comment by martinthomson** [comment]
From the transport layer, it's hard to see how this is a problem, but there might be higher-level issues:

```
client          | 0s140ms DEBUG [Client 0x7ffe3ac97eb8] Enabled 0-RTT
...
client          | 0s140ms DEBUG Building Initial dcid a537ff217d9d376ea34950 scid 
client          | 0s140ms DEBUG Emitting crypto frame space=in, offset=0, len=512
client          | 0s140ms DEBUG [Client 0x7ffe3ac97eb8] pn=0 type=Initial
client          |   TX -> Crypto { offset: 0, len: 512 }
client          | 0s141ms DEBUG Building ZeroRtt dcid a537ff217d9d376ea34950 scid 
client          | 0s141ms DEBUG [Client 0x7ffe3ac97eb8] pad Initial to path MTU 1357
... At this point we have 0-RTT keys, but the HTTP stack hasn't asked to send anything.
... There is no logging that indicates that they might have.
... Nothing more happens until we get an ACK for the Initial we sent.
client          | 0s174ms DEBUG [Client 0x7ffe3ac97eb8] pn=0 type=Initial
client          |   -> RX Ack { largest_acknowledged: 0, ack_delay: 0, first_ack_range: 0, ack_ranges: [] }
client          |   -> RX Crypto { offset: 0, len: 96 }
```

**Comment by martinthomson** [comment]
Looking at the client code, I think that we somehow lost something: there used to be code in both Post- and PreConnectHandlers for dealing with making requests, but that doesn't seem to be the case any more.  I think that we need to eliminate the distinction between the two if we are going to keep 0-RTT working properly.  A single handler will likely do the job well enough.

**Comment by vonasek** [comment]
With change https://github.com/vonasek/neqo/commit/ac98468c84c19daee56f5d9a5e5424c97aa8e542 0-RTT packet is sent. But the test still fails because we do 3 handshakes instead of 2.

**Comment by vonasek** [comment]
Interesting, I cannot reproduce the problem with 3 handshakes anymore.

**Comment by vonasek** [comment]
This was fixed by https://github.com/mozilla/neqo/pull/765
