### ISSUE TITLE
Should Neqo have separate timer expired and input packet methods instead of just one for both?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#75]
It might be more straightforward to have Neqo have separate process packet and timer expired calls, instead of one that signifies either one, or the other, or both has occurred.

**Comment by martinthomson** [comment]
In thinking about this one, I think that all we need is two functions:

1. absorb packet (called `process_input` today)
2. do something that might trigger actions from the caller

The `Output` enum accurately captures those actions: nothing, wait, send a packet.

Now all you need to do as a caller is call 1 if you get a packet, or call 2 when you are done with the task neqo gave you.  I think that's clean and simple.  From a caller perspective, I don't see what is different in responding to a timeout as opposed to asking for more actions.

Internally, that means that we should be running timer hooks on `process_output`.

**Comment by agrover** [comment]
mt is asking a different question so I opened #159.
