### ISSUE TITLE
RttVals::max_ack_delay doesn't need to be a variable

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#751]
We set it to MAX_ACK_DELAY and then it never changes. Maybe we just use MAX_ACK_DELAY directly?

**Comment by martinthomson** [comment]
We should be setting this value based on [transport parameters](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-18.2-4.28).

**Comment by martinthomson** [comment]
This was fixed in #894.
