### ISSUE TITLE
Check pseudo-header fields

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#753]
produce a stream error H3_GENERAL_PROTOCOL_ERROR if header block is malformed (section [4.1.3](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-malformed-requests-and-resp)):
- the presence of prohibited fields or pseudo-header fields
- the absence of mandatory pseudo-header fields
- invalid values for pseudo-header fields
- pseudo-header fields after fields
- an invalid sequence of HTTP messages
- the inclusion of uppercase field names
- the inclusion of invalid characters in field names or values

**Comment by i-am-jeetu** [comment]
I was tackling this. Have a look at the draft below, and see if the checks are performed at the right place. Currently, only the inclusion of uppercase characters in field names are handled. #780

**Comment by ddragana** [comment]
Note: some of this checks are perform in the firefox platform code, but they should be in neqo.
