### ISSUE TITLE
Errors from multiple layers

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#757]
In a meeting the issue was raised: How should we interpret errors that can come from multiple layers?

For example, InvalidStreamId can come from neqo-qpack but also neqo-transport, and may need to be treated differently depending on which one raised the error.

**Comment by ddragana** [comment]
I will write down some documentation about how some API functions propagate through different layers and what will be the best way to handle errors.

**Comment by ddragana** [comment]
PR that came out of this task:
PR #769 , PR #770 , PR #800 , PR #801 , PR #802 , PR #803 , PR #805 
and Issue #804 

I have decided to document errors in the code and also add assertion where it was needed. The PRs above are documenting and fixing issues with the error handling in http3(mostly) and in transport code.

**Comment by agrover** [comment]
@ddragana is this issue complete or still in progress? Thanks.

**Comment by ddragana** [comment]
done
