### ISSUE TITLE
QNS: Turn down output level for client tests

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#764]
By setting `RUST_LOG=debug` in run_endpoint.sh we are getting the full spew of debug messages when running QNS. I don't think other implementations are nearly so noisy.

Maybe we should turn this down (to "warn"?) once things are mostly working? We might decide we don't need it if we are using pcap or qlog files to diagnose and fix issues instead of debug output.

@vonasek what do you think, about either making this change now, or in the future?

**Comment by vonasek** [comment]
> @vonasek what do you think, about either making this change now, or in the future?

I'll try to measure if debug logging level affects performance. If not we might lower the logging level later.

**Comment by vonasek** [comment]
Transferring 50MB file over 100Mbps takes ~23 seconds with debug level and ~18 seconds with info/warn. Official QNS interop runner uses 10Mbps and there is no difference, it takes ~46 seconds in case of all logging levels.

**Comment by agrover** [comment]
Thanks, good to have some hard info on this.

Currently I'm finding the info useful so am not looking to turn this down in the near future, but only some day.

**Comment by martinthomson** [comment]
Let's bin this one.  There are tweaks we might make to the level of individual logging statements (I think that transport parameters can be logged at trace rather than debug), but it is still useful to have the logging and it doesn't appear to cost much, if anything.
