### ISSUE TITLE
Track spurious retransmissions

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#781]
We use the spec-recommended values for packet threshold and time threshold. Tracking cases where a retransmission was unneeded ("spurious") could show if those values are not optimal.

This could be done by tracking how many packets are acked after they have been declared lost, and their contents presumably retransmitted. We track such packets for a bit after they are declared lost, but after a lost packet is no longer tracked, we would not recognize its ack as indicating a technically-unneeded (spurious) retransmission.

**Comment by ddragana** [comment]
WE already have this.
