### ISSUE TITLE
API: Unique identifier for a Connection

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#787]
For such things as naming logs of connections and otherwise referring to a connection, it would be useful to have a unique name (string) for each connection. The client code is currently doing `conn.path().unwrap().remote_cid()` but this is a bit too chummy with Connection internals, and also won't work for all Role::Server Connections.

ref: https://github.com/mozilla/neqo/pull/782#discussion_r448712450

**Comment by martinthomson** [comment]
We fixed this one in #890.
