### ISSUE TITLE
Spec-defined initial RTT is too conservative / needs caching

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#79]
The spec says 500ms, which hurts too much unless you can remember the (presumably lower) RTT from an earlier session.

@martinthomson :
> The problem here is that if you are going to have this function, then you need to have a means of caching path RTT or you always end up having terrible connection establishment performance. There's the overbearing conservatism in transport areas in the IETF that say that you can't send packets too fast or the network melts. That's not really the case, but we keep getting stuck with these ridiculous constants.

> There is good justification for building some sort of RTT caching, at which point a longer default is good for everyone, but that is lots of work and complex. I'd prefer that we just keep this relatively low and leave an open issue for doing the caching.

**Comment by martinthomson** [comment]
@undef1nd helpfully wrote some code for us here.  It's not ideal as we only do this as part of resumption, such that a server that doesn't offer a session ticket won't get this behaviour.  Most servers use tickets, so I'm going to say that we're good here.
