### ISSUE TITLE
Stats about dropped packets

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#792]
Count number of drop packets.
We should count 2 kind of drops separately:
- packets cannot be decrypted, due to corruption
- packets are duplicate

Add these stats to:
https://github.com/mozilla/neqo/blob/master/neqo-transport/src/stats.rs

**Comment by martinthomson** [comment]
Don't we already have this?  Or do you think that we need to count different types of drop?

**Comment by ddragana** [comment]
Yes, we have this already... and I have actually implemented the dup stats :)
