### ISSUE TITLE
Make a API for changing the stream receiver window per stream

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#797]
APP could increase/decrease the rwnd of a individual streams.
We may want to have an API for the session as well. Let's make one for the session as well.

**Comment by agrover** [comment]
Possibly useful, but not a required feature.

**Comment by martinthomson** [comment]
@ddragana, would gecko use this?  It's a fairly easy feature to add, but I want to make sure that it's useful in light of the `required-feature` tag.

**Comment by ddragana** [comment]
This does not need r`equired-feature` tag. I will create a PR.

**Comment by ddragana** [comment]
Fixed by #1101
