### ISSUE TITLE
Handle the case when we cannot create critical HTTP3 streams 

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#804]
Probably we should just close a connection if server does not allow us to create control, and qpack streams due to the max streamId limit.

**Comment by KershawChang** [comment]
@ddragana , I am not really sure what to do here.
It seems that the connection will be closed when `initialize_http3_connection` returns an error. Or maybe I am looking at the wrong place?

**Comment by martinthomson** [comment]
@KershawChang, it might be worth testing that this is what happens.  Closing the connection would be the right reaction, but we should at least test that case.

**Comment by ddragana** [comment]
Fixed by #1040
