### ISSUE TITLE
Periodic stalls on CF sites

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#816]
https://www.cloudflare.com/people/
https://lucaspardue.com/quictilesstatic.html
https://lucaspardue.com/quictilesfetch.html

The latter two are probably the best test cases as the first page tends to thrash the layout engine.  Occasionally fetching an image fails.  You can see that part of the image is retrieved, but it breaks half way.  It looks like recovery is failing.  This seems to be a server-side issue, but we shouldn't rule out a client problem.

**Comment by martinthomson** [comment]
This is how it manifests:

![image](https://user-images.githubusercontent.com/67641/87382506-6ff39c00-c5da-11ea-8e16-79357305ffd9.png)

**Comment by martinthomson** [comment]
It is possible that this will be fixed by #867.  I'll wait until that ships in Nightly and test again.

**Comment by ddragana** [comment]
We should update m.-c.. Let's do it this week.

**Comment by martinthomson** [comment]
I'm seeing this problem still on the latest Nightly.  I'm going to try to see what is going on.

I'm also getting some serious stalling where devtools reports image loads as "Blocked" after 30s.  That seems un-good and worth looking into.

**Comment by martinthomson** [comment]
I've tried to replicate this problem with the command-line tool and aside from the changes in #969, I can't make headway.

It is 100% reproducible though, so I think it is probably down to problems in the gecko integration.

**Comment by ddragana** [comment]
I will take a look thee gecko part.

**Comment by martinthomson** [comment]
It looks like this is working much better now.  I see hitches occasionally, but they all resolve.  Closing.  We can make a new issue if we find more problems.
