### ISSUE TITLE
QNS: server data-send tests failing

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#819]
https://interop.seemann.io/

Since we are now in QNS as a server, we have visibility that tests are failing. This is likely indicative of problems with our sending-specific code (e.g. SendStream, congestion control, pacing), so we should get these to pass.

Probably starting with the basic `transfer` test ("DC")

**Comment by vonasek** [comment]
Problem is that in stream_writable() at [this line](https://github.com/mozilla/neqo/blob/master/neqo-http3-server/src/old_https.rs#L115) we update offset but this doesn't change the value in tuple conn_state.data_to_send, so when the data isn't all sent at once the next piece starts again from 0. PR 826 fixes it, but I guess there is a better way to do it.

**Comment by agrover** [comment]
Wait, it doesn't update the tuple???

**Comment by vonasek** [comment]
> EDIT: Ok, looks like the code wasn't properly taking a ref to the offset, instead it copied it. Should have said `ref mut offset`.

Do you mean this?

`if let Some((data, &mut offset)) = &mut conn_state.data_to_send {`

I tried it and it didn't compile.

**Comment by agrover** [comment]
The syntax is a little different. If it says
`if let Some((data, ref mut offset)) = &mut conn_state.data_to_send {`
then offset is a reference to the value in the tuple instead of a copy.
