### ISSUE TITLE
ACK processing taking too long

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#825]
see [qvis](https://qvis.edm.uhasselt.be/?#/sequence?file=https%3A%2F%2Finterop.seemann.io%2Flogs_2020-07-15T06%3A20%3A53UTC%2Fquic-go_neqo%2Fgoodput%2F1%2Fclient%2Fqlog%2Fserver-0a3b987a05eec43a.qlog&focusOnConnection=0&focusOnEvent=759) and [log](https://interop.seemann.io/logs_2020-07-15T06:20:53UTC/quic-go_neqo/goodput/1/output.txt) around "pn=517"

The even distribution of timestamps on log messages makes me think the log messages are part of what is causing the delay. There also appears to be some logic inefficiency in the tracking code that is making the logging delays worse.

**Comment by martinthomson** [comment]
@agrover, We'll need to take a copy of that log so that it doesn't disappear.

**Comment by agrover** [comment]
Well it's gone, I need to grab another one.

**Comment by agrover** [comment]
This is a truncated log but shows the problem: https://gist.github.com/agrover/bda64d5d93ac43f0e83ca0ea6764e86e#file-output-log-L5594. from time=588ms to t=694ms we just print stuff. There's the possibility of algorithmic improvement but probably the first thing to do is turn down or remove that log message.

**Comment by martinthomson** [comment]
@agrover you might find that running the code from #850 helps.

**Comment by martinthomson** [comment]
I ran a brief test under the "simulation" and determined that the ACK ratio doesn't seem to affect the overall performance.

If we send fewer ACKs, it takes a little more "real" time to complete, but the total execution time doesn't seem affected.

I'm going to see if adding a PING along with ACKs helps at all.

**Comment by martinthomson** [comment]
We can close this based on #862 being merged.  This might come up again, but it's no longer dire.
