### ISSUE TITLE
QNS: handshakeloss (L1) failure with aioquic

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#828]
[Complete QNS logs](https://interop.seemann.io/logs_2020-07-16T21:22:00UTC/aioquic_neqo/handshakeloss/).

Here's an excerpt of the connection that failed: [gist](https://gist.github.com/agrover/bd946c762a415a7e6ea004db3fa50566)

From looking at the server logs it never receives the http request on stream 0.

Analysis:
Neqo never receives a 1RTT ACK, either of the packet including the stream 0 request ([here ap-4](https://gist.github.com/agrover/bd946c762a415a7e6ea004db3fa50566#file-gistfile1-txt-L347)) that was dropped or for ap-5, ap-7, or ap-8. Server sends [HandshakeDone](https://gist.github.com/agrover/bd946c762a415a7e6ea004db3fa50566#file-gistfile1-txt-L483) and it looks like this disables PTO when it should only disable PTO for hs, not ap.

Proposed solution: Neqo should not disable the 1RTT PTO timer until it receives an 1RTT Ack. This would have caused Neqo to continue to 1RTT Ping the server, which would have generated an 1RTT ack indicating ap-4 was lost and this would cause Neqo to resend the http request data.

Also weird: Why all the "security library: received bad data" messages towards the end, and is this the sign of another issue?

@martinthomson does the above look right? Thanks.

**Comment by martinthomson** [comment]
So when we receive HANDSHAKE_DONE we drop PTO state.  We do that *after* we calculate the PTO state, so if the application space has an active PTO this could be a problem, yeah.  As we still had Handshake keys prior to processing the frame, the PTO state for Application Data will have been ignored anyway.

What we need to do there is recalculate the PTO state based on the new information.  

I also note that we fire the Application Data PTO timer prior to confirmation, which is not right.  We don't report that timer, but we fire it.  That results in sending packets in the Application Data space on PTO if that time has passed.  Based on recent discussion regarding max_ack_delay, we probably need some sort of confirmation state for Application Data.

(The security library messages are packets we think can be decrypted, but we can't.)

**Comment by agrover** [comment]
Actually I'm closing this in favor of #841, I'm assuming the analysis here will no longer apply.
