### ISSUE TITLE
Accurate byte counting

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#836]
Once we are out of slow start, the integer division that we use when increasing the congestion window might end up rounding down too aggressively.  We should instead count all acknowledged bytes and drop increases to the congestion window as the total hits certain thresholds.  There is a trick in that any unrealized count needs to be reduced in the same way that we reduce the congestion window, but this is otherwise a trivial change that should result in a larger congestion window (and therefore better throughput), especially as we get a larger congestion window.

**Comment by agrover** [comment]
closed by #892
