### ISSUE TITLE
Simulating network loss & delay directly in our H/3 implementation

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#840]
@martinthomson and @ddragana I've heard tell you have some ideas for adding simulation of bad/slow network to the code itself. 

Could you use this issue to talk a little bit more about what you had in mind? Seems like a smashing idea to me, but I'm not clear exactly where you were envisioning the simulation would fit: in the Necko code wrapping Neqo? In neqo-transport? And also any other details you've hashed out already.

**Comment by martinthomson** [comment]
#850 will be the basis of this.
