### ISSUE TITLE
Generate ConnectionEvent::SendStreamCreatable at startup

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#842]
When a new stream is created, there are no new events that indicate that a stream can be created; the event is only generated when the stream limit increases.  This event should be generated whenever the stream limit is set so that using code can drive stream creation off the event alone.

This is probably the right place to do that:

https://github.com/mozilla/neqo/blob/37374c4232fb25304a30127380f70c0e66a1f4cf/neqo-transport/src/connection.rs#L1735-L1738

**Comment by ddragana** [comment]
@KershawChang do you want to take this. It is not urgent.
