### ISSUE TITLE
QNS: Corrupted packets cause assertion failure

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#847]
https://interop.seemann.io/logs_2020-07-19T13:21:06UTC/neqo_quic-go/transfercorruption/output.txt

```
thread 'main' panicked at 'assertion failed: !delays.is_empty()', neqo-transport/src/connection.rs:954:9
```

**Comment by agrover** [comment]
I'm wondering if we want to move the:
```
self.idle_timeout.on_packet_received(now);
```
line in `Connection::input()`, that currently is only called if the packet is successfully decrypted, up above the decryption? This gets `IdleTimeout` out of `Init` state, avoiding the panic here. Presumably the client will re-send based on PTO and then connection can continue if this is received before the idle timeout, or else the idle timeout expires and the connection goes away...

**Comment by martinthomson** [comment]
See #839.
