### ISSUE TITLE
We need to got through  data_ranges twice

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#869]
We do not need this [line](https://github.com/mozilla/neqo/blob/66b639986949084b03e99f88eb3cbccb74c62eb9/neqo-transport/src/recv_stream.rs#L250) 
We can collect `to_remove` in for loop above.

**Comment by martinthomson** [comment]
I can go one better: `BTreeMap::split_off` works reasonably well here if you save the iterator and use that to get the first index to save (if you need to).

**Comment by ddragana** [comment]
Fixed by #946
