### ISSUE TITLE
CC: Pacer, optional or not?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#882]
Should it be possible to instantiate a `CongestionControl` and use it without calling `start_pacer()`? Right now, we use `unwrap()` on `self.pacer` in e.g. `on_packet_sent` so this is not possible.

**Comment by martinthomson** [comment]
@ddragana, you recently touched this.  Have you any opinions?  I think that we can make the pacer mandatory.  We might be able to implicitly initialize it and improve the interface that way.

**Comment by ddragana** [comment]
We should make it mandatory. I shortly though of doing this in #964 but that got too big.

**Comment by ddragana** [comment]
It is not optional.
Fixed by #1093
