### ISSUE TITLE
Measure throughput for the net simulation tests

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#896]

**Comment by martinthomson** [comment]
The tests currently report the elapsed or simulated time.  You could use that.  Of course, this only captures end-to-end time, so you need to do a very long transfer if you want to understand the sustained rate, or start counting after the congestion window has ramped up.

**Comment by ddragana** [comment]
I wanted to add throughput measurements in the taildrop queue, e.g. start time = first packet sent, end time the last packet sent.
I actually have a patch (I open the issue to let you all know so that we do not do double work). The numbers that I get are not what I expect and I want to investigate it a bit to understand what is wrong, my measurement method or our code.

**Comment by ddragana** [comment]
I will not implement this. I tried once ant it was not as easy as I thought to get it right.
