### ISSUE TITLE
QNS client: C1 handshakecorruption fail with quant

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#903]
[quant-neqo-fail-c1.zip](https://github.com/mozilla/neqo/files/5029677/quant-neqo-fail-c1.zip)

Here are the logs. I haven't taken a look yet.

**Comment by agrover** [comment]
failing connection: 65a95cc2892a3e5d853df80dcd

**Comment by martinthomson** [comment]
Looking at the connection in question, this looks pretty benign from our end.  We do as we are required.  As we don't get acknowledgments for Handshake packets, we keep sending on PTO.  But quant appears to send just one 1-RTT packet (there is one 0.5-RTT packet that we discard and one that we drop; #891 will likely cache the latter instead, but it shouldn't change the outcome).

I don't know why quant is not sending probe packets with the HANDSHAKE_DONE, but that is what is causing this to fail.  Let's pass this on to Lars.

**Comment by martinthomson** [comment]
BTW, qvis with a time offset of -1596643637070 seems to show this without too much distortion.  Maybe someone needs to implement a time skew correction algorithm for qvis.  Or maybe we should report absolute times in our logs rather than relative ones...

**Comment by ddragana** [comment]
We will open new issues if needed.
