### ISSUE TITLE
Should all client Initial PTO packets contain crypto?

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#904]
@martinthomson:

If Initial:0 from the client is lost, after PTO fires we send Initial:1 with crypto (ClientHello) and ping, and also Initial:2 with just ping.

Why not also include ClientHello in Initial:2? It's going to be padded out to full packet size in any case.

**Comment by martinthomson** [comment]
Doing this is likely a little tricky: we don't want to mark more outstanding frames lost than we have space to send.

In any case, the purpose of the probe that is sent at PTO is less to ensure that data is retransmitted, but more to ensure that the connection exits a potential stalemate state.  Even if we send nothing, we are giving the peer a chance to send an acknowledgment.  While sending genuine data is likely better than just sending padding, the complexity involved in finding appropriate data isn't really justified.

This sort of packet loss is rare and the first PTO packet will most likely reach its destination.  Optimizing for a case where multiple packets are lost isn't high priority.
