### ISSUE TITLE
Neqo Socket Thread Crash in [@ OOM | large | mozalloc_abort | xul.dll | _PR_NativeRunThread | pr_root]

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#923]
https://bugzilla.mozilla.org/show_bug.cgi?id=1658415

**Comment by martinthomson** [comment]
https://crash-stats.mozilla.org/report/index/76892a7c-2e80-4ab2-b773-b8a2e0200809 has a usable stack trace that points to us allocating a stream.

**Comment by ddragana** [comment]
This seems to be fixed.
