### ISSUE TITLE
Expiration time for a resumption token

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#929]
Necko use the expiration time to decide if it should replace a token that is already in the cache.
The time is read from the resumption token. The token from neqo does no contain only a raw TLS token but it also has other parameters so to use nss function to extract the expiration time in necko would mean that we need to parse the token and find the start of the TLS token. I would like to avoid doing this. here is 2 option:
1) neqo does the parsing of the token and return the token with the expiration time
2) we assume that the new token is newer and we always replace a token in the cache

**Comment by martinthomson** [comment]
So newer tokens will always be more relevant.  The question is whether expiration time might cause you not to consider a particular token.

**Comment by ddragana** [comment]
I will ask Dana about this.

**Comment by ddragana** [comment]
I should have looked more carefully. I was completely wrong. We use expiration time to prioritize removing tokens from he cache, because thee cache has a limited size.

We should extract the time in neqo.
