### ISSUE TITLE
Do we need an event when a resumtion token is available?

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#930]
I think it would be better to have an event for this.

**Comment by martinthomson** [comment]
I agree.  It will take a bit of plumbing, but it is fairly simple code.

**Comment by ddragana** [comment]
Let's wait for #893 to land. WE probably want a new resumption token when we get a NEW_TOKEN frame as well.

**Comment by ddragana** [comment]
This has been fixed in #960
