### ISSUE TITLE
Provide an `Iterator` implementation for events

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#934]
I've been wondering whether we should provide an `Iterator` implementation for events so that we can do these things more efficiently.  The code you have here is roughly:

```rust
client.events().filter(|e| matches!(e, Http3ClientEvent::HeaderReady { .. })).count();
```

We could get that by doing:

```rust
trait ConnectionEventProvider {
    fn next_event(&mut self) -> Option<ConnectionEvent>;
}

struct<'a, T> ConnectionEventIter<T> {
    c: &'a T;
}
    
impl<'a, T> Iterator for ConnectionEventIter<'a, T> 
    where T: ConnectionEventProvider {
    type Item = ConnectionEvent;
    fn next(&mut self) -> Option<Self::Item> {
        self.c.next_event()
    }
}
```

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/926_

**Comment by martinthomson** [comment]
Note that this is not as general as our current structure because it depends on having a *mutable* reference to the source of events while iterating.  This is good for some cases, but not all.
