### ISSUE TITLE
Events for resumption tokens

### ISSUE THREAD

**Issue by martinthomson** [mozilla/neqo#953]
@ddragana, we should probably discuss design options in an issue rather than a pull request.

On #950 you said: 

>  My last idea was to send events when we have both. If we do not have a token we do not send an event. The app can call get_resumption_token if it needs a resumption token and it did not get an event (e.g. just before closing a connection or when an app want to create a new connection in paralel) and in that case we will return a resumption token without a TOKEN only with a ticket.
>
> The second idea I had is to send a resumption_token_event without a TOKEN just before a CONNECTION_CLOSE event, but that may be too late for an app.

These are both interesting takes on this problem.

The first fails because you don't guarantee that you ever get NEW_TOKEN for every session ticket.  There are legitimate reasons for a server to only send tickets (they don't need address validation, because they don't do 0-RTT, for instance), so that isn't great.  And we certainly can't assume that NEW_TOKEN will always be sent before the session ticket (our code sends NEW_TOKEN second).

The second suggests a way we can avoid getting completely trapped by that, but for many cases that isn't going to work well either.  We could keep our current interface, but make it clear that this only works when NEW_TOKEN isn't available (that is, we provide events when we have both and you can manually pull a session ticket).

Frankly, I think that the timer is the best option out of those presented.  Hold the event for a PTO (or three) and then let it out if we don't see NEW_TOKEN before then.

We can then drop the function for retrieving tokens.

**Comment by ddragana** [comment]
> @ddragana, we should probably discuss design options in an issue rather than a pull request.
> 
> On #950 you said:
> 
> > My last idea was to send events when we have both. If we do not have a token we do not send an event. The app can call get_resumption_token if it needs a resumption token and it did not get an event (e.g. just before closing a connection or when an app want to create a new connection in paralel) and in that case we will return a resumption token without a TOKEN only with a ticket.
> > The second idea I had is to send a resumption_token_event without a TOKEN just before a CONNECTION_CLOSE event, but that may be too late for an app.
> 
> These are both interesting takes on this problem.
> 
> The first fails because you don't guarantee that you ever get NEW_TOKEN for every session ticket. There are legitimate reasons for a server to only send tickets (they don't need address validation, because they don't do 0-RTT, for instance), so that isn't great. And we certainly can't assume that NEW_TOKEN will always be sent before the session ticket (our code sends NEW_TOKEN second).
> 
> The second suggests a way we can avoid getting completely trapped by that, but for many cases that isn't going to work well either. We could keep our current interface, but make it clear that this only works when NEW_TOKEN isn't available (that is, we provide events when we have both and you can manually pull a session ticket).

That is what I suggest in the first proposal.

Any way I will create a PR for a version with a timer.
> 
> Frankly, I think that the timer is the best option out of those presented. Hold the event for a PTO (or three) and then let it out if we don't see NEW_TOKEN before then.
> 
> We can then drop the function for retrieving tokens.

**Comment by ddragana** [comment]
Fixed by #960
