### ISSUE TITLE
Send SETTINGS as soon as possible

### ISSUE THREAD

**Issue by ddragana** [mozilla/neqo#972]
... it appears as though our stack does not immediately send SETTINGS when the connection is established.  I think that it is probably worth fixing that problem to have the test pass.

_Originally posted by @martinthomson in https://github.com/mozilla/neqo/pull/970#issuecomment-701121024_

**Comment by martinthomson** [comment]
I was wrong about this one.  The test was running http/0.9.  The code appears to do the right thing.
