### ISSUE TITLE
Stream send scheduling for fairness or application priority

### ISSUE THREAD

**Issue by agrover** [mozilla/neqo#98]
Sending retransmitted ranges before new ranges I think we can do in a straightforward manner, but I don't yet understand how we should schedule to send between multiple streams with new data to send. Right now we just pick randomly (iterating a HashMap) and I think because of this stream A, because of the HashMap implementation, will consistently get first crack at sending over stream B.

This should be made fair, or perhaps, it could be based on some signal or ordering from the application, in order to give the application control over the order things are sent.

**Comment by martinthomson** [comment]
The original design I put together had (from memory) five buckets for streams with four priorities.  I'd like to move to that model.  Currently, we do ACK, crypto, "flow_mgr", and streams, which is still the right order, but we need to have streams bucketed by priority also.  Having priority buckets (and reprioritization) allows us to concentrate on streams in a deterministic order.  

As I originally thought, with four priorities we could treat retransmissions as being two slots higher on the priority ordering.  That seems simple enough, while giving some bias as needed.

After that, iterating a HashMap for equal-weighted streams isn't terrible, as long as the order is moderately stable.  But FIFO might be better.  With a HashMap, newly added streams might jump ahead of streams that are in progress.  Better to let in-progress streams complete their work first.

**Comment by agrover** [comment]
We don't care about fairness. Need settable priorities via API and also retrans bump in prio.

**Comment by martinthomson** [comment]
We have some code landed now that prioritizes sending.  See #1094.
